# -*- python -*-

tools = Split("""
boost_program_options
doxygen
FireFly
logx
lrose
qt4
QFunctionWrapper
QXmlRpcServerAbyss
""")

# Note that DrxStatus.cpp, HcrdrxRpcClient.cpp, and HcrPmc730.cpp are compiled
# via the hcrdrxrpcclient tool
sources = Split("""
fireflyd.cpp
""")

env = Environment(tools = ['default'] + tools)
env.EnableQtModules(['QtCore'])

fireflyd = env.Program('fireflyd', sources)
Default(fireflyd)

html = env.Apidocs(sources)
Default(html)
