# -*- python -*-
#
# Build HcrExecutive
#

tools = Split('''
boost_program_options
doxygen
hcrexecutiveclient
hcrpmc730client
lrose
motioncontrol
qt5
qtcore
qtxml
QFunctionWrapper
QXmlRpcServerAbyss
xmlrpc_client++
''')

env = Environment(tools = ['default'] + tools)

sources = Split('''
    HcrExecutive.cpp
    MaxPowerFmqClient.cpp
''')

headers = Split('''
    MaxPowerFmqClient.h
''')

daemon = env.Program('HcrExecutive', sources)
Default(daemon)
