# -*- python -*-
#
# Build HcrExecutive
#

tools = Split('''
hcrpmc730client
boost_program_options
doxygen
hcrexecutive
lrose
motioncontrol
qt4
QFunctionWrapper
QXmlRpcServerAbyss
xmlrpc_client++
''')

env = Environment(tools = ['default'] + tools)
env.EnableQtModules(['QtCore', 'QtXml'])

sources = Split('''
    HcrExecutive.cpp
    MaxPowerClient.cpp
''')

headers = Split('''
    MaxPowerClient.h
''')

daemon = env.Program('HcrExecutive', sources)
Default(daemon)
