# -*- python -*-

tools = Split("""
hcrdds
pentek
qtt_qtconfig
boost_date_time
boost_program_options
doxygen
qt4
""")

sources = Split("""
main.cpp
p7142hcrdnThread.cpp
""")

headers = Split("""
""")

env = Environment(tools = ['default'] + tools)

hcrdrx = env.Program('hcrdrx', sources)

html = env.Apidocs(sources + headers, DOXYFILE_FILE = "Doxyfile")

Default(hcrdrx, html)

