# -*- python -*-

tools = Split("""
boost_date_time
boost_program_options
cmigits
doxygen
hcrdrxrpcclient
logx
pentek
pmc730
qt4
qtt_qtconfig
rapradar
xmitdrpcclient
""")

# Note that DrxStatus.cpp, HcrdrxRpcClient.cpp, and HcrPmc730.cpp are compiled
# via the hcrdrxrpcclient tool
sources = Split("""
HcrDrxConfig.cpp
HcrDrxPub.cpp
HcrMonitor.cpp
IwrfExport.cpp
main.cpp
PulseData.cpp
""")

headers = Split("""
DrxStatus.h
HcrDrxConfig.h
HcrDrxPub.h
HcrdrxRpcClient.h
HcrMonitor.h
HcrPmc730.h
IwrfExport.h
PulseData.h
""")

env = Environment(tools = ['default'] + tools)

hcrdrx = env.Program('hcrdrx', sources)

html = env.Apidocs(sources + headers)

Default(hcrdrx, html)
