# -*- python -*-
#
# Build cmigitsDaemon
#

tools = ['cmigits', 'qt4']

env = Environment(tools = ['default'] + tools)
env.EnableQt4Modules(['QtCore', 'QtGui', 'QtNetwork'])

sources = ['cmigitsDaemon.cpp']

headers = ['cmigitsDaemon.h']

daemon = env.Program('cmigitsDaemon', sources)

Default(daemon)
