# -*- python -*-
#
# Build cmigitsDaemon
#

tools = ['cmigits', 'qt4', 'xmlrpc_server_abyss++', 'rapradar']

env = Environment(tools = ['default'] + tools)
env.EnableQt4Modules(['QtCore', 'QtGui'])

sources = ['cmigitsDaemon.cpp']

headers = ['cmigitsDaemon.h']

daemon = env.Program('cmigitsDaemon', sources)

Default(daemon)
