// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cordic_circ_apfixed (
        ap_clk,
        ap_rst,
        x_V_read,
        y_V_read,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [29:0] x_V_read;
input  [29:0] y_V_read;
output  [29:0] ap_return;
input   ap_ce;

reg   [0:0] tmp_141_reg_2675;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_state26_pp0_stage0_iter25;
wire    ap_block_state27_pp0_stage0_iter26;
wire    ap_block_state28_pp0_stage0_iter27;
wire    ap_block_state29_pp0_stage0_iter28;
wire    ap_block_pp0_stage0_11001;
wire   [30:0] add_ln703_fu_234_p2;
reg   [30:0] add_ln703_reg_2681;
wire   [30:0] sub_ln703_fu_240_p2;
reg   [30:0] sub_ln703_reg_2687;
wire   [30:0] sub_ln203_fu_246_p2;
reg   [30:0] sub_ln203_reg_2692;
reg   [0:0] tmp_142_reg_2697;
reg   [0:0] tmp_142_reg_2697_pp0_iter1_reg;
reg   [0:0] tmp_142_reg_2697_pp0_iter2_reg;
reg   [0:0] tmp_142_reg_2697_pp0_iter3_reg;
reg   [0:0] tmp_142_reg_2697_pp0_iter4_reg;
reg   [0:0] tmp_142_reg_2697_pp0_iter5_reg;
reg   [0:0] tmp_142_reg_2697_pp0_iter6_reg;
reg   [0:0] tmp_142_reg_2697_pp0_iter7_reg;
reg   [0:0] tmp_142_reg_2697_pp0_iter8_reg;
reg   [0:0] tmp_142_reg_2697_pp0_iter9_reg;
reg   [0:0] tmp_142_reg_2697_pp0_iter10_reg;
reg   [0:0] tmp_142_reg_2697_pp0_iter11_reg;
reg   [0:0] tmp_142_reg_2697_pp0_iter12_reg;
reg   [0:0] tmp_144_reg_2702;
reg   [0:0] tmp_144_reg_2702_pp0_iter2_reg;
reg   [0:0] tmp_144_reg_2702_pp0_iter3_reg;
reg   [0:0] tmp_144_reg_2702_pp0_iter4_reg;
reg   [0:0] tmp_144_reg_2702_pp0_iter5_reg;
reg   [0:0] tmp_144_reg_2702_pp0_iter6_reg;
reg   [0:0] tmp_144_reg_2702_pp0_iter7_reg;
reg   [0:0] tmp_144_reg_2702_pp0_iter8_reg;
reg   [0:0] tmp_144_reg_2702_pp0_iter9_reg;
reg   [0:0] tmp_144_reg_2702_pp0_iter10_reg;
reg   [0:0] tmp_144_reg_2702_pp0_iter11_reg;
reg   [0:0] tmp_144_reg_2702_pp0_iter12_reg;
wire   [30:0] select_ln101_2_fu_338_p3;
reg   [30:0] select_ln101_2_reg_2707;
wire   [30:0] select_ln101_3_fu_346_p3;
reg   [30:0] select_ln101_3_reg_2713;
reg   [28:0] trunc_ln1333_2_reg_2719;
reg   [28:0] trunc_ln1333_3_reg_2724;
reg   [0:0] tmp_145_reg_2729;
reg   [0:0] tmp_146_reg_2735;
reg   [0:0] tmp_146_reg_2735_pp0_iter2_reg;
reg   [0:0] tmp_146_reg_2735_pp0_iter3_reg;
reg   [0:0] tmp_146_reg_2735_pp0_iter4_reg;
reg   [0:0] tmp_146_reg_2735_pp0_iter5_reg;
reg   [0:0] tmp_146_reg_2735_pp0_iter6_reg;
reg   [0:0] tmp_146_reg_2735_pp0_iter7_reg;
reg   [0:0] tmp_146_reg_2735_pp0_iter8_reg;
reg   [0:0] tmp_146_reg_2735_pp0_iter9_reg;
reg   [0:0] tmp_146_reg_2735_pp0_iter10_reg;
reg   [0:0] tmp_146_reg_2735_pp0_iter11_reg;
reg   [0:0] tmp_146_reg_2735_pp0_iter12_reg;
wire   [30:0] select_ln101_4_fu_416_p3;
reg   [30:0] select_ln101_4_reg_2740;
reg   [30:0] select_ln101_4_reg_2740_pp0_iter3_reg;
reg   [30:0] select_ln101_4_reg_2740_pp0_iter4_reg;
reg   [30:0] select_ln101_4_reg_2740_pp0_iter5_reg;
wire   [30:0] select_ln101_5_fu_423_p3;
reg   [30:0] select_ln101_5_reg_2747;
reg   [27:0] trunc_ln1333_4_reg_2753;
reg   [27:0] trunc_ln1333_5_reg_2758;
reg   [0:0] tmp_147_reg_2763;
wire   [30:0] select_ln101_7_fu_484_p3;
reg   [30:0] select_ln101_7_reg_2769;
reg   [30:0] select_ln101_7_reg_2769_pp0_iter4_reg;
wire   [30:0] select_ln101_8_fu_491_p3;
reg   [30:0] select_ln101_8_reg_2776;
reg   [26:0] trunc_ln1333_6_reg_2782;
reg   [26:0] trunc_ln1333_7_reg_2787;
reg   [0:0] tmp_149_reg_2792;
reg   [0:0] tmp_149_reg_2792_pp0_iter4_reg;
wire   [30:0] sub_ln703_4_fu_537_p2;
reg   [30:0] sub_ln703_4_reg_2798;
wire   [30:0] add_ln203_3_fu_547_p2;
reg   [30:0] add_ln203_3_reg_2803;
wire   [30:0] select_ln101_11_fu_552_p3;
reg   [30:0] select_ln101_11_reg_2808;
reg   [25:0] trunc_ln1333_8_reg_2814;
wire   [30:0] select_ln101_13_fu_652_p3;
reg   [30:0] select_ln101_13_reg_2819;
wire   [30:0] select_ln101_14_fu_660_p3;
reg   [30:0] select_ln101_14_reg_2825;
reg   [24:0] trunc_ln1333_s_reg_2831;
reg   [24:0] trunc_ln1333_10_reg_2836;
reg   [0:0] tmp_153_reg_2841;
reg   [0:0] tmp_154_reg_2847;
reg   [0:0] tmp_154_reg_2847_pp0_iter6_reg;
reg   [0:0] tmp_154_reg_2847_pp0_iter7_reg;
reg   [0:0] tmp_154_reg_2847_pp0_iter8_reg;
reg   [0:0] tmp_154_reg_2847_pp0_iter9_reg;
reg   [0:0] tmp_154_reg_2847_pp0_iter10_reg;
reg   [0:0] tmp_154_reg_2847_pp0_iter11_reg;
reg   [0:0] tmp_154_reg_2847_pp0_iter12_reg;
wire   [26:0] add_ln101_3_fu_704_p2;
reg   [26:0] add_ln101_3_reg_2852;
wire   [30:0] select_ln101_16_fu_751_p3;
reg   [30:0] select_ln101_16_reg_2857;
reg   [30:0] select_ln101_16_reg_2857_pp0_iter7_reg;
wire   [30:0] select_ln101_17_fu_758_p3;
reg   [30:0] select_ln101_17_reg_2864;
reg   [23:0] trunc_ln1333_11_reg_2870;
reg   [23:0] trunc_ln1333_12_reg_2875;
reg   [0:0] tmp_155_reg_2880;
reg   [0:0] tmp_155_reg_2880_pp0_iter7_reg;
wire   [27:0] add_ln101_4_fu_796_p2;
reg   [27:0] add_ln101_4_reg_2886;
reg   [27:0] add_ln101_4_reg_2886_pp0_iter7_reg;
reg   [27:0] add_ln101_4_reg_2886_pp0_iter8_reg;
reg   [27:0] add_ln101_4_reg_2886_pp0_iter9_reg;
reg   [27:0] add_ln101_4_reg_2886_pp0_iter10_reg;
reg   [27:0] add_ln101_4_reg_2886_pp0_iter11_reg;
reg   [27:0] add_ln101_4_reg_2886_pp0_iter12_reg;
reg   [27:0] add_ln101_4_reg_2886_pp0_iter13_reg;
wire   [30:0] sub_ln703_7_fu_813_p2;
reg   [30:0] sub_ln703_7_reg_2891;
wire   [30:0] add_ln203_6_fu_823_p2;
reg   [30:0] add_ln203_6_reg_2896;
wire   [30:0] select_ln101_20_fu_828_p3;
reg   [30:0] select_ln101_20_reg_2901;
reg   [22:0] trunc_ln1333_13_reg_2907;
wire   [30:0] select_ln101_22_fu_928_p3;
reg   [30:0] select_ln101_22_reg_2912;
wire   [30:0] select_ln101_23_fu_936_p3;
reg   [30:0] select_ln101_23_reg_2918;
reg   [21:0] trunc_ln1333_15_reg_2924;
reg   [21:0] trunc_ln1333_16_reg_2929;
reg   [0:0] tmp_159_reg_2934;
reg   [0:0] tmp_160_reg_2940;
reg   [0:0] tmp_160_reg_2940_pp0_iter9_reg;
reg   [0:0] tmp_160_reg_2940_pp0_iter10_reg;
reg   [0:0] tmp_160_reg_2940_pp0_iter11_reg;
reg   [0:0] tmp_160_reg_2940_pp0_iter12_reg;
wire   [23:0] add_ln101_6_fu_980_p2;
reg   [23:0] add_ln101_6_reg_2945;
reg   [23:0] add_ln101_6_reg_2945_pp0_iter9_reg;
reg   [23:0] add_ln101_6_reg_2945_pp0_iter10_reg;
reg   [23:0] add_ln101_6_reg_2945_pp0_iter11_reg;
reg   [23:0] add_ln101_6_reg_2945_pp0_iter12_reg;
wire   [30:0] select_ln101_25_fu_1012_p3;
reg   [30:0] select_ln101_25_reg_2950;
wire   [30:0] select_ln101_26_fu_1019_p3;
reg   [30:0] select_ln101_26_reg_2956;
reg   [20:0] trunc_ln1333_17_reg_2962;
reg   [20:0] trunc_ln1333_18_reg_2967;
reg   [0:0] tmp_161_reg_2972;
reg   [0:0] tmp_162_reg_2978;
reg   [0:0] tmp_162_reg_2978_pp0_iter10_reg;
reg   [0:0] tmp_162_reg_2978_pp0_iter11_reg;
reg   [0:0] tmp_162_reg_2978_pp0_iter12_reg;
wire   [30:0] select_ln101_28_fu_1088_p3;
reg   [30:0] select_ln101_28_reg_2983;
reg   [30:0] select_ln101_28_reg_2983_pp0_iter11_reg;
wire   [30:0] select_ln101_29_fu_1095_p3;
reg   [30:0] select_ln101_29_reg_2990;
reg   [19:0] trunc_ln1333_19_reg_2996;
reg   [19:0] trunc_ln1333_20_reg_3001;
reg   [0:0] tmp_163_reg_3006;
reg   [0:0] tmp_163_reg_3006_pp0_iter11_reg;
wire   [30:0] sub_ln703_11_fu_1141_p2;
reg   [30:0] sub_ln703_11_reg_3012;
wire   [30:0] add_ln203_10_fu_1151_p2;
reg   [30:0] add_ln203_10_reg_3017;
wire   [30:0] select_ln101_32_fu_1156_p3;
reg   [30:0] select_ln101_32_reg_3022;
reg   [18:0] trunc_ln1333_21_reg_3028;
wire   [30:0] select_ln101_34_fu_1256_p3;
reg   [30:0] select_ln101_34_reg_3033;
reg   [30:0] select_ln101_34_reg_3033_pp0_iter13_reg;
reg   [30:0] select_ln101_34_reg_3033_pp0_iter14_reg;
reg   [30:0] select_ln101_34_reg_3033_pp0_iter15_reg;
wire   [30:0] select_ln101_35_fu_1264_p3;
reg   [30:0] select_ln101_35_reg_3040;
reg   [17:0] trunc_ln1333_23_reg_3046;
reg   [17:0] trunc_ln1333_24_reg_3051;
reg   [0:0] tmp_167_reg_3056;
wire   [19:0] add_ln101_9_fu_1300_p2;
reg   [19:0] add_ln101_9_reg_3062;
wire   [30:0] select_ln101_37_fu_1374_p3;
reg   [30:0] select_ln101_37_reg_3067;
reg   [30:0] select_ln101_37_reg_3067_pp0_iter14_reg;
wire   [30:0] select_ln101_38_fu_1381_p3;
reg   [30:0] select_ln101_38_reg_3074;
reg   [16:0] trunc_ln1333_25_reg_3080;
reg   [16:0] trunc_ln1333_26_reg_3085;
reg   [0:0] tmp_169_reg_3090;
reg   [0:0] tmp_169_reg_3090_pp0_iter14_reg;
wire   [29:0] add_ln101_2_fu_1422_p2;
reg   [29:0] add_ln101_2_reg_3096;
wire   [24:0] add_ln101_11_fu_1456_p2;
reg   [24:0] add_ln101_11_reg_3101;
wire   [30:0] sub_ln703_14_fu_1473_p2;
reg   [30:0] sub_ln703_14_reg_3106;
wire   [30:0] add_ln203_13_fu_1483_p2;
reg   [30:0] add_ln203_13_reg_3111;
wire   [30:0] select_ln101_41_fu_1488_p3;
reg   [30:0] select_ln101_41_reg_3116;
reg   [15:0] trunc_ln1333_27_reg_3122;
wire   [29:0] add_ln101_12_fu_1516_p2;
reg   [29:0] add_ln101_12_reg_3127;
reg   [29:0] add_ln101_12_reg_3127_pp0_iter15_reg;
reg   [29:0] add_ln101_12_reg_3127_pp0_iter16_reg;
reg   [29:0] add_ln101_12_reg_3127_pp0_iter17_reg;
reg   [29:0] add_ln101_12_reg_3127_pp0_iter18_reg;
reg   [29:0] add_ln101_12_reg_3127_pp0_iter19_reg;
reg   [29:0] add_ln101_12_reg_3127_pp0_iter20_reg;
reg   [29:0] add_ln101_12_reg_3127_pp0_iter21_reg;
reg   [29:0] add_ln101_12_reg_3127_pp0_iter22_reg;
reg   [29:0] add_ln101_12_reg_3127_pp0_iter23_reg;
reg   [29:0] add_ln101_12_reg_3127_pp0_iter24_reg;
reg   [29:0] add_ln101_12_reg_3127_pp0_iter25_reg;
reg   [29:0] add_ln101_12_reg_3127_pp0_iter26_reg;
reg   [29:0] add_ln101_12_reg_3127_pp0_iter27_reg;
wire   [30:0] select_ln101_43_fu_1605_p3;
reg   [30:0] select_ln101_43_reg_3132;
wire   [30:0] select_ln101_44_fu_1613_p3;
reg   [30:0] select_ln101_44_reg_3138;
reg   [14:0] trunc_ln1333_29_reg_3144;
reg   [14:0] trunc_ln1333_30_reg_3149;
reg   [0:0] tmp_173_reg_3154;
reg   [0:0] tmp_174_reg_3160;
reg   [0:0] tmp_174_reg_3160_pp0_iter16_reg;
reg   [0:0] tmp_174_reg_3160_pp0_iter17_reg;
reg   [0:0] tmp_174_reg_3160_pp0_iter18_reg;
reg   [0:0] tmp_174_reg_3160_pp0_iter19_reg;
reg   [0:0] tmp_174_reg_3160_pp0_iter20_reg;
reg   [0:0] tmp_174_reg_3160_pp0_iter21_reg;
reg   [0:0] tmp_174_reg_3160_pp0_iter22_reg;
reg   [0:0] tmp_174_reg_3160_pp0_iter23_reg;
reg   [0:0] tmp_174_reg_3160_pp0_iter24_reg;
reg   [0:0] tmp_174_reg_3160_pp0_iter25_reg;
reg   [0:0] tmp_174_reg_3160_pp0_iter26_reg;
wire   [16:0] add_ln101_13_fu_1657_p2;
reg   [16:0] add_ln101_13_reg_3165;
wire   [30:0] select_ln101_46_fu_1704_p3;
reg   [30:0] select_ln101_46_reg_3170;
wire   [30:0] select_ln101_47_fu_1711_p3;
reg   [30:0] select_ln101_47_reg_3176;
reg   [13:0] trunc_ln1333_31_reg_3182;
reg   [13:0] trunc_ln1333_32_reg_3187;
reg   [0:0] tmp_175_reg_3192;
reg   [0:0] tmp_176_reg_3198;
reg   [0:0] tmp_176_reg_3198_pp0_iter17_reg;
reg   [0:0] tmp_176_reg_3198_pp0_iter18_reg;
reg   [0:0] tmp_176_reg_3198_pp0_iter19_reg;
reg   [0:0] tmp_176_reg_3198_pp0_iter20_reg;
reg   [0:0] tmp_176_reg_3198_pp0_iter21_reg;
reg   [0:0] tmp_176_reg_3198_pp0_iter22_reg;
reg   [0:0] tmp_176_reg_3198_pp0_iter23_reg;
reg   [0:0] tmp_176_reg_3198_pp0_iter24_reg;
reg   [0:0] tmp_176_reg_3198_pp0_iter25_reg;
reg   [0:0] tmp_176_reg_3198_pp0_iter26_reg;
wire   [17:0] add_ln101_14_fu_1757_p2;
reg   [17:0] add_ln101_14_reg_3203;
reg   [17:0] add_ln101_14_reg_3203_pp0_iter17_reg;
reg   [17:0] add_ln101_14_reg_3203_pp0_iter18_reg;
reg   [17:0] add_ln101_14_reg_3203_pp0_iter19_reg;
reg   [17:0] add_ln101_14_reg_3203_pp0_iter20_reg;
reg   [17:0] add_ln101_14_reg_3203_pp0_iter21_reg;
reg   [17:0] add_ln101_14_reg_3203_pp0_iter22_reg;
reg   [17:0] add_ln101_14_reg_3203_pp0_iter23_reg;
reg   [17:0] add_ln101_14_reg_3203_pp0_iter24_reg;
reg   [17:0] add_ln101_14_reg_3203_pp0_iter25_reg;
reg   [17:0] add_ln101_14_reg_3203_pp0_iter26_reg;
reg   [17:0] add_ln101_14_reg_3203_pp0_iter27_reg;
wire   [30:0] select_ln101_49_fu_1789_p3;
reg   [30:0] select_ln101_49_reg_3208;
reg   [30:0] select_ln101_49_reg_3208_pp0_iter18_reg;
wire   [30:0] select_ln101_50_fu_1796_p3;
reg   [30:0] select_ln101_50_reg_3215;
reg   [12:0] trunc_ln1333_33_reg_3221;
reg   [12:0] trunc_ln1333_34_reg_3226;
reg   [0:0] tmp_177_reg_3231;
reg   [0:0] tmp_177_reg_3231_pp0_iter18_reg;
wire   [30:0] sub_ln703_18_fu_1842_p2;
reg   [30:0] sub_ln703_18_reg_3237;
wire   [30:0] add_ln203_17_fu_1852_p2;
reg   [30:0] add_ln203_17_reg_3242;
wire   [30:0] select_ln101_53_fu_1857_p3;
reg   [30:0] select_ln101_53_reg_3247;
reg   [11:0] trunc_ln1333_35_reg_3253;
wire   [30:0] select_ln101_55_fu_1957_p3;
reg   [30:0] select_ln101_55_reg_3258;
wire   [30:0] select_ln101_56_fu_1965_p3;
reg   [30:0] select_ln101_56_reg_3264;
reg   [10:0] trunc_ln1333_37_reg_3270;
reg   [10:0] trunc_ln1333_38_reg_3275;
reg   [0:0] tmp_181_reg_3280;
reg   [0:0] tmp_182_reg_3286;
reg   [0:0] tmp_182_reg_3286_pp0_iter20_reg;
reg   [0:0] tmp_182_reg_3286_pp0_iter21_reg;
reg   [0:0] tmp_182_reg_3286_pp0_iter22_reg;
reg   [0:0] tmp_182_reg_3286_pp0_iter23_reg;
reg   [0:0] tmp_182_reg_3286_pp0_iter24_reg;
reg   [0:0] tmp_182_reg_3286_pp0_iter25_reg;
reg   [0:0] tmp_182_reg_3286_pp0_iter26_reg;
wire   [12:0] add_ln101_16_fu_2009_p2;
reg   [12:0] add_ln101_16_reg_3291;
reg   [12:0] add_ln101_16_reg_3291_pp0_iter20_reg;
reg   [12:0] add_ln101_16_reg_3291_pp0_iter21_reg;
reg   [12:0] add_ln101_16_reg_3291_pp0_iter22_reg;
reg   [12:0] add_ln101_16_reg_3291_pp0_iter23_reg;
reg   [12:0] add_ln101_16_reg_3291_pp0_iter24_reg;
reg   [12:0] add_ln101_16_reg_3291_pp0_iter25_reg;
reg   [12:0] add_ln101_16_reg_3291_pp0_iter26_reg;
wire   [30:0] select_ln101_58_fu_2041_p3;
reg   [30:0] select_ln101_58_reg_3296;
reg   [30:0] select_ln101_58_reg_3296_pp0_iter21_reg;
wire   [30:0] select_ln101_59_fu_2048_p3;
reg   [30:0] select_ln101_59_reg_3303;
reg   [9:0] trunc_ln1333_39_reg_3309;
reg   [9:0] trunc_ln1333_40_reg_3314;
reg   [0:0] tmp_183_reg_3319;
reg   [0:0] tmp_183_reg_3319_pp0_iter21_reg;
wire   [30:0] sub_ln703_21_fu_2094_p2;
reg   [30:0] sub_ln703_21_reg_3325;
wire   [30:0] add_ln203_20_fu_2104_p2;
reg   [30:0] add_ln203_20_reg_3330;
wire   [30:0] select_ln101_62_fu_2109_p3;
reg   [30:0] select_ln101_62_reg_3335;
reg   [8:0] trunc_ln1333_41_reg_3341;
wire   [30:0] select_ln101_64_fu_2209_p3;
reg   [30:0] select_ln101_64_reg_3346;
wire   [30:0] select_ln101_65_fu_2217_p3;
reg   [30:0] select_ln101_65_reg_3352;
reg   [7:0] trunc_ln1333_43_reg_3358;
reg   [7:0] trunc_ln1333_44_reg_3363;
reg   [0:0] tmp_187_reg_3368;
reg   [0:0] tmp_188_reg_3374;
reg   [0:0] tmp_188_reg_3374_pp0_iter23_reg;
reg   [0:0] tmp_188_reg_3374_pp0_iter24_reg;
reg   [0:0] tmp_188_reg_3374_pp0_iter25_reg;
wire   [9:0] add_ln101_19_fu_2261_p2;
reg   [9:0] add_ln101_19_reg_3379;
reg   [9:0] add_ln101_19_reg_3379_pp0_iter23_reg;
reg   [9:0] add_ln101_19_reg_3379_pp0_iter24_reg;
reg   [9:0] add_ln101_19_reg_3379_pp0_iter25_reg;
reg   [9:0] add_ln101_19_reg_3379_pp0_iter26_reg;
wire   [30:0] select_ln101_67_fu_2293_p3;
reg   [30:0] select_ln101_67_reg_3384;
wire   [30:0] select_ln101_68_fu_2300_p3;
reg   [30:0] select_ln101_68_reg_3390;
reg   [6:0] trunc_ln1333_45_reg_3396;
reg   [6:0] trunc_ln1333_46_reg_3401;
reg   [0:0] tmp_189_reg_3406;
reg   [0:0] tmp_190_reg_3412;
reg   [0:0] tmp_190_reg_3412_pp0_iter24_reg;
reg   [0:0] tmp_190_reg_3412_pp0_iter25_reg;
reg   [0:0] tmp_190_reg_3412_pp0_iter26_reg;
wire   [30:0] select_ln101_70_fu_2369_p3;
reg   [30:0] select_ln101_70_reg_3417;
reg   [30:0] select_ln101_70_reg_3417_pp0_iter25_reg;
wire   [30:0] select_ln101_71_fu_2376_p3;
reg   [30:0] select_ln101_71_reg_3424;
reg   [5:0] trunc_ln1333_47_reg_3430;
reg   [5:0] trunc_ln1333_48_reg_3435;
reg   [0:0] tmp_191_reg_3440;
reg   [0:0] tmp_191_reg_3440_pp0_iter25_reg;
wire   [30:0] sub_ln703_25_fu_2422_p2;
reg   [30:0] sub_ln703_25_reg_3446;
wire   [30:0] add_ln203_24_fu_2432_p2;
reg   [30:0] add_ln203_24_reg_3451;
wire   [4:0] select_ln101_74_fu_2457_p3;
reg   [4:0] select_ln101_74_reg_3456;
wire   [7:0] select_ln101_66_fu_2464_p3;
reg   [7:0] select_ln101_66_reg_3461;
wire   [5:0] add_ln101_22_fu_2554_p2;
reg   [5:0] add_ln101_22_reg_3466;
wire   [29:0] select_ln101_80_cast_fu_2560_p3;
reg   [29:0] select_ln101_80_cast_reg_3471;
reg   [29:0] select_ln101_80_cast_reg_3471_pp0_iter27_reg;
wire   [14:0] add_ln101_17_fu_2605_p2;
reg   [14:0] add_ln101_17_reg_3476;
wire   [10:0] add_ln101_24_fu_2638_p2;
reg   [10:0] add_ln101_24_reg_3481;
wire  signed [29:0] y_V_read_cast1_fu_218_p0;
wire    ap_block_pp0_stage0;
wire  signed [29:0] tmp_141_fu_226_p1;
wire  signed [30:0] y_V_read_cast1_fu_218_p1;
wire  signed [30:0] x_V_read_cast_fu_222_p1;
wire  signed [29:0] tmp_142_fu_252_p1;
wire   [30:0] select_ln101_1_fu_265_p3;
wire   [29:0] trunc_ln_fu_270_p4;
wire   [30:0] select_ln101_fu_260_p3;
wire   [29:0] trunc_ln1333_1_fu_284_p4;
wire  signed [30:0] sext_ln1333_1_fu_294_p1;
wire  signed [30:0] sext_ln1333_fu_280_p1;
wire   [0:0] tmp_143_fu_298_p3;
wire   [30:0] add_ln203_fu_324_p2;
wire   [30:0] sub_ln703_1_fu_312_p2;
wire   [30:0] sub_ln203_1_fu_318_p2;
wire   [30:0] add_ln703_1_fu_306_p2;
wire  signed [30:0] sext_ln1371_1_fu_393_p1;
wire  signed [30:0] sext_ln1371_fu_390_p1;
wire   [30:0] add_ln203_1_fu_411_p2;
wire   [30:0] sub_ln703_2_fu_401_p2;
wire   [30:0] sub_ln203_2_fu_406_p2;
wire   [30:0] add_ln703_2_fu_396_p2;
wire  signed [30:0] sext_ln1371_3_fu_461_p1;
wire  signed [30:0] sext_ln1371_2_fu_458_p1;
wire   [30:0] add_ln203_2_fu_479_p2;
wire   [30:0] sub_ln703_3_fu_469_p2;
wire   [30:0] sub_ln203_3_fu_474_p2;
wire   [30:0] add_ln703_26_fu_464_p2;
wire  signed [30:0] sext_ln1371_5_fu_529_p1;
wire  signed [30:0] sext_ln1371_4_fu_526_p1;
wire   [30:0] sub_ln203_4_fu_542_p2;
wire   [30:0] add_ln703_4_fu_532_p2;
wire   [0:0] tmp_150_fu_569_p3;
wire   [30:0] select_ln101_10_fu_584_p3;
wire   [25:0] trunc_ln1333_9_fu_592_p4;
wire  signed [30:0] sext_ln1371_7_fu_602_p1;
wire  signed [30:0] sext_ln1371_6_fu_589_p1;
wire   [0:0] tmp_152_fu_636_p3;
wire   [0:0] tmp_151_fu_606_p3;
wire   [30:0] add_ln203_4_fu_630_p2;
wire   [30:0] sub_ln703_5_fu_619_p2;
wire   [30:0] sub_ln203_5_fu_625_p2;
wire   [30:0] add_ln703_5_fu_614_p2;
wire   [26:0] select_ln101_12_fu_644_p3;
wire   [26:0] select_ln101_9_fu_576_p3;
wire   [0:0] tmp_148_fu_710_p3;
wire  signed [30:0] sext_ln1371_9_fu_728_p1;
wire  signed [30:0] sext_ln1371_8_fu_725_p1;
wire   [30:0] add_ln203_5_fu_746_p2;
wire   [30:0] sub_ln703_6_fu_736_p2;
wire   [30:0] sub_ln203_6_fu_741_p2;
wire   [30:0] add_ln703_6_fu_731_p2;
wire   [27:0] select_ln101_6_fu_717_p3;
wire  signed [27:0] sext_ln101_fu_793_p1;
wire  signed [30:0] sext_ln1371_11_fu_805_p1;
wire  signed [30:0] sext_ln1371_10_fu_802_p1;
wire   [30:0] sub_ln203_7_fu_818_p2;
wire   [30:0] add_ln703_7_fu_808_p2;
wire   [0:0] tmp_156_fu_845_p3;
wire   [30:0] select_ln101_19_fu_860_p3;
wire   [22:0] trunc_ln1333_14_fu_868_p4;
wire  signed [30:0] sext_ln1371_13_fu_878_p1;
wire  signed [30:0] sext_ln1371_12_fu_865_p1;
wire   [0:0] tmp_158_fu_912_p3;
wire   [0:0] tmp_157_fu_882_p3;
wire   [30:0] add_ln203_7_fu_906_p2;
wire   [30:0] sub_ln703_8_fu_895_p2;
wire   [30:0] sub_ln203_8_fu_901_p2;
wire   [30:0] add_ln703_8_fu_890_p2;
wire   [23:0] select_ln101_21_fu_920_p3;
wire   [23:0] select_ln101_18_fu_852_p3;
wire  signed [30:0] sext_ln1371_15_fu_989_p1;
wire  signed [30:0] sext_ln1371_14_fu_986_p1;
wire   [30:0] add_ln203_8_fu_1007_p2;
wire   [30:0] sub_ln703_9_fu_997_p2;
wire   [30:0] sub_ln203_9_fu_1002_p2;
wire   [30:0] add_ln703_9_fu_992_p2;
wire  signed [30:0] sext_ln1371_17_fu_1065_p1;
wire  signed [30:0] sext_ln1371_16_fu_1062_p1;
wire   [30:0] add_ln203_9_fu_1083_p2;
wire   [30:0] sub_ln703_10_fu_1073_p2;
wire   [30:0] sub_ln203_10_fu_1078_p2;
wire   [30:0] add_ln703_10_fu_1068_p2;
wire  signed [30:0] sext_ln1371_19_fu_1133_p1;
wire  signed [30:0] sext_ln1371_18_fu_1130_p1;
wire   [30:0] sub_ln203_11_fu_1146_p2;
wire   [30:0] add_ln703_11_fu_1136_p2;
wire   [0:0] tmp_164_fu_1173_p3;
wire   [30:0] select_ln101_31_fu_1188_p3;
wire   [18:0] trunc_ln1333_22_fu_1196_p4;
wire  signed [30:0] sext_ln1371_21_fu_1206_p1;
wire  signed [30:0] sext_ln1371_20_fu_1193_p1;
wire   [0:0] tmp_166_fu_1240_p3;
wire   [0:0] tmp_165_fu_1210_p3;
wire   [30:0] add_ln203_11_fu_1234_p2;
wire   [30:0] sub_ln703_12_fu_1223_p2;
wire   [30:0] sub_ln203_12_fu_1229_p2;
wire   [30:0] add_ln703_12_fu_1218_p2;
wire   [19:0] select_ln101_33_fu_1248_p3;
wire   [19:0] select_ln101_30_fu_1180_p3;
wire  signed [30:0] sext_ln1371_23_fu_1351_p1;
wire  signed [30:0] sext_ln1371_22_fu_1348_p1;
wire   [30:0] add_ln203_12_fu_1369_p2;
wire   [30:0] sub_ln703_13_fu_1359_p2;
wire   [30:0] sub_ln203_13_fu_1364_p2;
wire   [30:0] add_ln703_13_fu_1354_p2;
wire   [29:0] select_ln101_6_cast_fu_1320_p3;
wire   [29:0] select_ln101_cast_fu_1306_p3;
wire   [29:0] select_ln101_3_cast_fu_1313_p3;
wire   [29:0] add_ln101_1_fu_1416_p2;
wire   [24:0] select_ln101_15_fu_1327_p3;
wire  signed [24:0] sext_ln101_2_fu_1428_p1;
wire   [21:0] select_ln101_27_fu_1341_p3;
wire   [21:0] select_ln101_24_fu_1334_p3;
wire   [21:0] add_ln101_8_fu_1437_p2;
wire  signed [21:0] sext_ln101_3_fu_1443_p1;
wire   [21:0] add_ln101_10_fu_1446_p2;
wire   [24:0] add_ln101_7_fu_1431_p2;
wire  signed [24:0] sext_ln101_4_fu_1452_p1;
wire  signed [30:0] sext_ln1371_25_fu_1465_p1;
wire  signed [30:0] sext_ln1371_24_fu_1462_p1;
wire   [30:0] sub_ln203_14_fu_1478_p2;
wire   [30:0] add_ln703_14_fu_1468_p2;
wire  signed [29:0] sext_ln101_1_fu_1505_p1;
wire   [29:0] add_ln101_5_fu_1508_p2;
wire  signed [29:0] sext_ln101_5_fu_1513_p1;
wire   [0:0] tmp_170_fu_1522_p3;
wire   [30:0] select_ln101_40_fu_1537_p3;
wire   [15:0] trunc_ln1333_28_fu_1545_p4;
wire  signed [30:0] sext_ln1371_27_fu_1555_p1;
wire  signed [30:0] sext_ln1371_26_fu_1542_p1;
wire   [0:0] tmp_172_fu_1589_p3;
wire   [0:0] tmp_171_fu_1559_p3;
wire   [30:0] add_ln203_14_fu_1583_p2;
wire   [30:0] sub_ln703_15_fu_1572_p2;
wire   [30:0] sub_ln203_15_fu_1578_p2;
wire   [30:0] add_ln703_15_fu_1567_p2;
wire   [16:0] select_ln101_42_fu_1597_p3;
wire   [16:0] select_ln101_39_fu_1529_p3;
wire   [0:0] tmp_168_fu_1663_p3;
wire  signed [30:0] sext_ln1371_29_fu_1681_p1;
wire  signed [30:0] sext_ln1371_28_fu_1678_p1;
wire   [30:0] add_ln203_15_fu_1699_p2;
wire   [30:0] sub_ln703_16_fu_1689_p2;
wire   [30:0] sub_ln203_16_fu_1694_p2;
wire   [30:0] add_ln703_16_fu_1684_p2;
wire   [17:0] select_ln101_36_fu_1670_p3;
wire  signed [17:0] sext_ln101_6_fu_1754_p1;
wire  signed [30:0] sext_ln1371_31_fu_1766_p1;
wire  signed [30:0] sext_ln1371_30_fu_1763_p1;
wire   [30:0] add_ln203_16_fu_1784_p2;
wire   [30:0] sub_ln703_17_fu_1774_p2;
wire   [30:0] sub_ln203_17_fu_1779_p2;
wire   [30:0] add_ln703_17_fu_1769_p2;
wire  signed [30:0] sext_ln1371_33_fu_1834_p1;
wire  signed [30:0] sext_ln1371_32_fu_1831_p1;
wire   [30:0] sub_ln203_18_fu_1847_p2;
wire   [30:0] add_ln703_18_fu_1837_p2;
wire   [0:0] tmp_178_fu_1874_p3;
wire   [30:0] select_ln101_52_fu_1889_p3;
wire   [11:0] trunc_ln1333_36_fu_1897_p4;
wire  signed [30:0] sext_ln1371_35_fu_1907_p1;
wire  signed [30:0] sext_ln1371_34_fu_1894_p1;
wire   [0:0] tmp_180_fu_1941_p3;
wire   [0:0] tmp_179_fu_1911_p3;
wire   [30:0] add_ln203_18_fu_1935_p2;
wire   [30:0] sub_ln703_19_fu_1924_p2;
wire   [30:0] sub_ln203_19_fu_1930_p2;
wire   [30:0] add_ln703_19_fu_1919_p2;
wire   [12:0] select_ln101_54_fu_1949_p3;
wire   [12:0] select_ln101_51_fu_1881_p3;
wire  signed [30:0] sext_ln1371_37_fu_2018_p1;
wire  signed [30:0] sext_ln1371_36_fu_2015_p1;
wire   [30:0] add_ln203_19_fu_2036_p2;
wire   [30:0] sub_ln703_20_fu_2026_p2;
wire   [30:0] sub_ln203_20_fu_2031_p2;
wire   [30:0] add_ln703_20_fu_2021_p2;
wire  signed [30:0] sext_ln1371_39_fu_2086_p1;
wire  signed [30:0] sext_ln1371_38_fu_2083_p1;
wire   [30:0] sub_ln203_21_fu_2099_p2;
wire   [30:0] add_ln703_21_fu_2089_p2;
wire   [0:0] tmp_184_fu_2126_p3;
wire   [30:0] select_ln101_61_fu_2141_p3;
wire   [8:0] trunc_ln1333_42_fu_2149_p4;
wire  signed [30:0] sext_ln1371_41_fu_2159_p1;
wire  signed [30:0] sext_ln1371_40_fu_2146_p1;
wire   [0:0] tmp_186_fu_2193_p3;
wire   [0:0] tmp_185_fu_2163_p3;
wire   [30:0] add_ln203_21_fu_2187_p2;
wire   [30:0] sub_ln703_22_fu_2176_p2;
wire   [30:0] sub_ln203_22_fu_2182_p2;
wire   [30:0] add_ln703_22_fu_2171_p2;
wire   [9:0] select_ln101_63_fu_2201_p3;
wire   [9:0] select_ln101_60_fu_2133_p3;
wire  signed [30:0] sext_ln1371_43_fu_2270_p1;
wire  signed [30:0] sext_ln1371_42_fu_2267_p1;
wire   [30:0] add_ln203_22_fu_2288_p2;
wire   [30:0] sub_ln703_23_fu_2278_p2;
wire   [30:0] sub_ln203_23_fu_2283_p2;
wire   [30:0] add_ln703_23_fu_2273_p2;
wire  signed [30:0] sext_ln1371_45_fu_2346_p1;
wire  signed [30:0] sext_ln1371_44_fu_2343_p1;
wire   [30:0] add_ln203_23_fu_2364_p2;
wire   [30:0] sub_ln703_24_fu_2354_p2;
wire   [30:0] sub_ln203_24_fu_2359_p2;
wire   [30:0] add_ln703_24_fu_2349_p2;
wire  signed [30:0] sext_ln1371_47_fu_2414_p1;
wire  signed [30:0] sext_ln1371_46_fu_2411_p1;
wire   [30:0] add_ln703_25_fu_2417_p2;
wire   [30:0] sub_ln203_25_fu_2427_p2;
wire   [4:0] tmp_s_fu_2447_p4;
wire   [4:0] tmp_fu_2437_p4;
wire   [0:0] tmp_192_fu_2471_p3;
wire   [30:0] select_ln101_73_fu_2486_p3;
wire  signed [30:0] sext_ln1371_48_fu_2491_p1;
wire   [0:0] tmp_194_fu_2514_p3;
wire   [30:0] sub_ln703_26_fu_2502_p2;
wire   [30:0] add_ln203_25_fu_2508_p2;
wire   [0:0] tmp_193_fu_2494_p3;
wire   [0:0] tmp_196_fu_2538_p3;
wire   [0:0] tmp_195_fu_2530_p3;
wire   [5:0] select_ln101_75_fu_2522_p3;
wire   [5:0] select_ln101_72_fu_2478_p3;
wire   [0:0] select_ln101_76_fu_2546_p3;
wire   [14:0] select_ln101_48_fu_2575_p3;
wire   [14:0] select_ln101_45_fu_2568_p3;
wire   [14:0] add_ln101_15_fu_2596_p2;
wire  signed [14:0] sext_ln101_7_fu_2602_p1;
wire   [10:0] select_ln101_57_fu_2582_p3;
wire  signed [10:0] sext_ln101_9_fu_2611_p1;
wire   [7:0] select_ln101_69_fu_2589_p3;
wire   [7:0] add_ln101_21_fu_2620_p2;
wire  signed [7:0] sext_ln101_10_fu_2625_p1;
wire   [7:0] add_ln101_23_fu_2628_p2;
wire   [10:0] add_ln101_20_fu_2614_p2;
wire  signed [10:0] sext_ln101_11_fu_2634_p1;
wire  signed [17:0] sext_ln101_8_fu_2644_p1;
wire   [17:0] add_ln101_18_fu_2647_p2;
wire  signed [17:0] sext_ln101_12_fu_2652_p1;
wire   [17:0] add_ln101_25_fu_2655_p2;
wire  signed [29:0] sext_ln101_13_fu_2661_p1;
wire   [29:0] add_ln101_26_fu_2665_p2;
reg   [29:0] x_V_read_int_reg;
reg   [29:0] y_V_read_int_reg;

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        add_ln101_11_reg_3101[24 : 1] <= add_ln101_11_fu_1456_p2[24 : 1];
        add_ln101_12_reg_3127[29 : 1] <= add_ln101_12_fu_1516_p2[29 : 1];
        add_ln101_12_reg_3127_pp0_iter15_reg[29 : 1] <= add_ln101_12_reg_3127[29 : 1];
        add_ln101_12_reg_3127_pp0_iter16_reg[29 : 1] <= add_ln101_12_reg_3127_pp0_iter15_reg[29 : 1];
        add_ln101_12_reg_3127_pp0_iter17_reg[29 : 1] <= add_ln101_12_reg_3127_pp0_iter16_reg[29 : 1];
        add_ln101_12_reg_3127_pp0_iter18_reg[29 : 1] <= add_ln101_12_reg_3127_pp0_iter17_reg[29 : 1];
        add_ln101_12_reg_3127_pp0_iter19_reg[29 : 1] <= add_ln101_12_reg_3127_pp0_iter18_reg[29 : 1];
        add_ln101_12_reg_3127_pp0_iter20_reg[29 : 1] <= add_ln101_12_reg_3127_pp0_iter19_reg[29 : 1];
        add_ln101_12_reg_3127_pp0_iter21_reg[29 : 1] <= add_ln101_12_reg_3127_pp0_iter20_reg[29 : 1];
        add_ln101_12_reg_3127_pp0_iter22_reg[29 : 1] <= add_ln101_12_reg_3127_pp0_iter21_reg[29 : 1];
        add_ln101_12_reg_3127_pp0_iter23_reg[29 : 1] <= add_ln101_12_reg_3127_pp0_iter22_reg[29 : 1];
        add_ln101_12_reg_3127_pp0_iter24_reg[29 : 1] <= add_ln101_12_reg_3127_pp0_iter23_reg[29 : 1];
        add_ln101_12_reg_3127_pp0_iter25_reg[29 : 1] <= add_ln101_12_reg_3127_pp0_iter24_reg[29 : 1];
        add_ln101_12_reg_3127_pp0_iter26_reg[29 : 1] <= add_ln101_12_reg_3127_pp0_iter25_reg[29 : 1];
        add_ln101_12_reg_3127_pp0_iter27_reg[29 : 1] <= add_ln101_12_reg_3127_pp0_iter26_reg[29 : 1];
        add_ln101_13_reg_3165[16 : 1] <= add_ln101_13_fu_1657_p2[16 : 1];
        add_ln101_14_reg_3203[17 : 1] <= add_ln101_14_fu_1757_p2[17 : 1];
        add_ln101_14_reg_3203_pp0_iter17_reg[17 : 1] <= add_ln101_14_reg_3203[17 : 1];
        add_ln101_14_reg_3203_pp0_iter18_reg[17 : 1] <= add_ln101_14_reg_3203_pp0_iter17_reg[17 : 1];
        add_ln101_14_reg_3203_pp0_iter19_reg[17 : 1] <= add_ln101_14_reg_3203_pp0_iter18_reg[17 : 1];
        add_ln101_14_reg_3203_pp0_iter20_reg[17 : 1] <= add_ln101_14_reg_3203_pp0_iter19_reg[17 : 1];
        add_ln101_14_reg_3203_pp0_iter21_reg[17 : 1] <= add_ln101_14_reg_3203_pp0_iter20_reg[17 : 1];
        add_ln101_14_reg_3203_pp0_iter22_reg[17 : 1] <= add_ln101_14_reg_3203_pp0_iter21_reg[17 : 1];
        add_ln101_14_reg_3203_pp0_iter23_reg[17 : 1] <= add_ln101_14_reg_3203_pp0_iter22_reg[17 : 1];
        add_ln101_14_reg_3203_pp0_iter24_reg[17 : 1] <= add_ln101_14_reg_3203_pp0_iter23_reg[17 : 1];
        add_ln101_14_reg_3203_pp0_iter25_reg[17 : 1] <= add_ln101_14_reg_3203_pp0_iter24_reg[17 : 1];
        add_ln101_14_reg_3203_pp0_iter26_reg[17 : 1] <= add_ln101_14_reg_3203_pp0_iter25_reg[17 : 1];
        add_ln101_14_reg_3203_pp0_iter27_reg[17 : 1] <= add_ln101_14_reg_3203_pp0_iter26_reg[17 : 1];
        add_ln101_16_reg_3291[12 : 1] <= add_ln101_16_fu_2009_p2[12 : 1];
        add_ln101_16_reg_3291_pp0_iter20_reg[12 : 1] <= add_ln101_16_reg_3291[12 : 1];
        add_ln101_16_reg_3291_pp0_iter21_reg[12 : 1] <= add_ln101_16_reg_3291_pp0_iter20_reg[12 : 1];
        add_ln101_16_reg_3291_pp0_iter22_reg[12 : 1] <= add_ln101_16_reg_3291_pp0_iter21_reg[12 : 1];
        add_ln101_16_reg_3291_pp0_iter23_reg[12 : 1] <= add_ln101_16_reg_3291_pp0_iter22_reg[12 : 1];
        add_ln101_16_reg_3291_pp0_iter24_reg[12 : 1] <= add_ln101_16_reg_3291_pp0_iter23_reg[12 : 1];
        add_ln101_16_reg_3291_pp0_iter25_reg[12 : 1] <= add_ln101_16_reg_3291_pp0_iter24_reg[12 : 1];
        add_ln101_16_reg_3291_pp0_iter26_reg[12 : 1] <= add_ln101_16_reg_3291_pp0_iter25_reg[12 : 1];
        add_ln101_17_reg_3476[14 : 1] <= add_ln101_17_fu_2605_p2[14 : 1];
        add_ln101_19_reg_3379[9 : 1] <= add_ln101_19_fu_2261_p2[9 : 1];
        add_ln101_19_reg_3379_pp0_iter23_reg[9 : 1] <= add_ln101_19_reg_3379[9 : 1];
        add_ln101_19_reg_3379_pp0_iter24_reg[9 : 1] <= add_ln101_19_reg_3379_pp0_iter23_reg[9 : 1];
        add_ln101_19_reg_3379_pp0_iter25_reg[9 : 1] <= add_ln101_19_reg_3379_pp0_iter24_reg[9 : 1];
        add_ln101_19_reg_3379_pp0_iter26_reg[9 : 1] <= add_ln101_19_reg_3379_pp0_iter25_reg[9 : 1];
        add_ln101_22_reg_3466[5 : 1] <= add_ln101_22_fu_2554_p2[5 : 1];
        add_ln101_24_reg_3481[10 : 1] <= add_ln101_24_fu_2638_p2[10 : 1];
        add_ln101_2_reg_3096[29 : 1] <= add_ln101_2_fu_1422_p2[29 : 1];
        add_ln101_3_reg_2852[26 : 1] <= add_ln101_3_fu_704_p2[26 : 1];
        add_ln101_4_reg_2886[27 : 1] <= add_ln101_4_fu_796_p2[27 : 1];
        add_ln101_4_reg_2886_pp0_iter10_reg[27 : 1] <= add_ln101_4_reg_2886_pp0_iter9_reg[27 : 1];
        add_ln101_4_reg_2886_pp0_iter11_reg[27 : 1] <= add_ln101_4_reg_2886_pp0_iter10_reg[27 : 1];
        add_ln101_4_reg_2886_pp0_iter12_reg[27 : 1] <= add_ln101_4_reg_2886_pp0_iter11_reg[27 : 1];
        add_ln101_4_reg_2886_pp0_iter13_reg[27 : 1] <= add_ln101_4_reg_2886_pp0_iter12_reg[27 : 1];
        add_ln101_4_reg_2886_pp0_iter7_reg[27 : 1] <= add_ln101_4_reg_2886[27 : 1];
        add_ln101_4_reg_2886_pp0_iter8_reg[27 : 1] <= add_ln101_4_reg_2886_pp0_iter7_reg[27 : 1];
        add_ln101_4_reg_2886_pp0_iter9_reg[27 : 1] <= add_ln101_4_reg_2886_pp0_iter8_reg[27 : 1];
        add_ln101_6_reg_2945[23 : 1] <= add_ln101_6_fu_980_p2[23 : 1];
        add_ln101_6_reg_2945_pp0_iter10_reg[23 : 1] <= add_ln101_6_reg_2945_pp0_iter9_reg[23 : 1];
        add_ln101_6_reg_2945_pp0_iter11_reg[23 : 1] <= add_ln101_6_reg_2945_pp0_iter10_reg[23 : 1];
        add_ln101_6_reg_2945_pp0_iter12_reg[23 : 1] <= add_ln101_6_reg_2945_pp0_iter11_reg[23 : 1];
        add_ln101_6_reg_2945_pp0_iter9_reg[23 : 1] <= add_ln101_6_reg_2945[23 : 1];
        add_ln101_9_reg_3062[19 : 1] <= add_ln101_9_fu_1300_p2[19 : 1];
        add_ln703_reg_2681 <= add_ln703_fu_234_p2;
        select_ln101_11_reg_2808 <= select_ln101_11_fu_552_p3;
        select_ln101_13_reg_2819 <= select_ln101_13_fu_652_p3;
        select_ln101_14_reg_2825 <= select_ln101_14_fu_660_p3;
        select_ln101_16_reg_2857 <= select_ln101_16_fu_751_p3;
        select_ln101_16_reg_2857_pp0_iter7_reg <= select_ln101_16_reg_2857;
        select_ln101_17_reg_2864 <= select_ln101_17_fu_758_p3;
        select_ln101_20_reg_2901 <= select_ln101_20_fu_828_p3;
        select_ln101_22_reg_2912 <= select_ln101_22_fu_928_p3;
        select_ln101_23_reg_2918 <= select_ln101_23_fu_936_p3;
        select_ln101_25_reg_2950 <= select_ln101_25_fu_1012_p3;
        select_ln101_26_reg_2956 <= select_ln101_26_fu_1019_p3;
        select_ln101_28_reg_2983 <= select_ln101_28_fu_1088_p3;
        select_ln101_28_reg_2983_pp0_iter11_reg <= select_ln101_28_reg_2983;
        select_ln101_29_reg_2990 <= select_ln101_29_fu_1095_p3;
        select_ln101_2_reg_2707 <= select_ln101_2_fu_338_p3;
        select_ln101_32_reg_3022 <= select_ln101_32_fu_1156_p3;
        select_ln101_34_reg_3033 <= select_ln101_34_fu_1256_p3;
        select_ln101_34_reg_3033_pp0_iter13_reg <= select_ln101_34_reg_3033;
        select_ln101_34_reg_3033_pp0_iter14_reg <= select_ln101_34_reg_3033_pp0_iter13_reg;
        select_ln101_34_reg_3033_pp0_iter15_reg <= select_ln101_34_reg_3033_pp0_iter14_reg;
        select_ln101_35_reg_3040 <= select_ln101_35_fu_1264_p3;
        select_ln101_37_reg_3067 <= select_ln101_37_fu_1374_p3;
        select_ln101_37_reg_3067_pp0_iter14_reg <= select_ln101_37_reg_3067;
        select_ln101_38_reg_3074 <= select_ln101_38_fu_1381_p3;
        select_ln101_3_reg_2713 <= select_ln101_3_fu_346_p3;
        select_ln101_41_reg_3116 <= select_ln101_41_fu_1488_p3;
        select_ln101_43_reg_3132 <= select_ln101_43_fu_1605_p3;
        select_ln101_44_reg_3138 <= select_ln101_44_fu_1613_p3;
        select_ln101_46_reg_3170 <= select_ln101_46_fu_1704_p3;
        select_ln101_47_reg_3176 <= select_ln101_47_fu_1711_p3;
        select_ln101_49_reg_3208 <= select_ln101_49_fu_1789_p3;
        select_ln101_49_reg_3208_pp0_iter18_reg <= select_ln101_49_reg_3208;
        select_ln101_4_reg_2740 <= select_ln101_4_fu_416_p3;
        select_ln101_4_reg_2740_pp0_iter3_reg <= select_ln101_4_reg_2740;
        select_ln101_4_reg_2740_pp0_iter4_reg <= select_ln101_4_reg_2740_pp0_iter3_reg;
        select_ln101_4_reg_2740_pp0_iter5_reg <= select_ln101_4_reg_2740_pp0_iter4_reg;
        select_ln101_50_reg_3215 <= select_ln101_50_fu_1796_p3;
        select_ln101_53_reg_3247 <= select_ln101_53_fu_1857_p3;
        select_ln101_55_reg_3258 <= select_ln101_55_fu_1957_p3;
        select_ln101_56_reg_3264 <= select_ln101_56_fu_1965_p3;
        select_ln101_58_reg_3296 <= select_ln101_58_fu_2041_p3;
        select_ln101_58_reg_3296_pp0_iter21_reg <= select_ln101_58_reg_3296;
        select_ln101_59_reg_3303 <= select_ln101_59_fu_2048_p3;
        select_ln101_5_reg_2747 <= select_ln101_5_fu_423_p3;
        select_ln101_62_reg_3335 <= select_ln101_62_fu_2109_p3;
        select_ln101_64_reg_3346 <= select_ln101_64_fu_2209_p3;
        select_ln101_65_reg_3352 <= select_ln101_65_fu_2217_p3;
        select_ln101_66_reg_3461[1] <= select_ln101_66_fu_2464_p3[1];
select_ln101_66_reg_3461[7 : 6] <= select_ln101_66_fu_2464_p3[7 : 6];
        select_ln101_67_reg_3384 <= select_ln101_67_fu_2293_p3;
        select_ln101_68_reg_3390 <= select_ln101_68_fu_2300_p3;
        select_ln101_70_reg_3417 <= select_ln101_70_fu_2369_p3;
        select_ln101_70_reg_3417_pp0_iter25_reg <= select_ln101_70_reg_3417;
        select_ln101_71_reg_3424 <= select_ln101_71_fu_2376_p3;
        select_ln101_74_reg_3456 <= select_ln101_74_fu_2457_p3;
        select_ln101_7_reg_2769 <= select_ln101_7_fu_484_p3;
        select_ln101_7_reg_2769_pp0_iter4_reg <= select_ln101_7_reg_2769;
        select_ln101_80_cast_reg_3471[1] <= select_ln101_80_cast_fu_2560_p3[1];
        select_ln101_80_cast_reg_3471_pp0_iter27_reg[1] <= select_ln101_80_cast_reg_3471[1];
        select_ln101_8_reg_2776 <= select_ln101_8_fu_491_p3;
        sub_ln203_reg_2692 <= sub_ln203_fu_246_p2;
        sub_ln703_reg_2687 <= sub_ln703_fu_240_p2;
        tmp_141_reg_2675 <= tmp_141_fu_226_p1[32'd29];
        tmp_142_reg_2697 <= tmp_142_fu_252_p1[32'd29];
        tmp_142_reg_2697_pp0_iter10_reg <= tmp_142_reg_2697_pp0_iter9_reg;
        tmp_142_reg_2697_pp0_iter11_reg <= tmp_142_reg_2697_pp0_iter10_reg;
        tmp_142_reg_2697_pp0_iter12_reg <= tmp_142_reg_2697_pp0_iter11_reg;
        tmp_142_reg_2697_pp0_iter1_reg <= tmp_142_reg_2697;
        tmp_142_reg_2697_pp0_iter2_reg <= tmp_142_reg_2697_pp0_iter1_reg;
        tmp_142_reg_2697_pp0_iter3_reg <= tmp_142_reg_2697_pp0_iter2_reg;
        tmp_142_reg_2697_pp0_iter4_reg <= tmp_142_reg_2697_pp0_iter3_reg;
        tmp_142_reg_2697_pp0_iter5_reg <= tmp_142_reg_2697_pp0_iter4_reg;
        tmp_142_reg_2697_pp0_iter6_reg <= tmp_142_reg_2697_pp0_iter5_reg;
        tmp_142_reg_2697_pp0_iter7_reg <= tmp_142_reg_2697_pp0_iter6_reg;
        tmp_142_reg_2697_pp0_iter8_reg <= tmp_142_reg_2697_pp0_iter7_reg;
        tmp_142_reg_2697_pp0_iter9_reg <= tmp_142_reg_2697_pp0_iter8_reg;
        tmp_144_reg_2702 <= select_ln101_fu_260_p3[32'd30];
        tmp_144_reg_2702_pp0_iter10_reg <= tmp_144_reg_2702_pp0_iter9_reg;
        tmp_144_reg_2702_pp0_iter11_reg <= tmp_144_reg_2702_pp0_iter10_reg;
        tmp_144_reg_2702_pp0_iter12_reg <= tmp_144_reg_2702_pp0_iter11_reg;
        tmp_144_reg_2702_pp0_iter2_reg <= tmp_144_reg_2702;
        tmp_144_reg_2702_pp0_iter3_reg <= tmp_144_reg_2702_pp0_iter2_reg;
        tmp_144_reg_2702_pp0_iter4_reg <= tmp_144_reg_2702_pp0_iter3_reg;
        tmp_144_reg_2702_pp0_iter5_reg <= tmp_144_reg_2702_pp0_iter4_reg;
        tmp_144_reg_2702_pp0_iter6_reg <= tmp_144_reg_2702_pp0_iter5_reg;
        tmp_144_reg_2702_pp0_iter7_reg <= tmp_144_reg_2702_pp0_iter6_reg;
        tmp_144_reg_2702_pp0_iter8_reg <= tmp_144_reg_2702_pp0_iter7_reg;
        tmp_144_reg_2702_pp0_iter9_reg <= tmp_144_reg_2702_pp0_iter8_reg;
        tmp_145_reg_2729 <= select_ln101_2_fu_338_p3[32'd30];
        tmp_146_reg_2735 <= select_ln101_2_fu_338_p3[32'd30];
        tmp_146_reg_2735_pp0_iter10_reg <= tmp_146_reg_2735_pp0_iter9_reg;
        tmp_146_reg_2735_pp0_iter11_reg <= tmp_146_reg_2735_pp0_iter10_reg;
        tmp_146_reg_2735_pp0_iter12_reg <= tmp_146_reg_2735_pp0_iter11_reg;
        tmp_146_reg_2735_pp0_iter2_reg <= tmp_146_reg_2735;
        tmp_146_reg_2735_pp0_iter3_reg <= tmp_146_reg_2735_pp0_iter2_reg;
        tmp_146_reg_2735_pp0_iter4_reg <= tmp_146_reg_2735_pp0_iter3_reg;
        tmp_146_reg_2735_pp0_iter5_reg <= tmp_146_reg_2735_pp0_iter4_reg;
        tmp_146_reg_2735_pp0_iter6_reg <= tmp_146_reg_2735_pp0_iter5_reg;
        tmp_146_reg_2735_pp0_iter7_reg <= tmp_146_reg_2735_pp0_iter6_reg;
        tmp_146_reg_2735_pp0_iter8_reg <= tmp_146_reg_2735_pp0_iter7_reg;
        tmp_146_reg_2735_pp0_iter9_reg <= tmp_146_reg_2735_pp0_iter8_reg;
        tmp_147_reg_2763 <= select_ln101_4_fu_416_p3[32'd30];
        tmp_149_reg_2792 <= select_ln101_7_fu_484_p3[32'd30];
        tmp_149_reg_2792_pp0_iter4_reg <= tmp_149_reg_2792;
        tmp_153_reg_2841 <= select_ln101_13_fu_652_p3[32'd30];
        tmp_154_reg_2847 <= select_ln101_13_fu_652_p3[32'd30];
        tmp_154_reg_2847_pp0_iter10_reg <= tmp_154_reg_2847_pp0_iter9_reg;
        tmp_154_reg_2847_pp0_iter11_reg <= tmp_154_reg_2847_pp0_iter10_reg;
        tmp_154_reg_2847_pp0_iter12_reg <= tmp_154_reg_2847_pp0_iter11_reg;
        tmp_154_reg_2847_pp0_iter6_reg <= tmp_154_reg_2847;
        tmp_154_reg_2847_pp0_iter7_reg <= tmp_154_reg_2847_pp0_iter6_reg;
        tmp_154_reg_2847_pp0_iter8_reg <= tmp_154_reg_2847_pp0_iter7_reg;
        tmp_154_reg_2847_pp0_iter9_reg <= tmp_154_reg_2847_pp0_iter8_reg;
        tmp_155_reg_2880 <= select_ln101_16_fu_751_p3[32'd30];
        tmp_155_reg_2880_pp0_iter7_reg <= tmp_155_reg_2880;
        tmp_159_reg_2934 <= select_ln101_22_fu_928_p3[32'd30];
        tmp_160_reg_2940 <= select_ln101_22_fu_928_p3[32'd30];
        tmp_160_reg_2940_pp0_iter10_reg <= tmp_160_reg_2940_pp0_iter9_reg;
        tmp_160_reg_2940_pp0_iter11_reg <= tmp_160_reg_2940_pp0_iter10_reg;
        tmp_160_reg_2940_pp0_iter12_reg <= tmp_160_reg_2940_pp0_iter11_reg;
        tmp_160_reg_2940_pp0_iter9_reg <= tmp_160_reg_2940;
        tmp_161_reg_2972 <= select_ln101_25_fu_1012_p3[32'd30];
        tmp_162_reg_2978 <= select_ln101_25_fu_1012_p3[32'd30];
        tmp_162_reg_2978_pp0_iter10_reg <= tmp_162_reg_2978;
        tmp_162_reg_2978_pp0_iter11_reg <= tmp_162_reg_2978_pp0_iter10_reg;
        tmp_162_reg_2978_pp0_iter12_reg <= tmp_162_reg_2978_pp0_iter11_reg;
        tmp_163_reg_3006 <= select_ln101_28_fu_1088_p3[32'd30];
        tmp_163_reg_3006_pp0_iter11_reg <= tmp_163_reg_3006;
        tmp_167_reg_3056 <= select_ln101_34_fu_1256_p3[32'd30];
        tmp_169_reg_3090 <= select_ln101_37_fu_1374_p3[32'd30];
        tmp_169_reg_3090_pp0_iter14_reg <= tmp_169_reg_3090;
        tmp_173_reg_3154 <= select_ln101_43_fu_1605_p3[32'd30];
        tmp_174_reg_3160 <= select_ln101_43_fu_1605_p3[32'd30];
        tmp_174_reg_3160_pp0_iter16_reg <= tmp_174_reg_3160;
        tmp_174_reg_3160_pp0_iter17_reg <= tmp_174_reg_3160_pp0_iter16_reg;
        tmp_174_reg_3160_pp0_iter18_reg <= tmp_174_reg_3160_pp0_iter17_reg;
        tmp_174_reg_3160_pp0_iter19_reg <= tmp_174_reg_3160_pp0_iter18_reg;
        tmp_174_reg_3160_pp0_iter20_reg <= tmp_174_reg_3160_pp0_iter19_reg;
        tmp_174_reg_3160_pp0_iter21_reg <= tmp_174_reg_3160_pp0_iter20_reg;
        tmp_174_reg_3160_pp0_iter22_reg <= tmp_174_reg_3160_pp0_iter21_reg;
        tmp_174_reg_3160_pp0_iter23_reg <= tmp_174_reg_3160_pp0_iter22_reg;
        tmp_174_reg_3160_pp0_iter24_reg <= tmp_174_reg_3160_pp0_iter23_reg;
        tmp_174_reg_3160_pp0_iter25_reg <= tmp_174_reg_3160_pp0_iter24_reg;
        tmp_174_reg_3160_pp0_iter26_reg <= tmp_174_reg_3160_pp0_iter25_reg;
        tmp_175_reg_3192 <= select_ln101_46_fu_1704_p3[32'd30];
        tmp_176_reg_3198 <= select_ln101_46_fu_1704_p3[32'd30];
        tmp_176_reg_3198_pp0_iter17_reg <= tmp_176_reg_3198;
        tmp_176_reg_3198_pp0_iter18_reg <= tmp_176_reg_3198_pp0_iter17_reg;
        tmp_176_reg_3198_pp0_iter19_reg <= tmp_176_reg_3198_pp0_iter18_reg;
        tmp_176_reg_3198_pp0_iter20_reg <= tmp_176_reg_3198_pp0_iter19_reg;
        tmp_176_reg_3198_pp0_iter21_reg <= tmp_176_reg_3198_pp0_iter20_reg;
        tmp_176_reg_3198_pp0_iter22_reg <= tmp_176_reg_3198_pp0_iter21_reg;
        tmp_176_reg_3198_pp0_iter23_reg <= tmp_176_reg_3198_pp0_iter22_reg;
        tmp_176_reg_3198_pp0_iter24_reg <= tmp_176_reg_3198_pp0_iter23_reg;
        tmp_176_reg_3198_pp0_iter25_reg <= tmp_176_reg_3198_pp0_iter24_reg;
        tmp_176_reg_3198_pp0_iter26_reg <= tmp_176_reg_3198_pp0_iter25_reg;
        tmp_177_reg_3231 <= select_ln101_49_fu_1789_p3[32'd30];
        tmp_177_reg_3231_pp0_iter18_reg <= tmp_177_reg_3231;
        tmp_181_reg_3280 <= select_ln101_55_fu_1957_p3[32'd30];
        tmp_182_reg_3286 <= select_ln101_55_fu_1957_p3[32'd30];
        tmp_182_reg_3286_pp0_iter20_reg <= tmp_182_reg_3286;
        tmp_182_reg_3286_pp0_iter21_reg <= tmp_182_reg_3286_pp0_iter20_reg;
        tmp_182_reg_3286_pp0_iter22_reg <= tmp_182_reg_3286_pp0_iter21_reg;
        tmp_182_reg_3286_pp0_iter23_reg <= tmp_182_reg_3286_pp0_iter22_reg;
        tmp_182_reg_3286_pp0_iter24_reg <= tmp_182_reg_3286_pp0_iter23_reg;
        tmp_182_reg_3286_pp0_iter25_reg <= tmp_182_reg_3286_pp0_iter24_reg;
        tmp_182_reg_3286_pp0_iter26_reg <= tmp_182_reg_3286_pp0_iter25_reg;
        tmp_183_reg_3319 <= select_ln101_58_fu_2041_p3[32'd30];
        tmp_183_reg_3319_pp0_iter21_reg <= tmp_183_reg_3319;
        tmp_187_reg_3368 <= select_ln101_64_fu_2209_p3[32'd30];
        tmp_188_reg_3374 <= select_ln101_64_fu_2209_p3[32'd30];
        tmp_188_reg_3374_pp0_iter23_reg <= tmp_188_reg_3374;
        tmp_188_reg_3374_pp0_iter24_reg <= tmp_188_reg_3374_pp0_iter23_reg;
        tmp_188_reg_3374_pp0_iter25_reg <= tmp_188_reg_3374_pp0_iter24_reg;
        tmp_189_reg_3406 <= select_ln101_67_fu_2293_p3[32'd30];
        tmp_190_reg_3412 <= select_ln101_67_fu_2293_p3[32'd30];
        tmp_190_reg_3412_pp0_iter24_reg <= tmp_190_reg_3412;
        tmp_190_reg_3412_pp0_iter25_reg <= tmp_190_reg_3412_pp0_iter24_reg;
        tmp_190_reg_3412_pp0_iter26_reg <= tmp_190_reg_3412_pp0_iter25_reg;
        tmp_191_reg_3440 <= select_ln101_70_fu_2369_p3[32'd30];
        tmp_191_reg_3440_pp0_iter25_reg <= tmp_191_reg_3440;
        trunc_ln1333_10_reg_2836 <= {{select_ln101_13_fu_652_p3[30:6]}};
        trunc_ln1333_11_reg_2870 <= {{select_ln101_17_fu_758_p3[30:7]}};
        trunc_ln1333_12_reg_2875 <= {{select_ln101_16_fu_751_p3[30:7]}};
        trunc_ln1333_13_reg_2907 <= {{select_ln101_20_fu_828_p3[30:8]}};
        trunc_ln1333_15_reg_2924 <= {{select_ln101_23_fu_936_p3[30:9]}};
        trunc_ln1333_16_reg_2929 <= {{select_ln101_22_fu_928_p3[30:9]}};
        trunc_ln1333_17_reg_2962 <= {{select_ln101_26_fu_1019_p3[30:10]}};
        trunc_ln1333_18_reg_2967 <= {{select_ln101_25_fu_1012_p3[30:10]}};
        trunc_ln1333_19_reg_2996 <= {{select_ln101_29_fu_1095_p3[30:11]}};
        trunc_ln1333_20_reg_3001 <= {{select_ln101_28_fu_1088_p3[30:11]}};
        trunc_ln1333_21_reg_3028 <= {{select_ln101_32_fu_1156_p3[30:12]}};
        trunc_ln1333_23_reg_3046 <= {{select_ln101_35_fu_1264_p3[30:13]}};
        trunc_ln1333_24_reg_3051 <= {{select_ln101_34_fu_1256_p3[30:13]}};
        trunc_ln1333_25_reg_3080 <= {{select_ln101_38_fu_1381_p3[30:14]}};
        trunc_ln1333_26_reg_3085 <= {{select_ln101_37_fu_1374_p3[30:14]}};
        trunc_ln1333_27_reg_3122 <= {{select_ln101_41_fu_1488_p3[30:15]}};
        trunc_ln1333_29_reg_3144 <= {{select_ln101_44_fu_1613_p3[30:16]}};
        trunc_ln1333_2_reg_2719 <= {{select_ln101_3_fu_346_p3[30:2]}};
        trunc_ln1333_30_reg_3149 <= {{select_ln101_43_fu_1605_p3[30:16]}};
        trunc_ln1333_31_reg_3182 <= {{select_ln101_47_fu_1711_p3[30:17]}};
        trunc_ln1333_32_reg_3187 <= {{select_ln101_46_fu_1704_p3[30:17]}};
        trunc_ln1333_33_reg_3221 <= {{select_ln101_50_fu_1796_p3[30:18]}};
        trunc_ln1333_34_reg_3226 <= {{select_ln101_49_fu_1789_p3[30:18]}};
        trunc_ln1333_35_reg_3253 <= {{select_ln101_53_fu_1857_p3[30:19]}};
        trunc_ln1333_37_reg_3270 <= {{select_ln101_56_fu_1965_p3[30:20]}};
        trunc_ln1333_38_reg_3275 <= {{select_ln101_55_fu_1957_p3[30:20]}};
        trunc_ln1333_39_reg_3309 <= {{select_ln101_59_fu_2048_p3[30:21]}};
        trunc_ln1333_3_reg_2724 <= {{select_ln101_2_fu_338_p3[30:2]}};
        trunc_ln1333_40_reg_3314 <= {{select_ln101_58_fu_2041_p3[30:21]}};
        trunc_ln1333_41_reg_3341 <= {{select_ln101_62_fu_2109_p3[30:22]}};
        trunc_ln1333_43_reg_3358 <= {{select_ln101_65_fu_2217_p3[30:23]}};
        trunc_ln1333_44_reg_3363 <= {{select_ln101_64_fu_2209_p3[30:23]}};
        trunc_ln1333_45_reg_3396 <= {{select_ln101_68_fu_2300_p3[30:24]}};
        trunc_ln1333_46_reg_3401 <= {{select_ln101_67_fu_2293_p3[30:24]}};
        trunc_ln1333_47_reg_3430 <= {{select_ln101_71_fu_2376_p3[30:25]}};
        trunc_ln1333_48_reg_3435 <= {{select_ln101_70_fu_2369_p3[30:25]}};
        trunc_ln1333_4_reg_2753 <= {{select_ln101_5_fu_423_p3[30:3]}};
        trunc_ln1333_5_reg_2758 <= {{select_ln101_4_fu_416_p3[30:3]}};
        trunc_ln1333_6_reg_2782 <= {{select_ln101_8_fu_491_p3[30:4]}};
        trunc_ln1333_7_reg_2787 <= {{select_ln101_7_fu_484_p3[30:4]}};
        trunc_ln1333_8_reg_2814 <= {{select_ln101_11_fu_552_p3[30:5]}};
        trunc_ln1333_s_reg_2831 <= {{select_ln101_14_fu_660_p3[30:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_163_reg_3006 == 1'd1) & (1'b1 == ap_ce))) begin
        add_ln203_10_reg_3017 <= add_ln203_10_fu_1151_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_169_reg_3090 == 1'd1) & (1'b1 == ap_ce))) begin
        add_ln203_13_reg_3111 <= add_ln203_13_fu_1483_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_177_reg_3231 == 1'd1) & (1'b1 == ap_ce))) begin
        add_ln203_17_reg_3242 <= add_ln203_17_fu_1852_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_183_reg_3319 == 1'd1) & (1'b1 == ap_ce))) begin
        add_ln203_20_reg_3330 <= add_ln203_20_fu_2104_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_191_reg_3440 == 1'd1) & (1'b1 == ap_ce))) begin
        add_ln203_24_reg_3451 <= add_ln203_24_fu_2432_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_149_reg_2792 == 1'd1) & (1'b1 == ap_ce))) begin
        add_ln203_3_reg_2803 <= add_ln203_3_fu_547_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_155_reg_2880 == 1'd1) & (1'b1 == ap_ce))) begin
        add_ln203_6_reg_2896 <= add_ln203_6_fu_823_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_163_reg_3006 == 1'd0) & (1'b1 == ap_ce))) begin
        sub_ln703_11_reg_3012 <= sub_ln703_11_fu_1141_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_169_reg_3090 == 1'd0) & (1'b1 == ap_ce))) begin
        sub_ln703_14_reg_3106 <= sub_ln703_14_fu_1473_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_177_reg_3231 == 1'd0) & (1'b1 == ap_ce))) begin
        sub_ln703_18_reg_3237 <= sub_ln703_18_fu_1842_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_183_reg_3319 == 1'd0) & (1'b1 == ap_ce))) begin
        sub_ln703_21_reg_3325 <= sub_ln703_21_fu_2094_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_191_reg_3440 == 1'd0) & (1'b1 == ap_ce))) begin
        sub_ln703_25_reg_3446 <= sub_ln703_25_fu_2422_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_149_reg_2792 == 1'd0) & (1'b1 == ap_ce))) begin
        sub_ln703_4_reg_2798 <= sub_ln703_4_fu_537_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_155_reg_2880 == 1'd0) & (1'b1 == ap_ce))) begin
        sub_ln703_7_reg_2891 <= sub_ln703_7_fu_813_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        x_V_read_int_reg <= x_V_read;
        y_V_read_int_reg <= y_V_read;
    end
end

assign add_ln101_10_fu_1446_p2 = ($signed(add_ln101_8_fu_1437_p2) + $signed(sext_ln101_3_fu_1443_p1));

assign add_ln101_11_fu_1456_p2 = ($signed(add_ln101_7_fu_1431_p2) + $signed(sext_ln101_4_fu_1452_p1));

assign add_ln101_12_fu_1516_p2 = ($signed(add_ln101_5_fu_1508_p2) + $signed(sext_ln101_5_fu_1513_p1));

assign add_ln101_13_fu_1657_p2 = (select_ln101_42_fu_1597_p3 + select_ln101_39_fu_1529_p3);

assign add_ln101_14_fu_1757_p2 = ($signed(select_ln101_36_fu_1670_p3) + $signed(sext_ln101_6_fu_1754_p1));

assign add_ln101_15_fu_2596_p2 = (select_ln101_48_fu_2575_p3 + select_ln101_45_fu_2568_p3);

assign add_ln101_16_fu_2009_p2 = (select_ln101_54_fu_1949_p3 + select_ln101_51_fu_1881_p3);

assign add_ln101_17_fu_2605_p2 = ($signed(add_ln101_15_fu_2596_p2) + $signed(sext_ln101_7_fu_2602_p1));

assign add_ln101_18_fu_2647_p2 = ($signed(add_ln101_14_reg_3203_pp0_iter27_reg) + $signed(sext_ln101_8_fu_2644_p1));

assign add_ln101_19_fu_2261_p2 = (select_ln101_63_fu_2201_p3 + select_ln101_60_fu_2133_p3);

assign add_ln101_1_fu_1416_p2 = (select_ln101_6_cast_fu_1320_p3 + select_ln101_cast_fu_1306_p3);

assign add_ln101_20_fu_2614_p2 = ($signed(select_ln101_57_fu_2582_p3) + $signed(sext_ln101_9_fu_2611_p1));

assign add_ln101_21_fu_2620_p2 = (select_ln101_69_fu_2589_p3 + select_ln101_66_reg_3461);

assign add_ln101_22_fu_2554_p2 = (select_ln101_75_fu_2522_p3 + select_ln101_72_fu_2478_p3);

assign add_ln101_23_fu_2628_p2 = ($signed(add_ln101_21_fu_2620_p2) + $signed(sext_ln101_10_fu_2625_p1));

assign add_ln101_24_fu_2638_p2 = ($signed(add_ln101_20_fu_2614_p2) + $signed(sext_ln101_11_fu_2634_p1));

assign add_ln101_25_fu_2655_p2 = ($signed(add_ln101_18_fu_2647_p2) + $signed(sext_ln101_12_fu_2652_p1));

assign add_ln101_26_fu_2665_p2 = ($signed(add_ln101_12_reg_3127_pp0_iter27_reg) + $signed(sext_ln101_13_fu_2661_p1));

assign add_ln101_2_fu_1422_p2 = (select_ln101_3_cast_fu_1313_p3 + add_ln101_1_fu_1416_p2);

assign add_ln101_3_fu_704_p2 = (select_ln101_12_fu_644_p3 + select_ln101_9_fu_576_p3);

assign add_ln101_4_fu_796_p2 = ($signed(select_ln101_6_fu_717_p3) + $signed(sext_ln101_fu_793_p1));

assign add_ln101_5_fu_1508_p2 = ($signed(add_ln101_2_reg_3096) + $signed(sext_ln101_1_fu_1505_p1));

assign add_ln101_6_fu_980_p2 = (select_ln101_21_fu_920_p3 + select_ln101_18_fu_852_p3);

assign add_ln101_7_fu_1431_p2 = ($signed(select_ln101_15_fu_1327_p3) + $signed(sext_ln101_2_fu_1428_p1));

assign add_ln101_8_fu_1437_p2 = (select_ln101_27_fu_1341_p3 + select_ln101_24_fu_1334_p3);

assign add_ln101_9_fu_1300_p2 = (select_ln101_33_fu_1248_p3 + select_ln101_30_fu_1180_p3);

assign add_ln203_10_fu_1151_p2 = ($signed(sext_ln1371_18_fu_1130_p1) + $signed(select_ln101_28_reg_2983));

assign add_ln203_11_fu_1234_p2 = ($signed(sext_ln1371_20_fu_1193_p1) + $signed(select_ln101_31_fu_1188_p3));

assign add_ln203_12_fu_1369_p2 = ($signed(sext_ln1371_22_fu_1348_p1) + $signed(select_ln101_34_reg_3033));

assign add_ln203_13_fu_1483_p2 = ($signed(sext_ln1371_24_fu_1462_p1) + $signed(select_ln101_37_reg_3067));

assign add_ln203_14_fu_1583_p2 = ($signed(sext_ln1371_26_fu_1542_p1) + $signed(select_ln101_40_fu_1537_p3));

assign add_ln203_15_fu_1699_p2 = ($signed(sext_ln1371_28_fu_1678_p1) + $signed(select_ln101_43_reg_3132));

assign add_ln203_16_fu_1784_p2 = ($signed(sext_ln1371_30_fu_1763_p1) + $signed(select_ln101_46_reg_3170));

assign add_ln203_17_fu_1852_p2 = ($signed(sext_ln1371_32_fu_1831_p1) + $signed(select_ln101_49_reg_3208));

assign add_ln203_18_fu_1935_p2 = ($signed(sext_ln1371_34_fu_1894_p1) + $signed(select_ln101_52_fu_1889_p3));

assign add_ln203_19_fu_2036_p2 = ($signed(sext_ln1371_36_fu_2015_p1) + $signed(select_ln101_55_reg_3258));

assign add_ln203_1_fu_411_p2 = ($signed(sext_ln1371_fu_390_p1) + $signed(select_ln101_2_reg_2707));

assign add_ln203_20_fu_2104_p2 = ($signed(sext_ln1371_38_fu_2083_p1) + $signed(select_ln101_58_reg_3296));

assign add_ln203_21_fu_2187_p2 = ($signed(sext_ln1371_40_fu_2146_p1) + $signed(select_ln101_61_fu_2141_p3));

assign add_ln203_22_fu_2288_p2 = ($signed(sext_ln1371_42_fu_2267_p1) + $signed(select_ln101_64_reg_3346));

assign add_ln203_23_fu_2364_p2 = ($signed(sext_ln1371_44_fu_2343_p1) + $signed(select_ln101_67_reg_3384));

assign add_ln203_24_fu_2432_p2 = ($signed(sext_ln1371_46_fu_2411_p1) + $signed(select_ln101_70_reg_3417));

assign add_ln203_25_fu_2508_p2 = ($signed(sext_ln1371_48_fu_2491_p1) + $signed(select_ln101_73_fu_2486_p3));

assign add_ln203_2_fu_479_p2 = ($signed(sext_ln1371_2_fu_458_p1) + $signed(select_ln101_4_reg_2740));

assign add_ln203_3_fu_547_p2 = ($signed(sext_ln1371_4_fu_526_p1) + $signed(select_ln101_7_reg_2769));

assign add_ln203_4_fu_630_p2 = ($signed(sext_ln1371_6_fu_589_p1) + $signed(select_ln101_10_fu_584_p3));

assign add_ln203_5_fu_746_p2 = ($signed(sext_ln1371_8_fu_725_p1) + $signed(select_ln101_13_reg_2819));

assign add_ln203_6_fu_823_p2 = ($signed(sext_ln1371_10_fu_802_p1) + $signed(select_ln101_16_reg_2857));

assign add_ln203_7_fu_906_p2 = ($signed(sext_ln1371_12_fu_865_p1) + $signed(select_ln101_19_fu_860_p3));

assign add_ln203_8_fu_1007_p2 = ($signed(sext_ln1371_14_fu_986_p1) + $signed(select_ln101_22_reg_2912));

assign add_ln203_9_fu_1083_p2 = ($signed(sext_ln1371_16_fu_1062_p1) + $signed(select_ln101_25_reg_2950));

assign add_ln203_fu_324_p2 = ($signed(sext_ln1333_fu_280_p1) + $signed(select_ln101_fu_260_p3));

assign add_ln703_10_fu_1068_p2 = ($signed(sext_ln1371_17_fu_1065_p1) + $signed(select_ln101_26_reg_2956));

assign add_ln703_11_fu_1136_p2 = ($signed(sext_ln1371_19_fu_1133_p1) + $signed(select_ln101_29_reg_2990));

assign add_ln703_12_fu_1218_p2 = ($signed(sext_ln1371_21_fu_1206_p1) + $signed(select_ln101_32_reg_3022));

assign add_ln703_13_fu_1354_p2 = ($signed(sext_ln1371_23_fu_1351_p1) + $signed(select_ln101_35_reg_3040));

assign add_ln703_14_fu_1468_p2 = ($signed(sext_ln1371_25_fu_1465_p1) + $signed(select_ln101_38_reg_3074));

assign add_ln703_15_fu_1567_p2 = ($signed(sext_ln1371_27_fu_1555_p1) + $signed(select_ln101_41_reg_3116));

assign add_ln703_16_fu_1684_p2 = ($signed(sext_ln1371_29_fu_1681_p1) + $signed(select_ln101_44_reg_3138));

assign add_ln703_17_fu_1769_p2 = ($signed(sext_ln1371_31_fu_1766_p1) + $signed(select_ln101_47_reg_3176));

assign add_ln703_18_fu_1837_p2 = ($signed(sext_ln1371_33_fu_1834_p1) + $signed(select_ln101_50_reg_3215));

assign add_ln703_19_fu_1919_p2 = ($signed(sext_ln1371_35_fu_1907_p1) + $signed(select_ln101_53_reg_3247));

assign add_ln703_1_fu_306_p2 = ($signed(sext_ln1333_1_fu_294_p1) + $signed(select_ln101_1_fu_265_p3));

assign add_ln703_20_fu_2021_p2 = ($signed(sext_ln1371_37_fu_2018_p1) + $signed(select_ln101_56_reg_3264));

assign add_ln703_21_fu_2089_p2 = ($signed(sext_ln1371_39_fu_2086_p1) + $signed(select_ln101_59_reg_3303));

assign add_ln703_22_fu_2171_p2 = ($signed(sext_ln1371_41_fu_2159_p1) + $signed(select_ln101_62_reg_3335));

assign add_ln703_23_fu_2273_p2 = ($signed(sext_ln1371_43_fu_2270_p1) + $signed(select_ln101_65_reg_3352));

assign add_ln703_24_fu_2349_p2 = ($signed(sext_ln1371_45_fu_2346_p1) + $signed(select_ln101_68_reg_3390));

assign add_ln703_25_fu_2417_p2 = ($signed(sext_ln1371_47_fu_2414_p1) + $signed(select_ln101_71_reg_3424));

assign add_ln703_26_fu_464_p2 = ($signed(sext_ln1371_3_fu_461_p1) + $signed(select_ln101_5_reg_2747));

assign add_ln703_2_fu_396_p2 = ($signed(sext_ln1371_1_fu_393_p1) + $signed(select_ln101_3_reg_2713));

assign add_ln703_4_fu_532_p2 = ($signed(sext_ln1371_5_fu_529_p1) + $signed(select_ln101_8_reg_2776));

assign add_ln703_5_fu_614_p2 = ($signed(sext_ln1371_7_fu_602_p1) + $signed(select_ln101_11_reg_2808));

assign add_ln703_6_fu_731_p2 = ($signed(sext_ln1371_9_fu_728_p1) + $signed(select_ln101_14_reg_2825));

assign add_ln703_7_fu_808_p2 = ($signed(sext_ln1371_11_fu_805_p1) + $signed(select_ln101_17_reg_2864));

assign add_ln703_8_fu_890_p2 = ($signed(sext_ln1371_13_fu_878_p1) + $signed(select_ln101_20_reg_2901));

assign add_ln703_9_fu_992_p2 = ($signed(sext_ln1371_15_fu_989_p1) + $signed(select_ln101_23_reg_2918));

assign add_ln703_fu_234_p2 = ($signed(y_V_read_cast1_fu_218_p1) + $signed(x_V_read_cast_fu_222_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_return = (add_ln101_26_fu_2665_p2 + select_ln101_80_cast_reg_3471_pp0_iter27_reg);

assign select_ln101_10_fu_584_p3 = ((tmp_149_reg_2792_pp0_iter4_reg[0:0] === 1'b1) ? add_ln203_3_reg_2803 : sub_ln703_4_reg_2798);

assign select_ln101_11_fu_552_p3 = ((tmp_149_reg_2792[0:0] === 1'b1) ? sub_ln203_4_fu_542_p2 : add_ln703_4_fu_532_p2);

assign select_ln101_12_fu_644_p3 = ((tmp_152_fu_636_p3[0:0] === 1'b1) ? 27'd117445972 : 27'd0);

assign select_ln101_13_fu_652_p3 = ((tmp_151_fu_606_p3[0:0] === 1'b1) ? add_ln203_4_fu_630_p2 : sub_ln703_5_fu_619_p2);

assign select_ln101_14_fu_660_p3 = ((tmp_151_fu_606_p3[0:0] === 1'b1) ? sub_ln203_5_fu_625_p2 : add_ln703_5_fu_614_p2);

assign select_ln101_15_fu_1327_p3 = ((tmp_154_reg_2847_pp0_iter12_reg[0:0] === 1'b1) ? 25'd25166508 : 25'd0);

assign select_ln101_16_fu_751_p3 = ((tmp_153_reg_2841[0:0] === 1'b1) ? add_ln203_5_fu_746_p2 : sub_ln703_6_fu_736_p2);

assign select_ln101_17_fu_758_p3 = ((tmp_153_reg_2841[0:0] === 1'b1) ? sub_ln203_6_fu_741_p2 : add_ln703_6_fu_731_p2);

assign select_ln101_18_fu_852_p3 = ((tmp_156_fu_845_p3[0:0] === 1'b1) ? 24'd12582998 : 24'd0);

assign select_ln101_19_fu_860_p3 = ((tmp_155_reg_2880_pp0_iter7_reg[0:0] === 1'b1) ? add_ln203_6_reg_2896 : sub_ln703_7_reg_2891);

assign select_ln101_1_fu_265_p3 = ((tmp_141_reg_2675[0:0] === 1'b1) ? sub_ln203_reg_2692 : add_ln703_reg_2681);

assign select_ln101_20_fu_828_p3 = ((tmp_155_reg_2880[0:0] === 1'b1) ? sub_ln203_7_fu_818_p2 : add_ln703_7_fu_808_p2);

assign select_ln101_21_fu_920_p3 = ((tmp_158_fu_912_p3[0:0] === 1'b1) ? 24'd14680076 : 24'd0);

assign select_ln101_22_fu_928_p3 = ((tmp_157_fu_882_p3[0:0] === 1'b1) ? add_ln203_7_fu_906_p2 : sub_ln703_8_fu_895_p2);

assign select_ln101_23_fu_936_p3 = ((tmp_157_fu_882_p3[0:0] === 1'b1) ? sub_ln203_8_fu_901_p2 : add_ln703_8_fu_890_p2);

assign select_ln101_24_fu_1334_p3 = ((tmp_160_reg_2940_pp0_iter12_reg[0:0] === 1'b1) ? 22'd3145730 : 22'd0);

assign select_ln101_25_fu_1012_p3 = ((tmp_159_reg_2934[0:0] === 1'b1) ? add_ln203_8_fu_1007_p2 : sub_ln703_9_fu_997_p2);

assign select_ln101_26_fu_1019_p3 = ((tmp_159_reg_2934[0:0] === 1'b1) ? sub_ln203_9_fu_1002_p2 : add_ln703_9_fu_992_p2);

assign select_ln101_27_fu_1341_p3 = ((tmp_162_reg_2978_pp0_iter12_reg[0:0] === 1'b1) ? 22'd3670018 : 22'd0);

assign select_ln101_28_fu_1088_p3 = ((tmp_161_reg_2972[0:0] === 1'b1) ? add_ln203_9_fu_1083_p2 : sub_ln703_10_fu_1073_p2);

assign select_ln101_29_fu_1095_p3 = ((tmp_161_reg_2972[0:0] === 1'b1) ? sub_ln203_10_fu_1078_p2 : add_ln703_10_fu_1068_p2);

assign select_ln101_2_fu_338_p3 = ((tmp_143_fu_298_p3[0:0] === 1'b1) ? add_ln203_fu_324_p2 : sub_ln703_1_fu_312_p2);

assign select_ln101_30_fu_1180_p3 = ((tmp_164_fu_1173_p3[0:0] === 1'b1) ? 20'd786434 : 20'd0);

assign select_ln101_31_fu_1188_p3 = ((tmp_163_reg_3006_pp0_iter11_reg[0:0] === 1'b1) ? add_ln203_10_reg_3017 : sub_ln703_11_reg_3012);

assign select_ln101_32_fu_1156_p3 = ((tmp_163_reg_3006[0:0] === 1'b1) ? sub_ln203_11_fu_1146_p2 : add_ln703_11_fu_1136_p2);

assign select_ln101_33_fu_1248_p3 = ((tmp_166_fu_1240_p3[0:0] === 1'b1) ? 20'd917506 : 20'd0);

assign select_ln101_34_fu_1256_p3 = ((tmp_165_fu_1210_p3[0:0] === 1'b1) ? add_ln203_11_fu_1234_p2 : sub_ln703_12_fu_1223_p2);

assign select_ln101_35_fu_1264_p3 = ((tmp_165_fu_1210_p3[0:0] === 1'b1) ? sub_ln203_12_fu_1229_p2 : add_ln703_12_fu_1218_p2);

assign select_ln101_36_fu_1670_p3 = ((tmp_168_fu_1663_p3[0:0] === 1'b1) ? 18'd196610 : 18'd0);

assign select_ln101_37_fu_1374_p3 = ((tmp_167_reg_3056[0:0] === 1'b1) ? add_ln203_12_fu_1369_p2 : sub_ln703_13_fu_1359_p2);

assign select_ln101_38_fu_1381_p3 = ((tmp_167_reg_3056[0:0] === 1'b1) ? sub_ln203_13_fu_1364_p2 : add_ln703_13_fu_1354_p2);

assign select_ln101_39_fu_1529_p3 = ((tmp_170_fu_1522_p3[0:0] === 1'b1) ? 17'd98306 : 17'd0);

assign select_ln101_3_cast_fu_1313_p3 = ((tmp_144_reg_2702_pp0_iter12_reg[0:0] === 1'b1) ? 30'd824822910 : 30'd0);

assign select_ln101_3_fu_346_p3 = ((tmp_143_fu_298_p3[0:0] === 1'b1) ? sub_ln203_1_fu_318_p2 : add_ln703_1_fu_306_p2);

assign select_ln101_40_fu_1537_p3 = ((tmp_169_reg_3090_pp0_iter14_reg[0:0] === 1'b1) ? add_ln203_13_reg_3111 : sub_ln703_14_reg_3106);

assign select_ln101_41_fu_1488_p3 = ((tmp_169_reg_3090[0:0] === 1'b1) ? sub_ln203_14_fu_1478_p2 : add_ln703_14_fu_1468_p2);

assign select_ln101_42_fu_1597_p3 = ((tmp_172_fu_1589_p3[0:0] === 1'b1) ? 17'd114690 : 17'd0);

assign select_ln101_43_fu_1605_p3 = ((tmp_171_fu_1559_p3[0:0] === 1'b1) ? add_ln203_14_fu_1583_p2 : sub_ln703_15_fu_1572_p2);

assign select_ln101_44_fu_1613_p3 = ((tmp_171_fu_1559_p3[0:0] === 1'b1) ? sub_ln203_15_fu_1578_p2 : add_ln703_15_fu_1567_p2);

assign select_ln101_45_fu_2568_p3 = ((tmp_174_reg_3160_pp0_iter26_reg[0:0] === 1'b1) ? 15'd24578 : 15'd0);

assign select_ln101_46_fu_1704_p3 = ((tmp_173_reg_3154[0:0] === 1'b1) ? add_ln203_15_fu_1699_p2 : sub_ln703_16_fu_1689_p2);

assign select_ln101_47_fu_1711_p3 = ((tmp_173_reg_3154[0:0] === 1'b1) ? sub_ln203_16_fu_1694_p2 : add_ln703_16_fu_1684_p2);

assign select_ln101_48_fu_2575_p3 = ((tmp_176_reg_3198_pp0_iter26_reg[0:0] === 1'b1) ? 15'd28674 : 15'd0);

assign select_ln101_49_fu_1789_p3 = ((tmp_175_reg_3192[0:0] === 1'b1) ? add_ln203_16_fu_1784_p2 : sub_ln703_17_fu_1774_p2);

assign select_ln101_4_fu_416_p3 = ((tmp_145_reg_2729[0:0] === 1'b1) ? add_ln203_1_fu_411_p2 : sub_ln703_2_fu_401_p2);

assign select_ln101_50_fu_1796_p3 = ((tmp_175_reg_3192[0:0] === 1'b1) ? sub_ln203_17_fu_1779_p2 : add_ln703_17_fu_1769_p2);

assign select_ln101_51_fu_1881_p3 = ((tmp_178_fu_1874_p3[0:0] === 1'b1) ? 13'd6146 : 13'd0);

assign select_ln101_52_fu_1889_p3 = ((tmp_177_reg_3231_pp0_iter18_reg[0:0] === 1'b1) ? add_ln203_17_reg_3242 : sub_ln703_18_reg_3237);

assign select_ln101_53_fu_1857_p3 = ((tmp_177_reg_3231[0:0] === 1'b1) ? sub_ln203_18_fu_1847_p2 : add_ln703_18_fu_1837_p2);

assign select_ln101_54_fu_1949_p3 = ((tmp_180_fu_1941_p3[0:0] === 1'b1) ? 13'd7170 : 13'd0);

assign select_ln101_55_fu_1957_p3 = ((tmp_179_fu_1911_p3[0:0] === 1'b1) ? add_ln203_18_fu_1935_p2 : sub_ln703_19_fu_1924_p2);

assign select_ln101_56_fu_1965_p3 = ((tmp_179_fu_1911_p3[0:0] === 1'b1) ? sub_ln203_19_fu_1930_p2 : add_ln703_19_fu_1919_p2);

assign select_ln101_57_fu_2582_p3 = ((tmp_182_reg_3286_pp0_iter26_reg[0:0] === 1'b1) ? 11'd1538 : 11'd0);

assign select_ln101_58_fu_2041_p3 = ((tmp_181_reg_3280[0:0] === 1'b1) ? add_ln203_19_fu_2036_p2 : sub_ln703_20_fu_2026_p2);

assign select_ln101_59_fu_2048_p3 = ((tmp_181_reg_3280[0:0] === 1'b1) ? sub_ln203_20_fu_2031_p2 : add_ln703_20_fu_2021_p2);

assign select_ln101_5_fu_423_p3 = ((tmp_145_reg_2729[0:0] === 1'b1) ? sub_ln203_2_fu_406_p2 : add_ln703_2_fu_396_p2);

assign select_ln101_60_fu_2133_p3 = ((tmp_184_fu_2126_p3[0:0] === 1'b1) ? 10'd770 : 10'd0);

assign select_ln101_61_fu_2141_p3 = ((tmp_183_reg_3319_pp0_iter21_reg[0:0] === 1'b1) ? add_ln203_20_reg_3330 : sub_ln703_21_reg_3325);

assign select_ln101_62_fu_2109_p3 = ((tmp_183_reg_3319[0:0] === 1'b1) ? sub_ln203_21_fu_2099_p2 : add_ln703_21_fu_2089_p2);

assign select_ln101_63_fu_2201_p3 = ((tmp_186_fu_2193_p3[0:0] === 1'b1) ? 10'd898 : 10'd0);

assign select_ln101_64_fu_2209_p3 = ((tmp_185_fu_2163_p3[0:0] === 1'b1) ? add_ln203_21_fu_2187_p2 : sub_ln703_22_fu_2176_p2);

assign select_ln101_65_fu_2217_p3 = ((tmp_185_fu_2163_p3[0:0] === 1'b1) ? sub_ln203_22_fu_2182_p2 : add_ln703_22_fu_2171_p2);

assign select_ln101_66_fu_2464_p3 = ((tmp_188_reg_3374_pp0_iter25_reg[0:0] === 1'b1) ? 8'd194 : 8'd0);

assign select_ln101_67_fu_2293_p3 = ((tmp_187_reg_3368[0:0] === 1'b1) ? add_ln203_22_fu_2288_p2 : sub_ln703_23_fu_2278_p2);

assign select_ln101_68_fu_2300_p3 = ((tmp_187_reg_3368[0:0] === 1'b1) ? sub_ln203_23_fu_2283_p2 : add_ln703_23_fu_2273_p2);

assign select_ln101_69_fu_2589_p3 = ((tmp_190_reg_3412_pp0_iter26_reg[0:0] === 1'b1) ? 8'd226 : 8'd0);

assign select_ln101_6_cast_fu_1320_p3 = ((tmp_146_reg_2735_pp0_iter12_reg[0:0] === 1'b1) ? 30'd942219906 : 30'd0);

assign select_ln101_6_fu_717_p3 = ((tmp_148_fu_710_p3[0:0] === 1'b1) ? 28'd201672878 : 28'd0);

assign select_ln101_70_fu_2369_p3 = ((tmp_189_reg_3406[0:0] === 1'b1) ? add_ln203_23_fu_2364_p2 : sub_ln703_24_fu_2354_p2);

assign select_ln101_71_fu_2376_p3 = ((tmp_189_reg_3406[0:0] === 1'b1) ? sub_ln203_24_fu_2359_p2 : add_ln703_24_fu_2349_p2);

assign select_ln101_72_fu_2478_p3 = ((tmp_192_fu_2471_p3[0:0] === 1'b1) ? 6'd50 : 6'd0);

assign select_ln101_73_fu_2486_p3 = ((tmp_191_reg_3440_pp0_iter25_reg[0:0] === 1'b1) ? add_ln203_24_reg_3451 : sub_ln703_25_reg_3446);

assign select_ln101_74_fu_2457_p3 = ((tmp_191_reg_3440[0:0] === 1'b1) ? tmp_s_fu_2447_p4 : tmp_fu_2437_p4);

assign select_ln101_75_fu_2522_p3 = ((tmp_194_fu_2514_p3[0:0] === 1'b1) ? 6'd58 : 6'd0);

assign select_ln101_76_fu_2546_p3 = ((tmp_193_fu_2494_p3[0:0] === 1'b1) ? tmp_196_fu_2538_p3 : tmp_195_fu_2530_p3);

assign select_ln101_7_fu_484_p3 = ((tmp_147_reg_2763[0:0] === 1'b1) ? add_ln203_2_fu_479_p2 : sub_ln703_3_fu_469_p2);

assign select_ln101_80_cast_fu_2560_p3 = ((select_ln101_76_fu_2546_p3[0:0] === 1'b1) ? 30'd467959912 : 30'd467959914);

assign select_ln101_8_fu_491_p3 = ((tmp_147_reg_2763[0:0] === 1'b1) ? sub_ln203_3_fu_474_p2 : add_ln703_26_fu_464_p2);

assign select_ln101_9_fu_576_p3 = ((tmp_150_fu_569_p3[0:0] === 1'b1) ? 27'd100706886 : 27'd0);

assign select_ln101_cast_fu_1306_p3 = ((tmp_142_reg_2697_pp0_iter12_reg[0:0] === 1'b1) ? 30'd652084396 : 30'd0);

assign select_ln101_fu_260_p3 = ((tmp_141_reg_2675[0:0] === 1'b1) ? add_ln703_reg_2681 : sub_ln703_reg_2687);

assign sext_ln101_10_fu_2625_p1 = $signed(add_ln101_22_reg_3466);

assign sext_ln101_11_fu_2634_p1 = $signed(add_ln101_23_fu_2628_p2);

assign sext_ln101_12_fu_2652_p1 = $signed(add_ln101_24_reg_3481);

assign sext_ln101_13_fu_2661_p1 = $signed(add_ln101_25_fu_2655_p2);

assign sext_ln101_1_fu_1505_p1 = $signed(add_ln101_4_reg_2886_pp0_iter13_reg);

assign sext_ln101_2_fu_1428_p1 = $signed(add_ln101_6_reg_2945_pp0_iter12_reg);

assign sext_ln101_3_fu_1443_p1 = $signed(add_ln101_9_reg_3062);

assign sext_ln101_4_fu_1452_p1 = $signed(add_ln101_10_fu_1446_p2);

assign sext_ln101_5_fu_1513_p1 = $signed(add_ln101_11_reg_3101);

assign sext_ln101_6_fu_1754_p1 = $signed(add_ln101_13_reg_3165);

assign sext_ln101_7_fu_2602_p1 = $signed(add_ln101_16_reg_3291_pp0_iter26_reg);

assign sext_ln101_8_fu_2644_p1 = $signed(add_ln101_17_reg_3476);

assign sext_ln101_9_fu_2611_p1 = $signed(add_ln101_19_reg_3379_pp0_iter26_reg);

assign sext_ln101_fu_793_p1 = $signed(add_ln101_3_reg_2852);

assign sext_ln1333_1_fu_294_p1 = $signed(trunc_ln1333_1_fu_284_p4);

assign sext_ln1333_fu_280_p1 = $signed(trunc_ln_fu_270_p4);

assign sext_ln1371_10_fu_802_p1 = $signed(trunc_ln1333_11_reg_2870);

assign sext_ln1371_11_fu_805_p1 = $signed(trunc_ln1333_12_reg_2875);

assign sext_ln1371_12_fu_865_p1 = $signed(trunc_ln1333_13_reg_2907);

assign sext_ln1371_13_fu_878_p1 = $signed(trunc_ln1333_14_fu_868_p4);

assign sext_ln1371_14_fu_986_p1 = $signed(trunc_ln1333_15_reg_2924);

assign sext_ln1371_15_fu_989_p1 = $signed(trunc_ln1333_16_reg_2929);

assign sext_ln1371_16_fu_1062_p1 = $signed(trunc_ln1333_17_reg_2962);

assign sext_ln1371_17_fu_1065_p1 = $signed(trunc_ln1333_18_reg_2967);

assign sext_ln1371_18_fu_1130_p1 = $signed(trunc_ln1333_19_reg_2996);

assign sext_ln1371_19_fu_1133_p1 = $signed(trunc_ln1333_20_reg_3001);

assign sext_ln1371_1_fu_393_p1 = $signed(trunc_ln1333_3_reg_2724);

assign sext_ln1371_20_fu_1193_p1 = $signed(trunc_ln1333_21_reg_3028);

assign sext_ln1371_21_fu_1206_p1 = $signed(trunc_ln1333_22_fu_1196_p4);

assign sext_ln1371_22_fu_1348_p1 = $signed(trunc_ln1333_23_reg_3046);

assign sext_ln1371_23_fu_1351_p1 = $signed(trunc_ln1333_24_reg_3051);

assign sext_ln1371_24_fu_1462_p1 = $signed(trunc_ln1333_25_reg_3080);

assign sext_ln1371_25_fu_1465_p1 = $signed(trunc_ln1333_26_reg_3085);

assign sext_ln1371_26_fu_1542_p1 = $signed(trunc_ln1333_27_reg_3122);

assign sext_ln1371_27_fu_1555_p1 = $signed(trunc_ln1333_28_fu_1545_p4);

assign sext_ln1371_28_fu_1678_p1 = $signed(trunc_ln1333_29_reg_3144);

assign sext_ln1371_29_fu_1681_p1 = $signed(trunc_ln1333_30_reg_3149);

assign sext_ln1371_2_fu_458_p1 = $signed(trunc_ln1333_4_reg_2753);

assign sext_ln1371_30_fu_1763_p1 = $signed(trunc_ln1333_31_reg_3182);

assign sext_ln1371_31_fu_1766_p1 = $signed(trunc_ln1333_32_reg_3187);

assign sext_ln1371_32_fu_1831_p1 = $signed(trunc_ln1333_33_reg_3221);

assign sext_ln1371_33_fu_1834_p1 = $signed(trunc_ln1333_34_reg_3226);

assign sext_ln1371_34_fu_1894_p1 = $signed(trunc_ln1333_35_reg_3253);

assign sext_ln1371_35_fu_1907_p1 = $signed(trunc_ln1333_36_fu_1897_p4);

assign sext_ln1371_36_fu_2015_p1 = $signed(trunc_ln1333_37_reg_3270);

assign sext_ln1371_37_fu_2018_p1 = $signed(trunc_ln1333_38_reg_3275);

assign sext_ln1371_38_fu_2083_p1 = $signed(trunc_ln1333_39_reg_3309);

assign sext_ln1371_39_fu_2086_p1 = $signed(trunc_ln1333_40_reg_3314);

assign sext_ln1371_3_fu_461_p1 = $signed(trunc_ln1333_5_reg_2758);

assign sext_ln1371_40_fu_2146_p1 = $signed(trunc_ln1333_41_reg_3341);

assign sext_ln1371_41_fu_2159_p1 = $signed(trunc_ln1333_42_fu_2149_p4);

assign sext_ln1371_42_fu_2267_p1 = $signed(trunc_ln1333_43_reg_3358);

assign sext_ln1371_43_fu_2270_p1 = $signed(trunc_ln1333_44_reg_3363);

assign sext_ln1371_44_fu_2343_p1 = $signed(trunc_ln1333_45_reg_3396);

assign sext_ln1371_45_fu_2346_p1 = $signed(trunc_ln1333_46_reg_3401);

assign sext_ln1371_46_fu_2411_p1 = $signed(trunc_ln1333_47_reg_3430);

assign sext_ln1371_47_fu_2414_p1 = $signed(trunc_ln1333_48_reg_3435);

assign sext_ln1371_48_fu_2491_p1 = $signed(select_ln101_74_reg_3456);

assign sext_ln1371_4_fu_526_p1 = $signed(trunc_ln1333_6_reg_2782);

assign sext_ln1371_5_fu_529_p1 = $signed(trunc_ln1333_7_reg_2787);

assign sext_ln1371_6_fu_589_p1 = $signed(trunc_ln1333_8_reg_2814);

assign sext_ln1371_7_fu_602_p1 = $signed(trunc_ln1333_9_fu_592_p4);

assign sext_ln1371_8_fu_725_p1 = $signed(trunc_ln1333_s_reg_2831);

assign sext_ln1371_9_fu_728_p1 = $signed(trunc_ln1333_10_reg_2836);

assign sext_ln1371_fu_390_p1 = $signed(trunc_ln1333_2_reg_2719);

assign sub_ln203_10_fu_1078_p2 = ($signed(select_ln101_26_reg_2956) - $signed(sext_ln1371_17_fu_1065_p1));

assign sub_ln203_11_fu_1146_p2 = ($signed(select_ln101_29_reg_2990) - $signed(sext_ln1371_19_fu_1133_p1));

assign sub_ln203_12_fu_1229_p2 = ($signed(select_ln101_32_reg_3022) - $signed(sext_ln1371_21_fu_1206_p1));

assign sub_ln203_13_fu_1364_p2 = ($signed(select_ln101_35_reg_3040) - $signed(sext_ln1371_23_fu_1351_p1));

assign sub_ln203_14_fu_1478_p2 = ($signed(select_ln101_38_reg_3074) - $signed(sext_ln1371_25_fu_1465_p1));

assign sub_ln203_15_fu_1578_p2 = ($signed(select_ln101_41_reg_3116) - $signed(sext_ln1371_27_fu_1555_p1));

assign sub_ln203_16_fu_1694_p2 = ($signed(select_ln101_44_reg_3138) - $signed(sext_ln1371_29_fu_1681_p1));

assign sub_ln203_17_fu_1779_p2 = ($signed(select_ln101_47_reg_3176) - $signed(sext_ln1371_31_fu_1766_p1));

assign sub_ln203_18_fu_1847_p2 = ($signed(select_ln101_50_reg_3215) - $signed(sext_ln1371_33_fu_1834_p1));

assign sub_ln203_19_fu_1930_p2 = ($signed(select_ln101_53_reg_3247) - $signed(sext_ln1371_35_fu_1907_p1));

assign sub_ln203_1_fu_318_p2 = ($signed(select_ln101_1_fu_265_p3) - $signed(sext_ln1333_1_fu_294_p1));

assign sub_ln203_20_fu_2031_p2 = ($signed(select_ln101_56_reg_3264) - $signed(sext_ln1371_37_fu_2018_p1));

assign sub_ln203_21_fu_2099_p2 = ($signed(select_ln101_59_reg_3303) - $signed(sext_ln1371_39_fu_2086_p1));

assign sub_ln203_22_fu_2182_p2 = ($signed(select_ln101_62_reg_3335) - $signed(sext_ln1371_41_fu_2159_p1));

assign sub_ln203_23_fu_2283_p2 = ($signed(select_ln101_65_reg_3352) - $signed(sext_ln1371_43_fu_2270_p1));

assign sub_ln203_24_fu_2359_p2 = ($signed(select_ln101_68_reg_3390) - $signed(sext_ln1371_45_fu_2346_p1));

assign sub_ln203_25_fu_2427_p2 = ($signed(select_ln101_71_reg_3424) - $signed(sext_ln1371_47_fu_2414_p1));

assign sub_ln203_2_fu_406_p2 = ($signed(select_ln101_3_reg_2713) - $signed(sext_ln1371_1_fu_393_p1));

assign sub_ln203_3_fu_474_p2 = ($signed(select_ln101_5_reg_2747) - $signed(sext_ln1371_3_fu_461_p1));

assign sub_ln203_4_fu_542_p2 = ($signed(select_ln101_8_reg_2776) - $signed(sext_ln1371_5_fu_529_p1));

assign sub_ln203_5_fu_625_p2 = ($signed(select_ln101_11_reg_2808) - $signed(sext_ln1371_7_fu_602_p1));

assign sub_ln203_6_fu_741_p2 = ($signed(select_ln101_14_reg_2825) - $signed(sext_ln1371_9_fu_728_p1));

assign sub_ln203_7_fu_818_p2 = ($signed(select_ln101_17_reg_2864) - $signed(sext_ln1371_11_fu_805_p1));

assign sub_ln203_8_fu_901_p2 = ($signed(select_ln101_20_reg_2901) - $signed(sext_ln1371_13_fu_878_p1));

assign sub_ln203_9_fu_1002_p2 = ($signed(select_ln101_23_reg_2918) - $signed(sext_ln1371_15_fu_989_p1));

assign sub_ln203_fu_246_p2 = ($signed(x_V_read_cast_fu_222_p1) - $signed(y_V_read_cast1_fu_218_p1));

assign sub_ln703_10_fu_1073_p2 = ($signed(select_ln101_25_reg_2950) - $signed(sext_ln1371_16_fu_1062_p1));

assign sub_ln703_11_fu_1141_p2 = ($signed(select_ln101_28_reg_2983) - $signed(sext_ln1371_18_fu_1130_p1));

assign sub_ln703_12_fu_1223_p2 = ($signed(select_ln101_31_fu_1188_p3) - $signed(sext_ln1371_20_fu_1193_p1));

assign sub_ln703_13_fu_1359_p2 = ($signed(select_ln101_34_reg_3033) - $signed(sext_ln1371_22_fu_1348_p1));

assign sub_ln703_14_fu_1473_p2 = ($signed(select_ln101_37_reg_3067) - $signed(sext_ln1371_24_fu_1462_p1));

assign sub_ln703_15_fu_1572_p2 = ($signed(select_ln101_40_fu_1537_p3) - $signed(sext_ln1371_26_fu_1542_p1));

assign sub_ln703_16_fu_1689_p2 = ($signed(select_ln101_43_reg_3132) - $signed(sext_ln1371_28_fu_1678_p1));

assign sub_ln703_17_fu_1774_p2 = ($signed(select_ln101_46_reg_3170) - $signed(sext_ln1371_30_fu_1763_p1));

assign sub_ln703_18_fu_1842_p2 = ($signed(select_ln101_49_reg_3208) - $signed(sext_ln1371_32_fu_1831_p1));

assign sub_ln703_19_fu_1924_p2 = ($signed(select_ln101_52_fu_1889_p3) - $signed(sext_ln1371_34_fu_1894_p1));

assign sub_ln703_1_fu_312_p2 = ($signed(select_ln101_fu_260_p3) - $signed(sext_ln1333_fu_280_p1));

assign sub_ln703_20_fu_2026_p2 = ($signed(select_ln101_55_reg_3258) - $signed(sext_ln1371_36_fu_2015_p1));

assign sub_ln703_21_fu_2094_p2 = ($signed(select_ln101_58_reg_3296) - $signed(sext_ln1371_38_fu_2083_p1));

assign sub_ln703_22_fu_2176_p2 = ($signed(select_ln101_61_fu_2141_p3) - $signed(sext_ln1371_40_fu_2146_p1));

assign sub_ln703_23_fu_2278_p2 = ($signed(select_ln101_64_reg_3346) - $signed(sext_ln1371_42_fu_2267_p1));

assign sub_ln703_24_fu_2354_p2 = ($signed(select_ln101_67_reg_3384) - $signed(sext_ln1371_44_fu_2343_p1));

assign sub_ln703_25_fu_2422_p2 = ($signed(select_ln101_70_reg_3417) - $signed(sext_ln1371_46_fu_2411_p1));

assign sub_ln703_26_fu_2502_p2 = ($signed(select_ln101_73_fu_2486_p3) - $signed(sext_ln1371_48_fu_2491_p1));

assign sub_ln703_2_fu_401_p2 = ($signed(select_ln101_2_reg_2707) - $signed(sext_ln1371_fu_390_p1));

assign sub_ln703_3_fu_469_p2 = ($signed(select_ln101_4_reg_2740) - $signed(sext_ln1371_2_fu_458_p1));

assign sub_ln703_4_fu_537_p2 = ($signed(select_ln101_7_reg_2769) - $signed(sext_ln1371_4_fu_526_p1));

assign sub_ln703_5_fu_619_p2 = ($signed(select_ln101_10_fu_584_p3) - $signed(sext_ln1371_6_fu_589_p1));

assign sub_ln703_6_fu_736_p2 = ($signed(select_ln101_13_reg_2819) - $signed(sext_ln1371_8_fu_725_p1));

assign sub_ln703_7_fu_813_p2 = ($signed(select_ln101_16_reg_2857) - $signed(sext_ln1371_10_fu_802_p1));

assign sub_ln703_8_fu_895_p2 = ($signed(select_ln101_19_fu_860_p3) - $signed(sext_ln1371_12_fu_865_p1));

assign sub_ln703_9_fu_997_p2 = ($signed(select_ln101_22_reg_2912) - $signed(sext_ln1371_14_fu_986_p1));

assign sub_ln703_fu_240_p2 = ($signed(y_V_read_cast1_fu_218_p1) - $signed(x_V_read_cast_fu_222_p1));

assign tmp_141_fu_226_p1 = y_V_read_int_reg;

assign tmp_142_fu_252_p1 = y_V_read_int_reg;

assign tmp_143_fu_298_p3 = select_ln101_fu_260_p3[32'd30];

assign tmp_148_fu_710_p3 = select_ln101_4_reg_2740_pp0_iter5_reg[32'd30];

assign tmp_150_fu_569_p3 = select_ln101_7_reg_2769_pp0_iter4_reg[32'd30];

assign tmp_151_fu_606_p3 = select_ln101_10_fu_584_p3[32'd30];

assign tmp_152_fu_636_p3 = select_ln101_10_fu_584_p3[32'd30];

assign tmp_156_fu_845_p3 = select_ln101_16_reg_2857_pp0_iter7_reg[32'd30];

assign tmp_157_fu_882_p3 = select_ln101_19_fu_860_p3[32'd30];

assign tmp_158_fu_912_p3 = select_ln101_19_fu_860_p3[32'd30];

assign tmp_164_fu_1173_p3 = select_ln101_28_reg_2983_pp0_iter11_reg[32'd30];

assign tmp_165_fu_1210_p3 = select_ln101_31_fu_1188_p3[32'd30];

assign tmp_166_fu_1240_p3 = select_ln101_31_fu_1188_p3[32'd30];

assign tmp_168_fu_1663_p3 = select_ln101_34_reg_3033_pp0_iter15_reg[32'd30];

assign tmp_170_fu_1522_p3 = select_ln101_37_reg_3067_pp0_iter14_reg[32'd30];

assign tmp_171_fu_1559_p3 = select_ln101_40_fu_1537_p3[32'd30];

assign tmp_172_fu_1589_p3 = select_ln101_40_fu_1537_p3[32'd30];

assign tmp_178_fu_1874_p3 = select_ln101_49_reg_3208_pp0_iter18_reg[32'd30];

assign tmp_179_fu_1911_p3 = select_ln101_52_fu_1889_p3[32'd30];

assign tmp_180_fu_1941_p3 = select_ln101_52_fu_1889_p3[32'd30];

assign tmp_184_fu_2126_p3 = select_ln101_58_reg_3296_pp0_iter21_reg[32'd30];

assign tmp_185_fu_2163_p3 = select_ln101_61_fu_2141_p3[32'd30];

assign tmp_186_fu_2193_p3 = select_ln101_61_fu_2141_p3[32'd30];

assign tmp_192_fu_2471_p3 = select_ln101_70_reg_3417_pp0_iter25_reg[32'd30];

assign tmp_193_fu_2494_p3 = select_ln101_73_fu_2486_p3[32'd30];

assign tmp_194_fu_2514_p3 = select_ln101_73_fu_2486_p3[32'd30];

assign tmp_195_fu_2530_p3 = sub_ln703_26_fu_2502_p2[32'd30];

assign tmp_196_fu_2538_p3 = add_ln203_25_fu_2508_p2[32'd30];

assign tmp_fu_2437_p4 = {{add_ln703_25_fu_2417_p2[30:26]}};

assign tmp_s_fu_2447_p4 = {{sub_ln203_25_fu_2427_p2[30:26]}};

assign trunc_ln1333_14_fu_868_p4 = {{select_ln101_19_fu_860_p3[30:8]}};

assign trunc_ln1333_1_fu_284_p4 = {{select_ln101_fu_260_p3[30:1]}};

assign trunc_ln1333_22_fu_1196_p4 = {{select_ln101_31_fu_1188_p3[30:12]}};

assign trunc_ln1333_28_fu_1545_p4 = {{select_ln101_40_fu_1537_p3[30:15]}};

assign trunc_ln1333_36_fu_1897_p4 = {{select_ln101_52_fu_1889_p3[30:19]}};

assign trunc_ln1333_42_fu_2149_p4 = {{select_ln101_61_fu_2141_p3[30:22]}};

assign trunc_ln1333_9_fu_592_p4 = {{select_ln101_10_fu_584_p3[30:5]}};

assign trunc_ln_fu_270_p4 = {{select_ln101_1_fu_265_p3[30:1]}};

assign x_V_read_cast_fu_222_p1 = $signed(x_V_read_int_reg);

assign y_V_read_cast1_fu_218_p0 = y_V_read_int_reg;

assign y_V_read_cast1_fu_218_p1 = y_V_read_cast1_fu_218_p0;

always @ (posedge ap_clk) begin
    add_ln101_3_reg_2852[0] <= 1'b0;
    add_ln101_4_reg_2886[0] <= 1'b0;
    add_ln101_4_reg_2886_pp0_iter7_reg[0] <= 1'b0;
    add_ln101_4_reg_2886_pp0_iter8_reg[0] <= 1'b0;
    add_ln101_4_reg_2886_pp0_iter9_reg[0] <= 1'b0;
    add_ln101_4_reg_2886_pp0_iter10_reg[0] <= 1'b0;
    add_ln101_4_reg_2886_pp0_iter11_reg[0] <= 1'b0;
    add_ln101_4_reg_2886_pp0_iter12_reg[0] <= 1'b0;
    add_ln101_4_reg_2886_pp0_iter13_reg[0] <= 1'b0;
    add_ln101_6_reg_2945[0] <= 1'b0;
    add_ln101_6_reg_2945_pp0_iter9_reg[0] <= 1'b0;
    add_ln101_6_reg_2945_pp0_iter10_reg[0] <= 1'b0;
    add_ln101_6_reg_2945_pp0_iter11_reg[0] <= 1'b0;
    add_ln101_6_reg_2945_pp0_iter12_reg[0] <= 1'b0;
    add_ln101_9_reg_3062[0] <= 1'b0;
    add_ln101_2_reg_3096[0] <= 1'b0;
    add_ln101_11_reg_3101[0] <= 1'b0;
    add_ln101_12_reg_3127[0] <= 1'b0;
    add_ln101_12_reg_3127_pp0_iter15_reg[0] <= 1'b0;
    add_ln101_12_reg_3127_pp0_iter16_reg[0] <= 1'b0;
    add_ln101_12_reg_3127_pp0_iter17_reg[0] <= 1'b0;
    add_ln101_12_reg_3127_pp0_iter18_reg[0] <= 1'b0;
    add_ln101_12_reg_3127_pp0_iter19_reg[0] <= 1'b0;
    add_ln101_12_reg_3127_pp0_iter20_reg[0] <= 1'b0;
    add_ln101_12_reg_3127_pp0_iter21_reg[0] <= 1'b0;
    add_ln101_12_reg_3127_pp0_iter22_reg[0] <= 1'b0;
    add_ln101_12_reg_3127_pp0_iter23_reg[0] <= 1'b0;
    add_ln101_12_reg_3127_pp0_iter24_reg[0] <= 1'b0;
    add_ln101_12_reg_3127_pp0_iter25_reg[0] <= 1'b0;
    add_ln101_12_reg_3127_pp0_iter26_reg[0] <= 1'b0;
    add_ln101_12_reg_3127_pp0_iter27_reg[0] <= 1'b0;
    add_ln101_13_reg_3165[0] <= 1'b0;
    add_ln101_14_reg_3203[0] <= 1'b0;
    add_ln101_14_reg_3203_pp0_iter17_reg[0] <= 1'b0;
    add_ln101_14_reg_3203_pp0_iter18_reg[0] <= 1'b0;
    add_ln101_14_reg_3203_pp0_iter19_reg[0] <= 1'b0;
    add_ln101_14_reg_3203_pp0_iter20_reg[0] <= 1'b0;
    add_ln101_14_reg_3203_pp0_iter21_reg[0] <= 1'b0;
    add_ln101_14_reg_3203_pp0_iter22_reg[0] <= 1'b0;
    add_ln101_14_reg_3203_pp0_iter23_reg[0] <= 1'b0;
    add_ln101_14_reg_3203_pp0_iter24_reg[0] <= 1'b0;
    add_ln101_14_reg_3203_pp0_iter25_reg[0] <= 1'b0;
    add_ln101_14_reg_3203_pp0_iter26_reg[0] <= 1'b0;
    add_ln101_14_reg_3203_pp0_iter27_reg[0] <= 1'b0;
    add_ln101_16_reg_3291[0] <= 1'b0;
    add_ln101_16_reg_3291_pp0_iter20_reg[0] <= 1'b0;
    add_ln101_16_reg_3291_pp0_iter21_reg[0] <= 1'b0;
    add_ln101_16_reg_3291_pp0_iter22_reg[0] <= 1'b0;
    add_ln101_16_reg_3291_pp0_iter23_reg[0] <= 1'b0;
    add_ln101_16_reg_3291_pp0_iter24_reg[0] <= 1'b0;
    add_ln101_16_reg_3291_pp0_iter25_reg[0] <= 1'b0;
    add_ln101_16_reg_3291_pp0_iter26_reg[0] <= 1'b0;
    add_ln101_19_reg_3379[0] <= 1'b0;
    add_ln101_19_reg_3379_pp0_iter23_reg[0] <= 1'b0;
    add_ln101_19_reg_3379_pp0_iter24_reg[0] <= 1'b0;
    add_ln101_19_reg_3379_pp0_iter25_reg[0] <= 1'b0;
    add_ln101_19_reg_3379_pp0_iter26_reg[0] <= 1'b0;
    select_ln101_66_reg_3461[0] <= 1'b0;
    select_ln101_66_reg_3461[5:2] <= 4'b0000;
    add_ln101_22_reg_3466[0] <= 1'b0;
    select_ln101_80_cast_reg_3471[0] <= 1'b0;
    select_ln101_80_cast_reg_3471[29:2] <= 28'b0110111110010010000000011010;
    select_ln101_80_cast_reg_3471_pp0_iter27_reg[0] <= 1'b0;
    select_ln101_80_cast_reg_3471_pp0_iter27_reg[29:2] <= 28'b0110111110010010000000011010;
    add_ln101_17_reg_3476[0] <= 1'b0;
    add_ln101_24_reg_3481[0] <= 1'b0;
end

endmodule //cordic_circ_apfixed
