#create_clock -period 2.000 [get_ports aclk]
#create_clock -period 4.000 -name s_axi_csr_aclk -waveform {0.000 2.000} [get_ports s_axi_csr_aclk]
create_clock -period 4.000 [get_ports s_axi_csr_aclk]
#set_false_path -from [get_clocks {aclk}] -to [get_clocks {s_axi_csr_aclk}]
#set_false_path -from [get_clocks {s_axi_csr_aclk}] -to [get_clocks {aclk}]
