# -*- python -*-
#
# Build cmigitsDaemon
#

tools = Split('''
hcrpmc730client
boost_program_options
cmigits
doxygen
motioncontrol
qt4
QFunctionWrapper
QXmlRpcServerAbyss
rapradar
xmlrpc_client++
''')

env = Environment(tools = ['default'] + tools)
env.EnableQt4Modules(['QtCore', 'QtGui'])

sources = Split('''
ApsControl.cpp
HcrMonitorStatus.cpp
HcrMonitor.cpp
TransmitControl.cpp
''')

headers = Split('''
ApsControl.h
HcrMonitorStatus.h
TransmitControl.h
''')

daemon = env.Program('HcrMonitor', sources)
Default(daemon)

doxref = env.Apidocs(sources + headers)
Default(doxref)