# -*- python -*-
#
# Build cmigitsDaemon
#

tools = Split('''
hcrpmc730client
boost_program_options
doxygen
hcrmonitor
motioncontrol
qt4
rapradar
QFunctionWrapper
QXmlRpcServerAbyss
xmlrpc_client++
''')

env = Environment(tools = ['default'] + tools)
env.EnableQt4Modules(['QtCore', 'QtXml'])

sources = Split('''
    HcrMonitor.cpp
    MaxPowerClient.cpp
''')

headers = Split('''
    MaxPowerClient.h
''')

daemon = env.Program('HcrMonitor', sources)
Default(daemon)
