// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module scheduler_parser (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_ready,
        ap_done,
        ap_continue,
        ap_idle,
        start_out,
        start_write,
        cfg_pulse_sequence_s,
        cfg_pulse_sequence_l,
        cfg_num_pulses_to_ex,
        cfg_decimation,
        cfg_pulse_sequence_p_address0,
        cfg_pulse_sequence_p_ce0,
        cfg_pulse_sequence_p_q0,
        cfg_pulse_sequence_p_2_address0,
        cfg_pulse_sequence_p_2_ce0,
        cfg_pulse_sequence_p_2_q0,
        cfg_pulse_sequence_n_address0,
        cfg_pulse_sequence_n_ce0,
        cfg_pulse_sequence_n_q0,
        cfg_pulse_sequence_b_address0,
        cfg_pulse_sequence_b_ce0,
        cfg_pulse_sequence_b_q0,
        cfg_pulse_sequence_c_address0,
        cfg_pulse_sequence_c_ce0,
        cfg_pulse_sequence_c_q0,
        cfg_pulse_sequence_f_address0,
        cfg_pulse_sequence_f_ce0,
        cfg_pulse_sequence_f_q0,
        cfg_pulse_sequence_f_3_address0,
        cfg_pulse_sequence_f_3_ce0,
        cfg_pulse_sequence_f_3_q0,
        cfg_pulse_sequence_f_4_address0,
        cfg_pulse_sequence_f_4_ce0,
        cfg_pulse_sequence_f_4_q0,
        cfg_pulse_sequence_t_address0,
        cfg_pulse_sequence_t_ce0,
        cfg_pulse_sequence_t_q0,
        cfg_pulse_sequence_t_16_address0,
        cfg_pulse_sequence_t_16_ce0,
        cfg_pulse_sequence_t_16_q0,
        cfg_pulse_sequence_t_17_address0,
        cfg_pulse_sequence_t_17_ce0,
        cfg_pulse_sequence_t_17_q0,
        cfg_pulse_sequence_t_18_address0,
        cfg_pulse_sequence_t_18_ce0,
        cfg_pulse_sequence_t_18_q0,
        cfg_pulse_sequence_t_19_address0,
        cfg_pulse_sequence_t_19_ce0,
        cfg_pulse_sequence_t_19_q0,
        cfg_pulse_sequence_t_20_address0,
        cfg_pulse_sequence_t_20_ce0,
        cfg_pulse_sequence_t_20_q0,
        cfg_pulse_sequence_t_21_address0,
        cfg_pulse_sequence_t_21_ce0,
        cfg_pulse_sequence_t_21_q0,
        cfg_pulse_sequence_t_22_address0,
        cfg_pulse_sequence_t_22_ce0,
        cfg_pulse_sequence_t_22_q0,
        cfg_pulse_sequence_t_23_address0,
        cfg_pulse_sequence_t_23_ce0,
        cfg_pulse_sequence_t_23_q0,
        cfg_pulse_sequence_t_24_address0,
        cfg_pulse_sequence_t_24_ce0,
        cfg_pulse_sequence_t_24_q0,
        cfg_pulse_sequence_t_25_address0,
        cfg_pulse_sequence_t_25_ce0,
        cfg_pulse_sequence_t_25_q0,
        cfg_pulse_sequence_t_26_address0,
        cfg_pulse_sequence_t_26_ce0,
        cfg_pulse_sequence_t_26_q0,
        cfg_pulse_sequence_t_27_address0,
        cfg_pulse_sequence_t_27_ce0,
        cfg_pulse_sequence_t_27_q0,
        cfg_pulse_sequence_t_28_address0,
        cfg_pulse_sequence_t_28_ce0,
        cfg_pulse_sequence_t_28_q0,
        cfg_pulse_sequence_t_29_address0,
        cfg_pulse_sequence_t_29_ce0,
        cfg_pulse_sequence_t_29_q0,
        cfg_pulse_sequence_t_30_address0,
        cfg_pulse_sequence_t_30_ce0,
        cfg_pulse_sequence_t_30_q0,
        cfg_filter_coefs_ch0_address0,
        cfg_filter_coefs_ch0_ce0,
        cfg_filter_coefs_ch0_q0,
        cfg_filter_coefs_ch1_address0,
        cfg_filter_coefs_ch1_ce0,
        cfg_filter_coefs_ch1_q0,
        cfg_filter_coefs_ch2_address0,
        cfg_filter_coefs_ch2_ce0,
        cfg_filter_coefs_ch2_q0,
        coef_ch0_V_V_TDATA,
        coef_ch0_V_V_TVALID,
        coef_ch0_V_V_TREADY,
        coef_ch1_V_V_TDATA,
        coef_ch1_V_V_TVALID,
        coef_ch1_V_V_TREADY,
        coef_ch2_V_V_TDATA,
        coef_ch2_V_V_TVALID,
        coef_ch2_V_V_TREADY,
        pulse_queue_0_V_din,
        pulse_queue_0_V_full_n,
        pulse_queue_0_V_write,
        pulse_queue_1_V_din,
        pulse_queue_1_V_full_n,
        pulse_queue_1_V_write,
        pulse_queue_2_V_din,
        pulse_queue_2_V_full_n,
        pulse_queue_2_V_write,
        pulse_queue_s_V_din,
        pulse_queue_s_V_full_n,
        pulse_queue_s_V_write
);

parameter    ap_ST_fsm_state1 = 51'd1;
parameter    ap_ST_fsm_state2 = 51'd2;
parameter    ap_ST_fsm_state3 = 51'd4;
parameter    ap_ST_fsm_state4 = 51'd8;
parameter    ap_ST_fsm_state5 = 51'd16;
parameter    ap_ST_fsm_state6 = 51'd32;
parameter    ap_ST_fsm_state7 = 51'd64;
parameter    ap_ST_fsm_state8 = 51'd128;
parameter    ap_ST_fsm_state9 = 51'd256;
parameter    ap_ST_fsm_state10 = 51'd512;
parameter    ap_ST_fsm_state11 = 51'd1024;
parameter    ap_ST_fsm_state12 = 51'd2048;
parameter    ap_ST_fsm_state13 = 51'd4096;
parameter    ap_ST_fsm_state14 = 51'd8192;
parameter    ap_ST_fsm_state15 = 51'd16384;
parameter    ap_ST_fsm_state16 = 51'd32768;
parameter    ap_ST_fsm_state17 = 51'd65536;
parameter    ap_ST_fsm_state18 = 51'd131072;
parameter    ap_ST_fsm_state19 = 51'd262144;
parameter    ap_ST_fsm_state20 = 51'd524288;
parameter    ap_ST_fsm_state21 = 51'd1048576;
parameter    ap_ST_fsm_state22 = 51'd2097152;
parameter    ap_ST_fsm_state23 = 51'd4194304;
parameter    ap_ST_fsm_state24 = 51'd8388608;
parameter    ap_ST_fsm_state25 = 51'd16777216;
parameter    ap_ST_fsm_state26 = 51'd33554432;
parameter    ap_ST_fsm_state27 = 51'd67108864;
parameter    ap_ST_fsm_state28 = 51'd134217728;
parameter    ap_ST_fsm_state29 = 51'd268435456;
parameter    ap_ST_fsm_state30 = 51'd536870912;
parameter    ap_ST_fsm_state31 = 51'd1073741824;
parameter    ap_ST_fsm_state32 = 51'd2147483648;
parameter    ap_ST_fsm_state33 = 51'd4294967296;
parameter    ap_ST_fsm_state34 = 51'd8589934592;
parameter    ap_ST_fsm_state35 = 51'd17179869184;
parameter    ap_ST_fsm_state36 = 51'd34359738368;
parameter    ap_ST_fsm_state37 = 51'd68719476736;
parameter    ap_ST_fsm_state38 = 51'd137438953472;
parameter    ap_ST_fsm_state39 = 51'd274877906944;
parameter    ap_ST_fsm_state40 = 51'd549755813888;
parameter    ap_ST_fsm_state41 = 51'd1099511627776;
parameter    ap_ST_fsm_state42 = 51'd2199023255552;
parameter    ap_ST_fsm_state43 = 51'd4398046511104;
parameter    ap_ST_fsm_state44 = 51'd8796093022208;
parameter    ap_ST_fsm_state45 = 51'd17592186044416;
parameter    ap_ST_fsm_state46 = 51'd35184372088832;
parameter    ap_ST_fsm_state47 = 51'd70368744177664;
parameter    ap_ST_fsm_state48 = 51'd140737488355328;
parameter    ap_ST_fsm_state49 = 51'd281474976710656;
parameter    ap_ST_fsm_state50 = 51'd562949953421312;
parameter    ap_ST_fsm_state51 = 51'd1125899906842624;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_ready;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   start_out;
output   start_write;
input  [7:0] cfg_pulse_sequence_s;
input  [7:0] cfg_pulse_sequence_l;
input  [31:0] cfg_num_pulses_to_ex;
input  [31:0] cfg_decimation;
output  [4:0] cfg_pulse_sequence_p_address0;
output   cfg_pulse_sequence_p_ce0;
input  [31:0] cfg_pulse_sequence_p_q0;
output  [4:0] cfg_pulse_sequence_p_2_address0;
output   cfg_pulse_sequence_p_2_ce0;
input  [31:0] cfg_pulse_sequence_p_2_q0;
output  [4:0] cfg_pulse_sequence_n_address0;
output   cfg_pulse_sequence_n_ce0;
input  [31:0] cfg_pulse_sequence_n_q0;
output  [4:0] cfg_pulse_sequence_b_address0;
output   cfg_pulse_sequence_b_ce0;
input  [31:0] cfg_pulse_sequence_b_q0;
output  [4:0] cfg_pulse_sequence_c_address0;
output   cfg_pulse_sequence_c_ce0;
input  [31:0] cfg_pulse_sequence_c_q0;
output  [4:0] cfg_pulse_sequence_f_address0;
output   cfg_pulse_sequence_f_ce0;
input  [31:0] cfg_pulse_sequence_f_q0;
output  [4:0] cfg_pulse_sequence_f_3_address0;
output   cfg_pulse_sequence_f_3_ce0;
input  [31:0] cfg_pulse_sequence_f_3_q0;
output  [4:0] cfg_pulse_sequence_f_4_address0;
output   cfg_pulse_sequence_f_4_ce0;
input  [31:0] cfg_pulse_sequence_f_4_q0;
output  [4:0] cfg_pulse_sequence_t_address0;
output   cfg_pulse_sequence_t_ce0;
input  [31:0] cfg_pulse_sequence_t_q0;
output  [4:0] cfg_pulse_sequence_t_16_address0;
output   cfg_pulse_sequence_t_16_ce0;
input  [31:0] cfg_pulse_sequence_t_16_q0;
output  [4:0] cfg_pulse_sequence_t_17_address0;
output   cfg_pulse_sequence_t_17_ce0;
input  [31:0] cfg_pulse_sequence_t_17_q0;
output  [4:0] cfg_pulse_sequence_t_18_address0;
output   cfg_pulse_sequence_t_18_ce0;
input  [31:0] cfg_pulse_sequence_t_18_q0;
output  [4:0] cfg_pulse_sequence_t_19_address0;
output   cfg_pulse_sequence_t_19_ce0;
input  [31:0] cfg_pulse_sequence_t_19_q0;
output  [4:0] cfg_pulse_sequence_t_20_address0;
output   cfg_pulse_sequence_t_20_ce0;
input  [31:0] cfg_pulse_sequence_t_20_q0;
output  [4:0] cfg_pulse_sequence_t_21_address0;
output   cfg_pulse_sequence_t_21_ce0;
input  [31:0] cfg_pulse_sequence_t_21_q0;
output  [4:0] cfg_pulse_sequence_t_22_address0;
output   cfg_pulse_sequence_t_22_ce0;
input  [31:0] cfg_pulse_sequence_t_22_q0;
output  [4:0] cfg_pulse_sequence_t_23_address0;
output   cfg_pulse_sequence_t_23_ce0;
input  [31:0] cfg_pulse_sequence_t_23_q0;
output  [4:0] cfg_pulse_sequence_t_24_address0;
output   cfg_pulse_sequence_t_24_ce0;
input  [31:0] cfg_pulse_sequence_t_24_q0;
output  [4:0] cfg_pulse_sequence_t_25_address0;
output   cfg_pulse_sequence_t_25_ce0;
input  [31:0] cfg_pulse_sequence_t_25_q0;
output  [4:0] cfg_pulse_sequence_t_26_address0;
output   cfg_pulse_sequence_t_26_ce0;
input  [31:0] cfg_pulse_sequence_t_26_q0;
output  [4:0] cfg_pulse_sequence_t_27_address0;
output   cfg_pulse_sequence_t_27_ce0;
input  [31:0] cfg_pulse_sequence_t_27_q0;
output  [4:0] cfg_pulse_sequence_t_28_address0;
output   cfg_pulse_sequence_t_28_ce0;
input  [31:0] cfg_pulse_sequence_t_28_q0;
output  [4:0] cfg_pulse_sequence_t_29_address0;
output   cfg_pulse_sequence_t_29_ce0;
input  [31:0] cfg_pulse_sequence_t_29_q0;
output  [4:0] cfg_pulse_sequence_t_30_address0;
output   cfg_pulse_sequence_t_30_ce0;
input  [31:0] cfg_pulse_sequence_t_30_q0;
output  [7:0] cfg_filter_coefs_ch0_address0;
output   cfg_filter_coefs_ch0_ce0;
input  [31:0] cfg_filter_coefs_ch0_q0;
output  [7:0] cfg_filter_coefs_ch1_address0;
output   cfg_filter_coefs_ch1_ce0;
input  [31:0] cfg_filter_coefs_ch1_q0;
output  [7:0] cfg_filter_coefs_ch2_address0;
output   cfg_filter_coefs_ch2_ce0;
input  [31:0] cfg_filter_coefs_ch2_q0;
output  [23:0] coef_ch0_V_V_TDATA;
output   coef_ch0_V_V_TVALID;
input   coef_ch0_V_V_TREADY;
output  [23:0] coef_ch1_V_V_TDATA;
output   coef_ch1_V_V_TVALID;
input   coef_ch1_V_V_TREADY;
output  [23:0] coef_ch2_V_V_TDATA;
output   coef_ch2_V_V_TVALID;
input   coef_ch2_V_V_TREADY;
output  [840:0] pulse_queue_0_V_din;
input   pulse_queue_0_V_full_n;
output   pulse_queue_0_V_write;
output  [840:0] pulse_queue_1_V_din;
input   pulse_queue_1_V_full_n;
output   pulse_queue_1_V_write;
output  [840:0] pulse_queue_2_V_din;
input   pulse_queue_2_V_full_n;
output   pulse_queue_2_V_write;
output  [840:0] pulse_queue_s_V_din;
input   pulse_queue_s_V_full_n;
output   pulse_queue_s_V_write;

reg ap_done;
reg ap_idle;
reg cfg_pulse_sequence_p_ce0;
reg cfg_pulse_sequence_p_2_ce0;
reg cfg_pulse_sequence_n_ce0;
reg cfg_pulse_sequence_b_ce0;
reg cfg_pulse_sequence_c_ce0;
reg cfg_pulse_sequence_f_ce0;
reg cfg_pulse_sequence_f_3_ce0;
reg cfg_pulse_sequence_f_4_ce0;
reg cfg_pulse_sequence_t_ce0;
reg cfg_pulse_sequence_t_16_ce0;
reg cfg_pulse_sequence_t_17_ce0;
reg cfg_pulse_sequence_t_18_ce0;
reg cfg_pulse_sequence_t_19_ce0;
reg cfg_pulse_sequence_t_20_ce0;
reg cfg_pulse_sequence_t_21_ce0;
reg cfg_pulse_sequence_t_22_ce0;
reg cfg_pulse_sequence_t_23_ce0;
reg cfg_pulse_sequence_t_24_ce0;
reg cfg_pulse_sequence_t_25_ce0;
reg cfg_pulse_sequence_t_26_ce0;
reg cfg_pulse_sequence_t_27_ce0;
reg cfg_pulse_sequence_t_28_ce0;
reg cfg_pulse_sequence_t_29_ce0;
reg cfg_pulse_sequence_t_30_ce0;
reg cfg_filter_coefs_ch0_ce0;
reg cfg_filter_coefs_ch1_ce0;
reg cfg_filter_coefs_ch2_ce0;
reg[840:0] pulse_queue_0_V_din;
reg pulse_queue_0_V_write;
reg[840:0] pulse_queue_1_V_din;
reg pulse_queue_1_V_write;
reg[840:0] pulse_queue_2_V_din;
reg pulse_queue_2_V_write;
reg[840:0] pulse_queue_s_V_din;
reg pulse_queue_s_V_write;

reg    real_start;
reg    real_start_status_reg;
reg    internal_ap_ready;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [50:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    start_once_reg;
reg    start_control_reg;
reg   [23:0] coef_ch0_V_V_1_data_in;
reg   [23:0] coef_ch0_V_V_1_data_out;
reg    coef_ch0_V_V_1_vld_in;
wire    coef_ch0_V_V_1_vld_out;
wire    coef_ch0_V_V_1_ack_in;
wire    coef_ch0_V_V_1_ack_out;
reg   [23:0] coef_ch0_V_V_1_payload_A;
reg   [23:0] coef_ch0_V_V_1_payload_B;
reg    coef_ch0_V_V_1_sel_rd;
reg    coef_ch0_V_V_1_sel_wr;
wire    coef_ch0_V_V_1_sel;
wire    coef_ch0_V_V_1_load_A;
wire    coef_ch0_V_V_1_load_B;
reg   [1:0] coef_ch0_V_V_1_state;
wire    coef_ch0_V_V_1_state_cmp_full;
reg   [23:0] coef_ch1_V_V_1_data_in;
reg   [23:0] coef_ch1_V_V_1_data_out;
reg    coef_ch1_V_V_1_vld_in;
wire    coef_ch1_V_V_1_vld_out;
wire    coef_ch1_V_V_1_ack_in;
wire    coef_ch1_V_V_1_ack_out;
reg   [23:0] coef_ch1_V_V_1_payload_A;
reg   [23:0] coef_ch1_V_V_1_payload_B;
reg    coef_ch1_V_V_1_sel_rd;
reg    coef_ch1_V_V_1_sel_wr;
wire    coef_ch1_V_V_1_sel;
wire    coef_ch1_V_V_1_load_A;
wire    coef_ch1_V_V_1_load_B;
reg   [1:0] coef_ch1_V_V_1_state;
wire    coef_ch1_V_V_1_state_cmp_full;
reg   [23:0] coef_ch2_V_V_1_data_in;
reg   [23:0] coef_ch2_V_V_1_data_out;
reg    coef_ch2_V_V_1_vld_in;
wire    coef_ch2_V_V_1_vld_out;
wire    coef_ch2_V_V_1_ack_in;
wire    coef_ch2_V_V_1_ack_out;
reg   [23:0] coef_ch2_V_V_1_payload_A;
reg   [23:0] coef_ch2_V_V_1_payload_B;
reg    coef_ch2_V_V_1_sel_rd;
reg    coef_ch2_V_V_1_sel_wr;
wire    coef_ch2_V_V_1_sel;
wire    coef_ch2_V_V_1_load_A;
wire    coef_ch2_V_V_1_load_B;
reg   [1:0] coef_ch2_V_V_1_state;
wire    coef_ch2_V_V_1_state_cmp_full;
reg    coef_ch0_V_V_TDATA_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond1_fu_770_p2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    coef_ch1_V_V_TDATA_blk_n;
reg    coef_ch2_V_V_TDATA_blk_n;
reg    pulse_queue_0_V_blk_n;
wire    ap_CS_fsm_state49;
wire    ap_CS_fsm_state51;
reg    pulse_queue_1_V_blk_n;
reg    pulse_queue_2_V_blk_n;
reg    pulse_queue_s_V_blk_n;
reg    ap_block_state1;
wire   [31:0] cfg_pulse_sequence_l_1_fu_762_p1;
reg   [31:0] cfg_pulse_sequence_l_1_reg_1230;
wire   [31:0] cfg_pulse_sequence_s_1_fu_766_p1;
reg   [31:0] cfg_pulse_sequence_s_1_reg_1235;
wire   [2:0] set_fu_776_p2;
reg   [2:0] set_reg_1243;
reg    ap_block_state2_io;
wire   [23:0] tmp_V_fu_782_p1;
wire   [8:0] tmp_18_fu_814_p2;
reg   [8:0] tmp_18_reg_1285;
reg    ap_block_state3_io;
wire   [5:0] coef_1_fu_826_p2;
reg   [5:0] coef_1_reg_1293;
wire    ap_CS_fsm_state4;
wire   [8:0] tmp_19_fu_842_p2;
reg   [8:0] tmp_19_reg_1298;
wire   [0:0] exitcond2_fu_820_p2;
wire    ap_CS_fsm_state5;
wire   [23:0] tmp_V_1_fu_853_p1;
reg    ap_block_state6_io;
wire   [23:0] tmp_V_2_fu_858_p1;
wire   [23:0] tmp_V_3_fu_863_p1;
reg   [31:0] seq_idx_load_reg_1333;
wire    ap_CS_fsm_state8;
wire   [0:0] tmp_5_fu_871_p2;
reg   [0:0] tmp_5_reg_1339;
reg   [31:0] cfg_pulse_sequence_p_6_reg_1463;
wire    ap_CS_fsm_state9;
reg   [31:0] pulse_definition_num_reg_1470;
reg   [31:0] pulse_definition_blo_reg_1478;
reg   [31:0] pulse_definition_con_reg_1483;
reg   [31:0] pulse_definition_fil_reg_1490;
reg   [31:0] pulse_definition_fil_1_reg_1497;
reg   [31:0] pulse_definition_fil_2_reg_1504;
reg   [31:0] pulse_definition_tim_reg_1511;
reg   [31:0] pulse_definition_tim_1_reg_1518;
reg   [31:0] pulse_definition_tim_2_reg_1526;
reg   [31:0] pulse_definition_tim_3_reg_1533;
reg   [31:0] pulse_definition_tim_4_reg_1540;
reg   [31:0] pulse_definition_tim_5_reg_1548;
reg   [31:0] pulse_definition_tim_6_reg_1555;
reg   [31:0] pulse_definition_tim_7_reg_1562;
reg   [31:0] pulse_definition_tim_8_reg_1569;
reg   [31:0] pulse_definition_tim_9_reg_1576;
reg   [31:0] pulse_definition_tim_10_reg_1583;
reg   [31:0] pulse_definition_tim_11_reg_1590;
reg   [31:0] pulse_definition_tim_12_reg_1597;
reg   [31:0] pulse_definition_tim_13_reg_1604;
reg   [31:0] pulse_definition_tim_14_reg_1611;
reg   [31:0] pulse_definition_tim_15_reg_1618;
wire   [7:0] pulse_sequence_index_fu_912_p2;
reg   [7:0] pulse_sequence_index_reg_1625;
wire   [31:0] tmp_2_fu_917_p2;
reg   [31:0] tmp_2_reg_1632;
wire   [31:0] totalTime_fu_923_p2;
reg   [31:0] totalTime_reg_1637;
wire   [31:0] totalTime_2_fu_929_p2;
reg   [31:0] totalTime_2_reg_1643;
wire   [31:0] pulse_rep_fu_940_p2;
reg   [31:0] pulse_rep_reg_1652;
wire    ap_CS_fsm_state10;
wire   [31:0] tmp_def_block_post_t_fu_951_p3;
reg   [31:0] tmp_def_block_post_t_reg_1657;
wire   [0:0] tmp_9_fu_935_p2;
wire   [31:0] pulse_definition_prt_q0;
reg   [31:0] pulse_definition_prt_4_reg_1669;
wire    ap_CS_fsm_state11;
wire   [31:0] tmp_16_fu_983_p2;
reg   [31:0] tmp_16_reg_1680;
wire    ap_CS_fsm_state12;
wire   [31:0] tmp_19_2_fu_998_p2;
reg   [31:0] tmp_19_2_reg_1685;
wire   [31:0] grp_fu_1003_p2;
reg   [31:0] ns_reg_1690;
wire    ap_CS_fsm_state48;
wire   [31:0] grp_fu_1007_p2;
reg   [31:0] ns_2_reg_1696;
wire   [7:0] staggered_prt_index_2_fu_1174_p2;
reg   [7:0] staggered_prt_index_2_reg_1705;
reg    ap_block_state49;
wire   [0:0] or_cond_fu_1168_p2;
wire   [7:0] staggered_prt_index_1_fu_1212_p3;
wire    ap_CS_fsm_state50;
reg   [0:0] pulse_definition_prt_address0;
reg    pulse_definition_prt_ce0;
reg    pulse_definition_prt_we0;
reg   [0:0] pulse_definition_prt_address1;
reg    pulse_definition_prt_ce1;
reg    pulse_definition_prt_we1;
wire   [31:0] pulse_definition_prt_q1;
reg   [2:0] val_assign_reg_710;
reg   [5:0] coef_reg_722;
reg    ap_block_state7_io;
reg   [7:0] staggered_prt_index_reg_733;
reg   [31:0] pulse_pulse_rep_reg_745;
wire  signed [63:0] tmp_20_cast_fu_847_p1;
wire   [63:0] tmp_7_fu_881_p1;
wire   [63:0] tmp_8_fu_958_p1;
wire   [63:0] tmp_13_fu_1180_p1;
reg    ap_block_state51;
wire   [840:0] tmp170_fu_1041_p29;
wire   [840:0] tmp_122_fu_1077_p29;
wire   [840:0] tmp_3488_fu_1114_p29;
reg   [31:0] seq_idx_fu_260;
wire   [31:0] seq_idx_1_fu_963_p2;
reg   [31:0] num_pulses_scheduled_1_fu_264;
wire   [31:0] num_pulses_scheduled_fu_1150_p2;
reg   [31:0] tmp_num_samples_fu_268;
wire   [31:0] pulse_num_samples_1_fu_1034_p3;
wire   [6:0] tmp_1_fu_802_p3;
wire   [8:0] tmp_4_fu_794_p3;
wire   [8:0] p_shl1_cast_fu_810_p1;
wire   [5:0] tmp_s_fu_832_p2;
wire   [8:0] tmp_1_cast_fu_838_p1;
wire   [31:0] tmp_6_fu_876_p2;
wire   [7:0] tmp_fu_909_p1;
wire   [0:0] tmp_3_fu_946_p2;
wire   [0:0] tmp_15_fu_973_p2;
wire   [31:0] pulse_definition_prt_5_fu_977_p3;
wire   [0:0] tmp_17_2_fu_988_p2;
wire   [31:0] pulse_definition_prt_6_fu_992_p3;
wire    ap_CS_fsm_state13;
wire   [0:0] tmp_17_fu_1017_p2;
wire   [0:0] tmp_20_2_fu_1029_p2;
wire   [31:0] pulse_num_samples_fu_1022_p3;
wire   [0:0] tmp_10_fu_1156_p2;
wire   [0:0] tmp_11_fu_1162_p2;
wire   [0:0] tmp_12_fu_1195_p2;
wire   [0:0] tmp_14_fu_1200_p2;
wire   [0:0] sel_tmp_fu_1206_p2;
reg    grp_fu_1003_ap_start;
wire    grp_fu_1003_ap_done;
reg    grp_fu_1007_ap_start;
wire    grp_fu_1007_ap_done;
reg   [50:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 real_start_status_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 51'd1;
#0 start_once_reg = 1'b0;
#0 start_control_reg = 1'b0;
#0 coef_ch0_V_V_1_sel_rd = 1'b0;
#0 coef_ch0_V_V_1_sel_wr = 1'b0;
#0 coef_ch0_V_V_1_state = 2'd0;
#0 coef_ch1_V_V_1_sel_rd = 1'b0;
#0 coef_ch1_V_V_1_sel_wr = 1'b0;
#0 coef_ch1_V_V_1_state = 2'd0;
#0 coef_ch2_V_V_1_sel_rd = 1'b0;
#0 coef_ch2_V_V_1_sel_wr = 1'b0;
#0 coef_ch2_V_V_1_state = 2'd0;
end

scheduler_parser_bkb #(
    .DataWidth( 32 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
pulse_definition_prt_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pulse_definition_prt_address0),
    .ce0(pulse_definition_prt_ce0),
    .we0(pulse_definition_prt_we0),
    .d0(cfg_pulse_sequence_p_q0),
    .q0(pulse_definition_prt_q0),
    .address1(pulse_definition_prt_address1),
    .ce1(pulse_definition_prt_ce1),
    .we1(pulse_definition_prt_we1),
    .d1(cfg_pulse_sequence_p_2_q0),
    .q1(pulse_definition_prt_q1)
);

hcr_controller_udcud #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
hcr_controller_udcud_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_1003_ap_start),
    .done(grp_fu_1003_ap_done),
    .din0(tmp_16_reg_1680),
    .din1(cfg_decimation),
    .ce(1'b1),
    .dout(grp_fu_1003_p2)
);

hcr_controller_udcud #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
hcr_controller_udcud_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_1007_ap_start),
    .done(grp_fu_1007_ap_done),
    .din0(tmp_19_2_reg_1685),
    .din1(cfg_decimation),
    .ce(1'b1),
    .dout(grp_fu_1007_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_continue)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state51) & ~((1'b0 == coef_ch0_V_V_1_ack_in) | (1'b0 == coef_ch1_V_V_1_ack_in) | (1'b0 == coef_ch2_V_V_1_ack_in) | (1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n)))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        coef_ch0_V_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == coef_ch0_V_V_1_ack_out) & (1'b1 == coef_ch0_V_V_1_vld_out))) begin
            coef_ch0_V_V_1_sel_rd <= ~coef_ch0_V_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        coef_ch0_V_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == coef_ch0_V_V_1_vld_in) & (1'b1 == coef_ch0_V_V_1_ack_in))) begin
            coef_ch0_V_V_1_sel_wr <= ~coef_ch0_V_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        coef_ch0_V_V_1_state <= 2'd0;
    end else begin
        if ((((1'b0 == coef_ch0_V_V_1_vld_in) & (1'b1 == coef_ch0_V_V_1_ack_out) & (coef_ch0_V_V_1_state == 2'd3)) | ((1'b0 == coef_ch0_V_V_1_vld_in) & (coef_ch0_V_V_1_state == 2'd2)))) begin
            coef_ch0_V_V_1_state <= 2'd2;
        end else if ((((1'b1 == coef_ch0_V_V_1_vld_in) & (1'b0 == coef_ch0_V_V_1_ack_out) & (coef_ch0_V_V_1_state == 2'd3)) | ((1'b0 == coef_ch0_V_V_1_ack_out) & (coef_ch0_V_V_1_state == 2'd1)))) begin
            coef_ch0_V_V_1_state <= 2'd1;
        end else if ((((1'b1 == coef_ch0_V_V_1_vld_in) & (coef_ch0_V_V_1_state == 2'd2)) | ((1'b1 == coef_ch0_V_V_1_ack_out) & (coef_ch0_V_V_1_state == 2'd1)) | ((coef_ch0_V_V_1_state == 2'd3) & ~((1'b1 == coef_ch0_V_V_1_vld_in) & (1'b0 == coef_ch0_V_V_1_ack_out)) & ~((1'b0 == coef_ch0_V_V_1_vld_in) & (1'b1 == coef_ch0_V_V_1_ack_out))))) begin
            coef_ch0_V_V_1_state <= 2'd3;
        end else begin
            coef_ch0_V_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        coef_ch1_V_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == coef_ch1_V_V_1_ack_out) & (1'b1 == coef_ch1_V_V_1_vld_out))) begin
            coef_ch1_V_V_1_sel_rd <= ~coef_ch1_V_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        coef_ch1_V_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == coef_ch1_V_V_1_vld_in) & (1'b1 == coef_ch1_V_V_1_ack_in))) begin
            coef_ch1_V_V_1_sel_wr <= ~coef_ch1_V_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        coef_ch1_V_V_1_state <= 2'd0;
    end else begin
        if ((((1'b0 == coef_ch1_V_V_1_vld_in) & (1'b1 == coef_ch1_V_V_1_ack_out) & (2'd3 == coef_ch1_V_V_1_state)) | ((1'b0 == coef_ch1_V_V_1_vld_in) & (2'd2 == coef_ch1_V_V_1_state)))) begin
            coef_ch1_V_V_1_state <= 2'd2;
        end else if ((((1'b1 == coef_ch1_V_V_1_vld_in) & (1'b0 == coef_ch1_V_V_1_ack_out) & (2'd3 == coef_ch1_V_V_1_state)) | ((1'b0 == coef_ch1_V_V_1_ack_out) & (2'd1 == coef_ch1_V_V_1_state)))) begin
            coef_ch1_V_V_1_state <= 2'd1;
        end else if ((((1'b1 == coef_ch1_V_V_1_vld_in) & (2'd2 == coef_ch1_V_V_1_state)) | ((1'b1 == coef_ch1_V_V_1_ack_out) & (2'd1 == coef_ch1_V_V_1_state)) | ((2'd3 == coef_ch1_V_V_1_state) & ~((1'b1 == coef_ch1_V_V_1_vld_in) & (1'b0 == coef_ch1_V_V_1_ack_out)) & ~((1'b0 == coef_ch1_V_V_1_vld_in) & (1'b1 == coef_ch1_V_V_1_ack_out))))) begin
            coef_ch1_V_V_1_state <= 2'd3;
        end else begin
            coef_ch1_V_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        coef_ch2_V_V_1_sel_rd <= 1'b0;
    end else begin
        if (((1'b1 == coef_ch2_V_V_1_ack_out) & (1'b1 == coef_ch2_V_V_1_vld_out))) begin
            coef_ch2_V_V_1_sel_rd <= ~coef_ch2_V_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        coef_ch2_V_V_1_sel_wr <= 1'b0;
    end else begin
        if (((1'b1 == coef_ch2_V_V_1_vld_in) & (1'b1 == coef_ch2_V_V_1_ack_in))) begin
            coef_ch2_V_V_1_sel_wr <= ~coef_ch2_V_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        coef_ch2_V_V_1_state <= 2'd0;
    end else begin
        if ((((1'b0 == coef_ch2_V_V_1_vld_in) & (1'b1 == coef_ch2_V_V_1_ack_out) & (2'd3 == coef_ch2_V_V_1_state)) | ((1'b0 == coef_ch2_V_V_1_vld_in) & (2'd2 == coef_ch2_V_V_1_state)))) begin
            coef_ch2_V_V_1_state <= 2'd2;
        end else if ((((1'b1 == coef_ch2_V_V_1_vld_in) & (1'b0 == coef_ch2_V_V_1_ack_out) & (2'd3 == coef_ch2_V_V_1_state)) | ((1'b0 == coef_ch2_V_V_1_ack_out) & (2'd1 == coef_ch2_V_V_1_state)))) begin
            coef_ch2_V_V_1_state <= 2'd1;
        end else if ((((1'b1 == coef_ch2_V_V_1_vld_in) & (2'd2 == coef_ch2_V_V_1_state)) | ((1'b1 == coef_ch2_V_V_1_ack_out) & (2'd1 == coef_ch2_V_V_1_state)) | ((2'd3 == coef_ch2_V_V_1_state) & ~((1'b1 == coef_ch2_V_V_1_vld_in) & (1'b0 == coef_ch2_V_V_1_ack_out)) & ~((1'b0 == coef_ch2_V_V_1_vld_in) & (1'b1 == coef_ch2_V_V_1_ack_out))))) begin
            coef_ch2_V_V_1_state <= 2'd3;
        end else begin
            coef_ch2_V_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        real_start_status_reg <= 1'b0;
    end else begin
        if ((start_full_n == 1'b1)) begin
            real_start_status_reg <= 1'b0;
        end else if (((1'b0 == start_full_n) & (1'b1 == internal_ap_ready))) begin
            real_start_status_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_control_reg <= 1'b0;
    end else begin
        if (((1'b1 == real_start) & ((1'b1 == internal_ap_ready) | (1'b0 == start_once_reg)))) begin
            start_control_reg <= 1'b1;
        end else if ((1'b1 == start_control_reg)) begin
            start_control_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if ((1'b1 == real_start)) begin
            start_once_reg <= 1'b1;
        end else if ((1'b0 == ap_start)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (ap_block_state7_io == 1'b0))) begin
        coef_reg_722 <= coef_1_reg_1293;
    end else if (((1'b1 == ap_CS_fsm_state3) & (ap_block_state3_io == 1'b0))) begin
        coef_reg_722 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state49) & ~((1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n)) & (1'd1 == or_cond_fu_1168_p2))) begin
        num_pulses_scheduled_1_fu_264 <= num_pulses_scheduled_fu_1150_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (ap_block_state2_io == 1'b0) & (1'd1 == exitcond1_fu_770_p2))) begin
        num_pulses_scheduled_1_fu_264 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        pulse_pulse_rep_reg_745 <= pulse_rep_reg_1652;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        pulse_pulse_rep_reg_745 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (1'd1 == tmp_5_reg_1339) & (1'd0 == tmp_9_fu_935_p2))) begin
        seq_idx_fu_260 <= seq_idx_1_fu_963_p2;
    end else if ((((1'b1 == ap_CS_fsm_state2) & (ap_block_state2_io == 1'b0) & (1'd1 == exitcond1_fu_770_p2)) | ((1'b1 == ap_CS_fsm_state8) & (1'd0 == tmp_5_fu_871_p2)))) begin
        seq_idx_fu_260 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        staggered_prt_index_reg_733 <= staggered_prt_index_1_fu_1212_p3;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        staggered_prt_index_reg_733 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'd1 == exitcond2_fu_820_p2))) begin
        val_assign_reg_710 <= set_reg_1243;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == real_start) | (ap_done_reg == 1'b1)))) begin
        val_assign_reg_710 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == real_start) | (ap_done_reg == 1'b1)))) begin
        cfg_pulse_sequence_l_1_reg_1230[7 : 0] <= cfg_pulse_sequence_l_1_fu_762_p1[7 : 0];
        cfg_pulse_sequence_s_1_reg_1235[7 : 0] <= cfg_pulse_sequence_s_1_fu_766_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        cfg_pulse_sequence_p_6_reg_1463 <= cfg_pulse_sequence_p_2_q0;
        pulse_definition_blo_reg_1478 <= cfg_pulse_sequence_b_q0;
        pulse_definition_con_reg_1483 <= cfg_pulse_sequence_c_q0;
        pulse_definition_fil_1_reg_1497 <= cfg_pulse_sequence_f_3_q0;
        pulse_definition_fil_2_reg_1504 <= cfg_pulse_sequence_f_4_q0;
        pulse_definition_fil_reg_1490 <= cfg_pulse_sequence_f_q0;
        pulse_definition_num_reg_1470 <= cfg_pulse_sequence_n_q0;
        pulse_definition_tim_10_reg_1583 <= cfg_pulse_sequence_t_25_q0;
        pulse_definition_tim_11_reg_1590 <= cfg_pulse_sequence_t_26_q0;
        pulse_definition_tim_12_reg_1597 <= cfg_pulse_sequence_t_27_q0;
        pulse_definition_tim_13_reg_1604 <= cfg_pulse_sequence_t_28_q0;
        pulse_definition_tim_14_reg_1611 <= cfg_pulse_sequence_t_29_q0;
        pulse_definition_tim_15_reg_1618 <= cfg_pulse_sequence_t_30_q0;
        pulse_definition_tim_1_reg_1518 <= cfg_pulse_sequence_t_16_q0;
        pulse_definition_tim_2_reg_1526 <= cfg_pulse_sequence_t_17_q0;
        pulse_definition_tim_3_reg_1533 <= cfg_pulse_sequence_t_18_q0;
        pulse_definition_tim_4_reg_1540 <= cfg_pulse_sequence_t_19_q0;
        pulse_definition_tim_5_reg_1548 <= cfg_pulse_sequence_t_20_q0;
        pulse_definition_tim_6_reg_1555 <= cfg_pulse_sequence_t_21_q0;
        pulse_definition_tim_7_reg_1562 <= cfg_pulse_sequence_t_22_q0;
        pulse_definition_tim_8_reg_1569 <= cfg_pulse_sequence_t_23_q0;
        pulse_definition_tim_9_reg_1576 <= cfg_pulse_sequence_t_24_q0;
        pulse_definition_tim_reg_1511 <= cfg_pulse_sequence_t_q0;
        pulse_sequence_index_reg_1625 <= pulse_sequence_index_fu_912_p2;
        tmp_2_reg_1632 <= tmp_2_fu_917_p2;
        totalTime_2_reg_1643 <= totalTime_2_fu_929_p2;
        totalTime_reg_1637 <= totalTime_fu_923_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        coef_1_reg_1293 <= coef_1_fu_826_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == coef_ch0_V_V_1_load_A)) begin
        coef_ch0_V_V_1_payload_A <= coef_ch0_V_V_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == coef_ch0_V_V_1_load_B)) begin
        coef_ch0_V_V_1_payload_B <= coef_ch0_V_V_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == coef_ch1_V_V_1_load_A)) begin
        coef_ch1_V_V_1_payload_A <= coef_ch1_V_V_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == coef_ch1_V_V_1_load_B)) begin
        coef_ch1_V_V_1_payload_B <= coef_ch1_V_V_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == coef_ch2_V_V_1_load_A)) begin
        coef_ch2_V_V_1_payload_A <= coef_ch2_V_V_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == coef_ch2_V_V_1_load_B)) begin
        coef_ch2_V_V_1_payload_B <= coef_ch2_V_V_1_data_in;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state48)) begin
        ns_2_reg_1696 <= grp_fu_1007_p2;
        ns_reg_1690 <= grp_fu_1003_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        pulse_definition_prt_4_reg_1669 <= pulse_definition_prt_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (1'd1 == tmp_5_reg_1339))) begin
        pulse_rep_reg_1652 <= pulse_rep_fu_940_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        seq_idx_load_reg_1333 <= seq_idx_fu_260;
        tmp_5_reg_1339 <= tmp_5_fu_871_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (ap_block_state2_io == 1'b0))) begin
        set_reg_1243 <= set_fu_776_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state49) & ~((1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n)) & (1'd1 == or_cond_fu_1168_p2))) begin
        staggered_prt_index_2_reg_1705 <= staggered_prt_index_2_fu_1174_p2;
        tmp_num_samples_fu_268 <= pulse_num_samples_1_fu_1034_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        tmp_16_reg_1680 <= tmp_16_fu_983_p2;
        tmp_19_2_reg_1685 <= tmp_19_2_fu_998_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (ap_block_state3_io == 1'b0))) begin
        tmp_18_reg_1285[8 : 4] <= tmp_18_fu_814_p2[8 : 4];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (1'd0 == exitcond2_fu_820_p2))) begin
        tmp_19_reg_1298 <= tmp_19_fu_842_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (1'd1 == tmp_5_reg_1339) & (1'd1 == tmp_9_fu_935_p2))) begin
        tmp_def_block_post_t_reg_1657 <= tmp_def_block_post_t_fu_951_p3;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state51) & ~((1'b0 == coef_ch0_V_V_1_ack_in) | (1'b0 == coef_ch1_V_V_1_ack_in) | (1'b0 == coef_ch2_V_V_1_ack_in) | (1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b0 == real_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        cfg_filter_coefs_ch0_ce0 = 1'b1;
    end else begin
        cfg_filter_coefs_ch0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        cfg_filter_coefs_ch1_ce0 = 1'b1;
    end else begin
        cfg_filter_coefs_ch1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        cfg_filter_coefs_ch2_ce0 = 1'b1;
    end else begin
        cfg_filter_coefs_ch2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_b_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_c_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_c_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_f_3_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_f_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_f_4_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_f_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_f_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_f_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_n_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_n_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_p_2_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_p_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_p_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_p_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_t_16_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_t_16_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_t_17_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_t_17_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_t_18_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_t_18_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_t_19_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_t_19_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_t_20_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_t_20_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_t_21_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_t_21_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_t_22_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_t_22_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_t_23_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_t_23_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_t_24_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_t_24_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_t_25_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_t_25_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_t_26_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_t_26_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_t_27_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_t_27_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_t_28_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_t_28_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_t_29_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_t_29_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_t_30_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_t_30_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        cfg_pulse_sequence_t_ce0 = 1'b1;
    end else begin
        cfg_pulse_sequence_t_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        coef_ch0_V_V_1_data_in = tmp_V_1_fu_853_p1;
    end else if (((1'b1 == ap_CS_fsm_state2) & (1'd0 == exitcond1_fu_770_p2))) begin
        coef_ch0_V_V_1_data_in = tmp_V_fu_782_p1;
    end else begin
        coef_ch0_V_V_1_data_in = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == coef_ch0_V_V_1_sel)) begin
        coef_ch0_V_V_1_data_out = coef_ch0_V_V_1_payload_B;
    end else begin
        coef_ch0_V_V_1_data_out = coef_ch0_V_V_1_payload_A;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (1'd0 == exitcond1_fu_770_p2) & (ap_block_state2_io == 1'b0)) | ((1'b1 == ap_CS_fsm_state6) & (ap_block_state6_io == 1'b0)))) begin
        coef_ch0_V_V_1_vld_in = 1'b1;
    end else begin
        coef_ch0_V_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (1'd0 == exitcond1_fu_770_p2)) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state7))) begin
        coef_ch0_V_V_TDATA_blk_n = coef_ch0_V_V_1_state[1'd1];
    end else begin
        coef_ch0_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        coef_ch1_V_V_1_data_in = tmp_V_2_fu_858_p1;
    end else if (((1'b1 == ap_CS_fsm_state2) & (1'd0 == exitcond1_fu_770_p2))) begin
        coef_ch1_V_V_1_data_in = tmp_V_fu_782_p1;
    end else begin
        coef_ch1_V_V_1_data_in = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == coef_ch1_V_V_1_sel)) begin
        coef_ch1_V_V_1_data_out = coef_ch1_V_V_1_payload_B;
    end else begin
        coef_ch1_V_V_1_data_out = coef_ch1_V_V_1_payload_A;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (1'd0 == exitcond1_fu_770_p2) & (ap_block_state2_io == 1'b0)) | ((1'b1 == ap_CS_fsm_state6) & (ap_block_state6_io == 1'b0)))) begin
        coef_ch1_V_V_1_vld_in = 1'b1;
    end else begin
        coef_ch1_V_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (1'd0 == exitcond1_fu_770_p2)) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state7))) begin
        coef_ch1_V_V_TDATA_blk_n = coef_ch1_V_V_1_state[1'd1];
    end else begin
        coef_ch1_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        coef_ch2_V_V_1_data_in = tmp_V_3_fu_863_p1;
    end else if (((1'b1 == ap_CS_fsm_state2) & (1'd0 == exitcond1_fu_770_p2))) begin
        coef_ch2_V_V_1_data_in = tmp_V_fu_782_p1;
    end else begin
        coef_ch2_V_V_1_data_in = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == coef_ch2_V_V_1_sel)) begin
        coef_ch2_V_V_1_data_out = coef_ch2_V_V_1_payload_B;
    end else begin
        coef_ch2_V_V_1_data_out = coef_ch2_V_V_1_payload_A;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (1'd0 == exitcond1_fu_770_p2) & (ap_block_state2_io == 1'b0)) | ((1'b1 == ap_CS_fsm_state6) & (ap_block_state6_io == 1'b0)))) begin
        coef_ch2_V_V_1_vld_in = 1'b1;
    end else begin
        coef_ch2_V_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (1'd0 == exitcond1_fu_770_p2)) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state7))) begin
        coef_ch2_V_V_TDATA_blk_n = coef_ch2_V_V_1_state[1'd1];
    end else begin
        coef_ch2_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_1003_ap_start = 1'b1;
    end else begin
        grp_fu_1003_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_1007_ap_start = 1'b1;
    end else begin
        grp_fu_1007_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state51) & ~((1'b0 == coef_ch0_V_V_1_ack_in) | (1'b0 == coef_ch1_V_V_1_ack_in) | (1'b0 == coef_ch2_V_V_1_ack_in) | (1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n)))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        pulse_definition_prt_address0 = tmp_8_fu_958_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        pulse_definition_prt_address0 = 64'd0;
    end else begin
        pulse_definition_prt_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        pulse_definition_prt_address1 = tmp_13_fu_1180_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        pulse_definition_prt_address1 = 64'd1;
    end else begin
        pulse_definition_prt_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10))) begin
        pulse_definition_prt_ce0 = 1'b1;
    end else begin
        pulse_definition_prt_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state49) & ~((1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n))))) begin
        pulse_definition_prt_ce1 = 1'b1;
    end else begin
        pulse_definition_prt_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        pulse_definition_prt_we0 = 1'b1;
    end else begin
        pulse_definition_prt_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        pulse_definition_prt_we1 = 1'b1;
    end else begin
        pulse_definition_prt_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state51))) begin
        pulse_queue_0_V_blk_n = pulse_queue_0_V_full_n;
    end else begin
        pulse_queue_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state51) & ~((1'b0 == coef_ch0_V_V_1_ack_in) | (1'b0 == coef_ch1_V_V_1_ack_in) | (1'b0 == coef_ch2_V_V_1_ack_in) | (1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n)))) begin
        pulse_queue_0_V_din = 841'd7331559403129590068331208687020758653624765228075687047537011123791632385370343464792392772051104864109916034360063928339045596353810784435313926666640532382851295822842678298180301122938618566718730242107326783353838221723324821405531849499257419595776;
    end else if (((1'b1 == ap_CS_fsm_state49) & ~((1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n)))) begin
        pulse_queue_0_V_din = tmp_122_fu_1077_p29;
    end else begin
        pulse_queue_0_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state49) & ~((1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n))) | ((1'b1 == ap_CS_fsm_state51) & ~((1'b0 == coef_ch0_V_V_1_ack_in) | (1'b0 == coef_ch1_V_V_1_ack_in) | (1'b0 == coef_ch2_V_V_1_ack_in) | (1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n))))) begin
        pulse_queue_0_V_write = 1'b1;
    end else begin
        pulse_queue_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state51))) begin
        pulse_queue_1_V_blk_n = pulse_queue_1_V_full_n;
    end else begin
        pulse_queue_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state51) & ~((1'b0 == coef_ch0_V_V_1_ack_in) | (1'b0 == coef_ch1_V_V_1_ack_in) | (1'b0 == coef_ch2_V_V_1_ack_in) | (1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n)))) begin
        pulse_queue_1_V_din = 841'd7331559403129590068331208687020758653624765228075687047537011123791632385370343464792392772051104864109916034360063928339045596353810784435313926666640532382851295822842678298180301122938618566718730242107326783353838221723324821405531849499257419595776;
    end else if (((1'b1 == ap_CS_fsm_state49) & ~((1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n)))) begin
        pulse_queue_1_V_din = tmp_122_fu_1077_p29;
    end else begin
        pulse_queue_1_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state49) & ~((1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n))) | ((1'b1 == ap_CS_fsm_state51) & ~((1'b0 == coef_ch0_V_V_1_ack_in) | (1'b0 == coef_ch1_V_V_1_ack_in) | (1'b0 == coef_ch2_V_V_1_ack_in) | (1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n))))) begin
        pulse_queue_1_V_write = 1'b1;
    end else begin
        pulse_queue_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state51))) begin
        pulse_queue_2_V_blk_n = pulse_queue_2_V_full_n;
    end else begin
        pulse_queue_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state51) & ~((1'b0 == coef_ch0_V_V_1_ack_in) | (1'b0 == coef_ch1_V_V_1_ack_in) | (1'b0 == coef_ch2_V_V_1_ack_in) | (1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n)))) begin
        pulse_queue_2_V_din = 841'd7331559403129590068331208687020758653624765228075687047537011123791632385370343464792392772051104864109916034360063928339045596353810784435313926666640532382851295822842678298180301122938618566718730242107326783353838221723324821405531849499257419595776;
    end else if (((1'b1 == ap_CS_fsm_state49) & ~((1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n)))) begin
        pulse_queue_2_V_din = tmp_3488_fu_1114_p29;
    end else begin
        pulse_queue_2_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state49) & ~((1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n))) | ((1'b1 == ap_CS_fsm_state51) & ~((1'b0 == coef_ch0_V_V_1_ack_in) | (1'b0 == coef_ch1_V_V_1_ack_in) | (1'b0 == coef_ch2_V_V_1_ack_in) | (1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n))))) begin
        pulse_queue_2_V_write = 1'b1;
    end else begin
        pulse_queue_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state51))) begin
        pulse_queue_s_V_blk_n = pulse_queue_s_V_full_n;
    end else begin
        pulse_queue_s_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state51) & ~((1'b0 == coef_ch0_V_V_1_ack_in) | (1'b0 == coef_ch1_V_V_1_ack_in) | (1'b0 == coef_ch2_V_V_1_ack_in) | (1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n)))) begin
        pulse_queue_s_V_din = 841'd7331559403129590068331208687020758653624765228075687047537011123791632385370343464792392772051104864109916034360063928339045596353810784435313926666640532382851295822842678298180301122938618566718730242107326783353838221723324821405531849499257419595776;
    end else if (((1'b1 == ap_CS_fsm_state49) & ~((1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n)))) begin
        pulse_queue_s_V_din = tmp170_fu_1041_p29;
    end else begin
        pulse_queue_s_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state49) & ~((1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n))) | ((1'b1 == ap_CS_fsm_state51) & ~((1'b0 == coef_ch0_V_V_1_ack_in) | (1'b0 == coef_ch1_V_V_1_ack_in) | (1'b0 == coef_ch2_V_V_1_ack_in) | (1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n))))) begin
        pulse_queue_s_V_write = 1'b1;
    end else begin
        pulse_queue_s_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == real_start_status_reg)) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == real_start) | (ap_done_reg == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (ap_block_state2_io == 1'b0) & (1'd1 == exitcond1_fu_770_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((1'b1 == ap_CS_fsm_state2) & (1'd0 == exitcond1_fu_770_p2) & (ap_block_state2_io == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (ap_block_state3_io == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (1'd1 == exitcond2_fu_820_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (ap_block_state6_io == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (ap_block_state7_io == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (1'd0 == tmp_5_fu_871_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & ((1'd0 == tmp_9_fu_935_p2) | (1'd0 == tmp_5_reg_1339)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            if (((1'b1 == ap_CS_fsm_state49) & ~((1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n)) & (1'd0 == or_cond_fu_1168_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state51;
            end else if (((1'b1 == ap_CS_fsm_state49) & ~((1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n)) & (1'd1 == or_cond_fu_1168_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state50;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state49;
            end
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state51 : begin
            if (((1'b1 == ap_CS_fsm_state51) & ~((1'b0 == coef_ch0_V_V_1_ack_in) | (1'b0 == coef_ch1_V_V_1_ack_in) | (1'b0 == coef_ch2_V_V_1_ack_in) | (1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state51;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((1'b0 == real_start) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_io = (((1'd0 == exitcond1_fu_770_p2) & (1'b0 == coef_ch0_V_V_1_ack_in)) | ((1'd0 == exitcond1_fu_770_p2) & (1'b0 == coef_ch1_V_V_1_ack_in)) | ((1'd0 == exitcond1_fu_770_p2) & (1'b0 == coef_ch2_V_V_1_ack_in)));
end

always @ (*) begin
    ap_block_state3_io = ((1'b0 == coef_ch0_V_V_1_ack_in) | (1'b0 == coef_ch1_V_V_1_ack_in) | (1'b0 == coef_ch2_V_V_1_ack_in));
end

always @ (*) begin
    ap_block_state49 = ((1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n));
end

always @ (*) begin
    ap_block_state51 = ((1'b0 == coef_ch0_V_V_1_ack_in) | (1'b0 == coef_ch1_V_V_1_ack_in) | (1'b0 == coef_ch2_V_V_1_ack_in) | (1'b0 == pulse_queue_s_V_full_n) | (1'b0 == pulse_queue_0_V_full_n) | (1'b0 == pulse_queue_1_V_full_n) | (1'b0 == pulse_queue_2_V_full_n));
end

always @ (*) begin
    ap_block_state6_io = ((1'b0 == coef_ch0_V_V_1_ack_in) | (1'b0 == coef_ch1_V_V_1_ack_in) | (1'b0 == coef_ch2_V_V_1_ack_in));
end

always @ (*) begin
    ap_block_state7_io = ((1'b0 == coef_ch0_V_V_1_ack_in) | (1'b0 == coef_ch1_V_V_1_ack_in) | (1'b0 == coef_ch2_V_V_1_ack_in));
end

assign ap_ready = internal_ap_ready;

assign cfg_filter_coefs_ch0_address0 = tmp_20_cast_fu_847_p1;

assign cfg_filter_coefs_ch1_address0 = tmp_20_cast_fu_847_p1;

assign cfg_filter_coefs_ch2_address0 = tmp_20_cast_fu_847_p1;

assign cfg_pulse_sequence_b_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_c_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_f_3_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_f_4_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_f_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_l_1_fu_762_p1 = cfg_pulse_sequence_l;

assign cfg_pulse_sequence_n_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_p_2_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_p_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_s_1_fu_766_p1 = cfg_pulse_sequence_s;

assign cfg_pulse_sequence_t_16_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_t_17_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_t_18_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_t_19_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_t_20_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_t_21_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_t_22_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_t_23_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_t_24_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_t_25_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_t_26_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_t_27_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_t_28_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_t_29_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_t_30_address0 = tmp_7_fu_881_p1;

assign cfg_pulse_sequence_t_address0 = tmp_7_fu_881_p1;

assign coef_1_fu_826_p2 = (coef_reg_722 + 6'd1);

assign coef_ch0_V_V_1_ack_in = coef_ch0_V_V_1_state[1'd1];

assign coef_ch0_V_V_1_ack_out = coef_ch0_V_V_TREADY;

assign coef_ch0_V_V_1_load_A = (coef_ch0_V_V_1_state_cmp_full & ~coef_ch0_V_V_1_sel_wr);

assign coef_ch0_V_V_1_load_B = (coef_ch0_V_V_1_sel_wr & coef_ch0_V_V_1_state_cmp_full);

assign coef_ch0_V_V_1_sel = coef_ch0_V_V_1_sel_rd;

assign coef_ch0_V_V_1_state_cmp_full = ((coef_ch0_V_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign coef_ch0_V_V_1_vld_out = coef_ch0_V_V_1_state[1'd0];

assign coef_ch0_V_V_TDATA = coef_ch0_V_V_1_data_out;

assign coef_ch0_V_V_TVALID = coef_ch0_V_V_1_state[1'd0];

assign coef_ch1_V_V_1_ack_in = coef_ch1_V_V_1_state[1'd1];

assign coef_ch1_V_V_1_ack_out = coef_ch1_V_V_TREADY;

assign coef_ch1_V_V_1_load_A = (coef_ch1_V_V_1_state_cmp_full & ~coef_ch1_V_V_1_sel_wr);

assign coef_ch1_V_V_1_load_B = (coef_ch1_V_V_1_sel_wr & coef_ch1_V_V_1_state_cmp_full);

assign coef_ch1_V_V_1_sel = coef_ch1_V_V_1_sel_rd;

assign coef_ch1_V_V_1_state_cmp_full = ((coef_ch1_V_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign coef_ch1_V_V_1_vld_out = coef_ch1_V_V_1_state[1'd0];

assign coef_ch1_V_V_TDATA = coef_ch1_V_V_1_data_out;

assign coef_ch1_V_V_TVALID = coef_ch1_V_V_1_state[1'd0];

assign coef_ch2_V_V_1_ack_in = coef_ch2_V_V_1_state[1'd1];

assign coef_ch2_V_V_1_ack_out = coef_ch2_V_V_TREADY;

assign coef_ch2_V_V_1_load_A = (coef_ch2_V_V_1_state_cmp_full & ~coef_ch2_V_V_1_sel_wr);

assign coef_ch2_V_V_1_load_B = (coef_ch2_V_V_1_sel_wr & coef_ch2_V_V_1_state_cmp_full);

assign coef_ch2_V_V_1_sel = coef_ch2_V_V_1_sel_rd;

assign coef_ch2_V_V_1_state_cmp_full = ((coef_ch2_V_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign coef_ch2_V_V_1_vld_out = coef_ch2_V_V_1_state[1'd0];

assign coef_ch2_V_V_TDATA = coef_ch2_V_V_1_data_out;

assign coef_ch2_V_V_TVALID = coef_ch2_V_V_1_state[1'd0];

assign exitcond1_fu_770_p2 = ((val_assign_reg_710 == 3'd4) ? 1'b1 : 1'b0);

assign exitcond2_fu_820_p2 = ((coef_reg_722 == 6'd48) ? 1'b1 : 1'b0);

assign num_pulses_scheduled_fu_1150_p2 = (num_pulses_scheduled_1_fu_264 + 32'd1);

assign or_cond_fu_1168_p2 = (tmp_10_fu_1156_p2 | tmp_11_fu_1162_p2);

assign p_shl1_cast_fu_810_p1 = tmp_1_fu_802_p3;

assign pulse_definition_prt_5_fu_977_p3 = ((tmp_15_fu_973_p2[0:0] === 1'b1) ? pulse_definition_prt_4_reg_1669 : totalTime_reg_1637);

assign pulse_definition_prt_6_fu_992_p3 = ((tmp_17_2_fu_988_p2[0:0] === 1'b1) ? pulse_definition_prt_4_reg_1669 : totalTime_2_reg_1643);

assign pulse_num_samples_1_fu_1034_p3 = ((tmp_20_2_fu_1029_p2[0:0] === 1'b1) ? 32'd1 : ns_2_reg_1696);

assign pulse_num_samples_fu_1022_p3 = ((tmp_17_fu_1017_p2[0:0] === 1'b1) ? 32'd1 : ns_reg_1690);

assign pulse_rep_fu_940_p2 = (pulse_pulse_rep_reg_745 + 32'd1);

assign pulse_sequence_index_fu_912_p2 = (cfg_pulse_sequence_s + tmp_fu_909_p1);

assign sel_tmp_fu_1206_p2 = (tmp_12_fu_1195_p2 | tmp_14_fu_1200_p2);

assign seq_idx_1_fu_963_p2 = (seq_idx_load_reg_1333 + 32'd1);

assign set_fu_776_p2 = (val_assign_reg_710 + 3'd1);

assign staggered_prt_index_1_fu_1212_p3 = ((sel_tmp_fu_1206_p2[0:0] === 1'b1) ? 8'd0 : staggered_prt_index_2_reg_1705);

assign staggered_prt_index_2_fu_1174_p2 = (staggered_prt_index_reg_733 + 8'd1);

assign start_out = real_start;

assign start_write = (ap_start & start_control_reg);

assign tmp170_fu_1041_p29 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{1'd0}, {tmp_num_samples_fu_268}}}, {pulse_pulse_rep_reg_745}}}, {pulse_sequence_index_reg_1625}}}, {pulse_definition_tim_15_reg_1618}}}, {pulse_definition_tim_14_reg_1611}}}, {pulse_definition_tim_13_reg_1604}}}, {pulse_definition_tim_12_reg_1597}}}, {pulse_definition_tim_11_reg_1590}}}, {pulse_definition_tim_10_reg_1583}}}, {pulse_definition_tim_9_reg_1576}}}, {pulse_definition_tim_8_reg_1569}}}, {pulse_definition_tim_7_reg_1562}}}, {pulse_definition_tim_6_reg_1555}}}, {pulse_definition_tim_5_reg_1548}}}, {pulse_definition_tim_4_reg_1540}}}, {pulse_definition_tim_3_reg_1533}}}, {pulse_definition_tim_2_reg_1526}}}, {pulse_definition_tim_1_reg_1518}}}, {pulse_definition_tim_reg_1511}}}, {pulse_definition_fil_2_reg_1504}}}, {pulse_definition_fil_1_reg_1497}}}, {pulse_definition_fil_reg_1490}}}, {pulse_definition_con_reg_1483}}}, {tmp_def_block_post_t_reg_1657}}}, {pulse_definition_num_reg_1470}}}, {cfg_pulse_sequence_p_6_reg_1463}}}, {pulse_definition_prt_4_reg_1669}};

assign tmp_10_fu_1156_p2 = ((cfg_num_pulses_to_ex == 32'd0) ? 1'b1 : 1'b0);

assign tmp_11_fu_1162_p2 = ((num_pulses_scheduled_fu_1150_p2 < cfg_num_pulses_to_ex) ? 1'b1 : 1'b0);

assign tmp_122_fu_1077_p29 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{1'd0}, {pulse_num_samples_fu_1022_p3}}}, {pulse_pulse_rep_reg_745}}}, {pulse_sequence_index_reg_1625}}}, {pulse_definition_tim_15_reg_1618}}}, {pulse_definition_tim_14_reg_1611}}}, {pulse_definition_tim_13_reg_1604}}}, {pulse_definition_tim_12_reg_1597}}}, {pulse_definition_tim_11_reg_1590}}}, {pulse_definition_tim_10_reg_1583}}}, {pulse_definition_tim_9_reg_1576}}}, {pulse_definition_tim_8_reg_1569}}}, {pulse_definition_tim_7_reg_1562}}}, {pulse_definition_tim_6_reg_1555}}}, {pulse_definition_tim_5_reg_1548}}}, {pulse_definition_tim_4_reg_1540}}}, {pulse_definition_tim_3_reg_1533}}}, {pulse_definition_tim_2_reg_1526}}}, {pulse_definition_tim_1_reg_1518}}}, {pulse_definition_tim_reg_1511}}}, {pulse_definition_fil_2_reg_1504}}}, {pulse_definition_fil_1_reg_1497}}}, {pulse_definition_fil_reg_1490}}}, {pulse_definition_con_reg_1483}}}, {tmp_def_block_post_t_reg_1657}}}, {pulse_definition_num_reg_1470}}}, {cfg_pulse_sequence_p_6_reg_1463}}}, {pulse_definition_prt_4_reg_1669}};

assign tmp_12_fu_1195_p2 = ((staggered_prt_index_2_reg_1705 == 8'd2) ? 1'b1 : 1'b0);

assign tmp_13_fu_1180_p1 = staggered_prt_index_2_fu_1174_p2;

assign tmp_14_fu_1200_p2 = ((pulse_definition_prt_q1 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_15_fu_973_p2 = ((pulse_definition_prt_4_reg_1669 < totalTime_reg_1637) ? 1'b1 : 1'b0);

assign tmp_16_fu_983_p2 = (pulse_definition_prt_5_fu_977_p3 - pulse_definition_tim_1_reg_1518);

assign tmp_17_2_fu_988_p2 = ((pulse_definition_prt_4_reg_1669 < totalTime_2_reg_1643) ? 1'b1 : 1'b0);

assign tmp_17_fu_1017_p2 = ((ns_reg_1690 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_18_fu_814_p2 = (tmp_4_fu_794_p3 - p_shl1_cast_fu_810_p1);

assign tmp_19_2_fu_998_p2 = (pulse_definition_prt_6_fu_992_p3 - pulse_definition_tim_4_reg_1540);

assign tmp_19_fu_842_p2 = (tmp_18_reg_1285 + tmp_1_cast_fu_838_p1);

assign tmp_1_cast_fu_838_p1 = tmp_s_fu_832_p2;

assign tmp_1_fu_802_p3 = {{val_assign_reg_710}, {4'd0}};

assign tmp_20_2_fu_1029_p2 = ((ns_2_reg_1696 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_20_cast_fu_847_p1 = $signed(tmp_19_reg_1298);

assign tmp_2_fu_917_p2 = ($signed(32'd4294967295) + $signed(cfg_pulse_sequence_n_q0));

assign tmp_3488_fu_1114_p29 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{1'd0}, {pulse_num_samples_1_fu_1034_p3}}}, {pulse_pulse_rep_reg_745}}}, {pulse_sequence_index_reg_1625}}}, {pulse_definition_tim_15_reg_1618}}}, {pulse_definition_tim_14_reg_1611}}}, {pulse_definition_tim_13_reg_1604}}}, {pulse_definition_tim_12_reg_1597}}}, {pulse_definition_tim_11_reg_1590}}}, {pulse_definition_tim_10_reg_1583}}}, {pulse_definition_tim_9_reg_1576}}}, {pulse_definition_tim_8_reg_1569}}}, {pulse_definition_tim_7_reg_1562}}}, {pulse_definition_tim_6_reg_1555}}}, {pulse_definition_tim_5_reg_1548}}}, {pulse_definition_tim_4_reg_1540}}}, {pulse_definition_tim_3_reg_1533}}}, {pulse_definition_tim_2_reg_1526}}}, {pulse_definition_tim_1_reg_1518}}}, {pulse_definition_tim_reg_1511}}}, {pulse_definition_fil_2_reg_1504}}}, {pulse_definition_fil_1_reg_1497}}}, {pulse_definition_fil_reg_1490}}}, {pulse_definition_con_reg_1483}}}, {tmp_def_block_post_t_reg_1657}}}, {pulse_definition_num_reg_1470}}}, {cfg_pulse_sequence_p_6_reg_1463}}}, {pulse_definition_prt_4_reg_1669}};

assign tmp_3_fu_946_p2 = ((pulse_pulse_rep_reg_745 == tmp_2_reg_1632) ? 1'b1 : 1'b0);

assign tmp_4_fu_794_p3 = {{val_assign_reg_710}, {6'd0}};

assign tmp_5_fu_871_p2 = ((seq_idx_fu_260 < cfg_pulse_sequence_l_1_reg_1230) ? 1'b1 : 1'b0);

assign tmp_6_fu_876_p2 = (seq_idx_fu_260 + cfg_pulse_sequence_s_1_reg_1235);

assign tmp_7_fu_881_p1 = tmp_6_fu_876_p2;

assign tmp_8_fu_958_p1 = staggered_prt_index_reg_733;

assign tmp_9_fu_935_p2 = ((pulse_pulse_rep_reg_745 < pulse_definition_num_reg_1470) ? 1'b1 : 1'b0);

assign tmp_V_1_fu_853_p1 = cfg_filter_coefs_ch0_q0[23:0];

assign tmp_V_2_fu_858_p1 = cfg_filter_coefs_ch1_q0[23:0];

assign tmp_V_3_fu_863_p1 = cfg_filter_coefs_ch2_q0[23:0];

assign tmp_V_fu_782_p1 = val_assign_reg_710;

assign tmp_def_block_post_t_fu_951_p3 = ((tmp_3_fu_946_p2[0:0] === 1'b1) ? pulse_definition_blo_reg_1478 : 32'd0);

assign tmp_fu_909_p1 = seq_idx_load_reg_1333[7:0];

assign tmp_s_fu_832_p2 = ($signed(6'd47) - $signed(coef_reg_722));

assign totalTime_2_fu_929_p2 = (cfg_pulse_sequence_t_19_q0 + cfg_pulse_sequence_t_27_q0);

assign totalTime_fu_923_p2 = (cfg_pulse_sequence_t_16_q0 + cfg_pulse_sequence_t_24_q0);

always @ (posedge ap_clk) begin
    cfg_pulse_sequence_l_1_reg_1230[31:8] <= 24'b000000000000000000000000;
    cfg_pulse_sequence_s_1_reg_1235[31:8] <= 24'b000000000000000000000000;
    tmp_18_reg_1285[3:0] <= 4'b0000;
end

endmodule //scheduler_parser
