# -*- python -*-

tools = Split("""
qt4
qtt_qtconfig
qtt_scopeplot
qtt_knob
hcrdds
doxygen
fftw
boost_program_options
""")

env = Environment(tools = ['default'] + tools)

qt4modules = ['QtCore','QtGui']
env.EnableQt4Modules(qt4modules)

# This will create ui_HcrScope.h
env.Uic4(['HcrScope.ui',])

sources = Split("""
main.cpp
HcrScope.cpp
PlotInfo.cpp
""")

headers = Split("""
HcrScope.h
PlotInfo.h
""")

html = env.Apidocs(sources + headers, DOXYFILE_FILE = "Doxyfile")

hcrscope = env.Program('hcrscope', sources)

Default(hcrscope, html)



