# -*- python -*-

tools = Split("""
qt4
ascope
qtt_qtconfig
doxygen
fftw
boost_program_options
profilerdds
""")

env = Environment(tools = ['default'] + tools)

sources = Split("""
main.cpp
AScopeReader.cpp
""")

headers = Split("""
""")

html = env.Apidocs(sources + headers, DOXYFILE_FILE = "Doxyfile")

hcrscope = env.Program('hcrscope', sources)

#Default(hcrscope, html)
Default(hcrscope)



