# -*- python -*-

tools = Split("""
qt4
qtt_qtconfig
hcrdds
doxygen
boost_program_options
rapradar
""")

env = Environment(tools = ['default'] + tools)

qt4modules = ['QtCore', 'QtGui']
env.EnableQt4Modules(qt4modules)

sources = Split("""
hcrprod.cpp
ProductGenerator.cpp
""")

headers = Split("""
ProductGenerator.h
""")

html = env.Apidocs(sources + headers, DOXYFILE_FILE = "Doxyfile")

hcrprod = env.Program('hcrprod', sources)

Default(hcrprod, html)



