# -*- python -*-

tools = Split("""
profilerdds
qtt_qtconfig
boost_date_time
boost_program_options
""")

env = Environment(tools = ['default'] + tools)

sources = Split("""
main.cpp
SnifferTSReader.cpp
""")

headers = Split("""
SnifferTSReader.h
""")

html = env.Apidocs(sources + headers, DOXYFILE_FILE = "#/Doxyfile")

sniffer = env.Program('sniffer', sources)
Default(sniffer, html)

