# -*- python -*-
#
# Build cmigitsDaemon
#

tools = Split('''
boost_program_options
cmigits
qt4
QFunctionWrapper
QXmlRpcServerAbyss
rapradar
''')

env = Environment(tools = ['default'] + tools)
env.EnableQt4Modules(['QtCore', 'QtGui'])

sources = Split('''
AltitudeMonitorDaemon.cpp
''')

headers = Split('''
''')

daemon = env.Program('AltitudeMonitorDaemon', sources)
Default(daemon)
