# -*- python -*-
#
# Build cmigitsDaemon
#

tools = ['cmigits', 'qt4', 'QFunctionWrapper', 'QXmlRpcServerAbyss', 'rapradar']

env = Environment(tools = ['default'] + tools)
env.EnableQt4Modules(['QtCore', 'QtGui'])

sources = Split('''
cmigitsDaemon.cpp
Ts2CmigitsFmqThread.cpp
''')

headers = Split('''
Ts2CmigitsFmqThread.h
''')

daemon = env.Program('cmigitsDaemon', sources)
Default(daemon)
