# -*- python -*-
#
# Build cmigitsDaemon
#

tools = Split("""
boost_program_options
cmigits
lrose
qt4
QFunctionWrapper
QXmlRpcServerAbyss
""")

env = Environment(tools = ['default'] + tools)
env.EnableQtModules(['QtCore', 'QtGui'])

sources = Split('''
cmigitsDaemon.cpp
Ts2CmigitsFmqThread.cpp
''')

headers = Split('''
Ts2CmigitsFmqThread.h
''')

daemon = env.Program('cmigitsDaemon', sources)
Default(daemon)
