# -*- python -*-
#
# Build cmigitsDaemon
#

tools = Split("""
boost_program_options
cmigits
lrose
qt5
qtcore
qtgui
QFunctionWrapper
QXmlRpcServerAbyss
""")

env = Environment(tools = ['default'] + tools)

sources = Split('''
cmigitsDaemon.cpp
Ts2CmigitsFmqThread.cpp
''')

headers = Split('''
Ts2CmigitsFmqThread.h
''')

daemon = env.Program('cmigitsDaemon', sources)
Default(daemon)
