module HcrDDS {

    enum RadarChoice {HCR_HI, HCR_LO};
    typedef sequence<short> TS;
    
    typedef struct housekeeping_ {
        long long timetag;
        long gates;
        long tsLength;
        long numChannels;
    } Housekeeping;

#pragma DCPS_DATA_TYPE "HcrDDS::TimeSeries"
#pragma DCPS_DATA_KEY  "HcrDDS::TimeSeries radarId"

    /// TimeSeries carries I and Q pairs for a limited number 
    /// of consecutive gates, for nci samples, for one radar.
    /// The packing order is [sample][gate][I,Q]
    struct TimeSeries {
        RadarChoice radarId;
        Housekeeping hskp;
        TS tsdata;
    };
};
