# -*- python -*-

xmitdTools = Split("""
logx
doxygen
xmlrpc
rapradar
boost_program_options
hcrpmc730client
qt4
""")

xmitdEnv = Environment(tools = ['default'] + xmitdTools)
xmitdEnv.EnableQt4Modules(['QtCore'])

xmitd_sources = Split("""
hcr_xmitd.cpp
HcrXmitter.cpp
XmitStatus.cpp
""")

hcr_xmitd = xmitdEnv.Program('hcr_xmitd', xmitd_sources)
Default(hcr_xmitd)


headers = Split("""
HcrXmitter.h
XmitStatus.h
""")

html = xmitdEnv.Apidocs(xmitd_sources + headers)
Default(html)
