# -*- python -*-

xmitdTools = Split("""
archive_xmlrpc_c
boost_program_options
doxygen
logx
lrose
qt5
qtcore
QFunctionWrapper
QXmlRpcServerAbyss
""")

xmitdEnv = Environment(tools = ['default'] + xmitdTools)

xmitd_sources = Split("""
hcr_xmitd.cpp
HcrXmitter.cpp
XmitStatus.cpp
""")

hcr_xmitd = xmitdEnv.Program('hcr_xmitd', xmitd_sources)
Default(hcr_xmitd)


headers = Split("""
HcrXmitter.h
XmitStatus.h
""")

html = xmitdEnv.Apidocs(xmitd_sources + headers)
Default(html)
