# -*- python -*-
#
# Build Motion Control
#

tools = Split("""
    cmigits
    motioncontrol
    qt4
    rapradar
    xmlrpc_server_abyss++
""")

env = Environment(tools = ['default'] + tools)
env.EnableQt4Modules(['QtCore', 'QtGui', 'QtNetwork'])

uisources = ['ClientMainWindow.ui']
env.Uic4(uisources)

serversources = Split("""
	MotionControlDaemon.cpp
""")

daemon = env.Program('MotionControlDaemon', serversources)
env.Default(daemon)

clientsources = Split("""
	ClientMain.cpp
	ClientMainWindow.cpp
""")

clientheaders = Split("""
	ClientMainWindow.h
""")

client = env.Program('MotionControlClient', clientsources)
env.Default(client)