# -*- python -*-
#
# Build Motion Control
#

tools = Split("""
    archive_xmlrpc_c
    cmigits
    motioncontrolrpcclient
    qt4
    xmlrpc_server_abyss++
""")

env = Environment(tools = ['default'] + tools)
env.EnableQt4Modules(['QtCore', 'QtGui', 'QtNetwork'])

uisources = ['ClientMainWindow.ui']
env.Uic4(uisources)

serversources = Split("""
    DriveConnection.cpp
    DriveStatus.cpp
    ElmoServoDrive.cpp
	MotionControlDaemon.cpp
""")

serverheaders = Split("""
    DriveConnection.h
    DriveStatus.h
    ElmoServoDrive.h
""")

daemon = env.Program('MotionControlDaemon', serversources)
env.Default(daemon)

clientsources = Split("""
	ClientMain.cpp
	ClientMainWindow.cpp
""")

clientheaders = Split("""
	ClientMainWindow.h
""")

client = env.Program('MotionControlClient', clientsources)
env.Default(client)