#create_clock -period 4.000 -name s_axi_csr_aclk [get_ports s_axi_csr_aclk]
create_clock -period 2.222 -name s_axis_aclk [get_ports s_axis_aclk]
create_clock -period 3.2 -name m_axis_ddr_aclk [get_ports m_axis_ddr_aclk]
#set_clock_groups -name async_clocks1 -asynchronous -group [get_clocks s_axi_csr_aclk] -group [get_clocks s_axis_aclk]
create_clock -period 4.000 [get_ports s_axi_csr_aclk]