-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.2
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity output_fifo69 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    pulse_queue_ch0_V_dout : IN STD_LOGIC_VECTOR (812 downto 0);
    pulse_queue_ch0_V_empty_n : IN STD_LOGIC;
    pulse_queue_ch0_V_read : OUT STD_LOGIC;
    pulse_metadata_ch0_V_TDATA : OUT STD_LOGIC_VECTOR (815 downto 0);
    pulse_metadata_ch0_V_TVALID : OUT STD_LOGIC;
    pulse_metadata_ch0_V_TREADY : IN STD_LOGIC );
end;


architecture behav of output_fifo69 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_32C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001100101100";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal pulse_metadata_ch0_V_1_data_out : STD_LOGIC_VECTOR (815 downto 0);
    signal pulse_metadata_ch0_V_1_vld_in : STD_LOGIC;
    signal pulse_metadata_ch0_V_1_vld_out : STD_LOGIC;
    signal pulse_metadata_ch0_V_1_ack_in : STD_LOGIC;
    signal pulse_metadata_ch0_V_1_ack_out : STD_LOGIC;
    signal pulse_metadata_ch0_V_1_payload_A : STD_LOGIC_VECTOR (815 downto 0);
    signal pulse_metadata_ch0_V_1_payload_B : STD_LOGIC_VECTOR (815 downto 0);
    signal pulse_metadata_ch0_V_1_sel_rd : STD_LOGIC := '0';
    signal pulse_metadata_ch0_V_1_sel_wr : STD_LOGIC := '0';
    signal pulse_metadata_ch0_V_1_sel : STD_LOGIC;
    signal pulse_metadata_ch0_V_1_load_A : STD_LOGIC;
    signal pulse_metadata_ch0_V_1_load_B : STD_LOGIC;
    signal pulse_metadata_ch0_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal pulse_metadata_ch0_V_1_state_cmp_full : STD_LOGIC;
    signal pulse_queue_ch0_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal pulse_metadata_ch0_V_TDATA_blk_n : STD_LOGIC;
    signal pulse_terminate_fu_65_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal cast_fu_85_p1 : STD_LOGIC_VECTOR (815 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal tmp_49_fu_73_p1 : STD_LOGIC_VECTOR (811 downto 0);
    signal tmp_1_fu_77_p3 : STD_LOGIC_VECTOR (812 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_state1 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and not(((ap_const_logic_0 = pulse_queue_ch0_V_empty_n) or (ap_const_logic_0 = pulse_metadata_ch0_V_1_ack_in) or (ap_const_boolean_1 = ap_block_state2_io))) and (ap_const_lv1_1 = pulse_terminate_fu_65_p3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    pulse_metadata_ch0_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                pulse_metadata_ch0_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = pulse_metadata_ch0_V_1_ack_out) and (ap_const_logic_1 = pulse_metadata_ch0_V_1_vld_out))) then 
                                        pulse_metadata_ch0_V_1_sel_rd <= not(pulse_metadata_ch0_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    pulse_metadata_ch0_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                pulse_metadata_ch0_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = pulse_metadata_ch0_V_1_vld_in) and (ap_const_logic_1 = pulse_metadata_ch0_V_1_ack_in))) then 
                                        pulse_metadata_ch0_V_1_sel_wr <= not(pulse_metadata_ch0_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    pulse_metadata_ch0_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                pulse_metadata_ch0_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = pulse_metadata_ch0_V_1_vld_in) and (ap_const_logic_1 = pulse_metadata_ch0_V_1_ack_out) and (pulse_metadata_ch0_V_1_state = ap_const_lv2_3)) or ((ap_const_logic_0 = pulse_metadata_ch0_V_1_vld_in) and (pulse_metadata_ch0_V_1_state = ap_const_lv2_2)))) then 
                    pulse_metadata_ch0_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = pulse_metadata_ch0_V_1_vld_in) and (ap_const_logic_0 = pulse_metadata_ch0_V_1_ack_out) and (pulse_metadata_ch0_V_1_state = ap_const_lv2_3)) or ((ap_const_logic_0 = pulse_metadata_ch0_V_1_ack_out) and (pulse_metadata_ch0_V_1_state = ap_const_lv2_1)))) then 
                    pulse_metadata_ch0_V_1_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = pulse_metadata_ch0_V_1_vld_in) and (pulse_metadata_ch0_V_1_state = ap_const_lv2_2)) or ((ap_const_logic_1 = pulse_metadata_ch0_V_1_ack_out) and (pulse_metadata_ch0_V_1_state = ap_const_lv2_1)) or ((pulse_metadata_ch0_V_1_state = ap_const_lv2_3) and not(((ap_const_logic_1 = pulse_metadata_ch0_V_1_vld_in) and (ap_const_logic_0 = pulse_metadata_ch0_V_1_ack_out))) and not(((ap_const_logic_0 = pulse_metadata_ch0_V_1_vld_in) and (ap_const_logic_1 = pulse_metadata_ch0_V_1_ack_out)))))) then 
                    pulse_metadata_ch0_V_1_state <= ap_const_lv2_3;
                else 
                    pulse_metadata_ch0_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = pulse_metadata_ch0_V_1_load_A)) then
                pulse_metadata_ch0_V_1_payload_A <= cast_fu_85_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = pulse_metadata_ch0_V_1_load_B)) then
                pulse_metadata_ch0_V_1_payload_B <= cast_fu_85_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, pulse_queue_ch0_V_empty_n, pulse_metadata_ch0_V_1_ack_in, ap_CS_fsm_state2, pulse_terminate_fu_65_p3, ap_CS_fsm_state3, ap_block_state2_io)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and not(((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and not(((ap_const_logic_0 = pulse_queue_ch0_V_empty_n) or (ap_const_logic_0 = pulse_metadata_ch0_V_1_ack_in) or (ap_const_boolean_1 = ap_block_state2_io))) and (ap_const_lv1_1 = pulse_terminate_fu_65_p3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv1_0 = pulse_terminate_fu_65_p3) and not(((ap_const_logic_0 = pulse_queue_ch0_V_empty_n) or (ap_const_logic_0 = pulse_metadata_ch0_V_1_ack_in) or (ap_const_boolean_1 = ap_block_state2_io))))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (pulse_metadata_ch0_V_1_ack_in = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(pulse_queue_ch0_V_empty_n, pulse_metadata_ch0_V_1_ack_in)
    begin
                ap_block_state2 <= ((ap_const_logic_0 = pulse_queue_ch0_V_empty_n) or (ap_const_logic_0 = pulse_metadata_ch0_V_1_ack_in));
    end process;


    ap_block_state2_io_assign_proc : process(pulse_metadata_ch0_V_1_ack_in, pulse_terminate_fu_65_p3)
    begin
                ap_block_state2_io <= ((ap_const_lv1_0 = pulse_terminate_fu_65_p3) and (ap_const_logic_0 = pulse_metadata_ch0_V_1_ack_in));
    end process;


    ap_done_assign_proc : process(ap_done_reg, pulse_queue_ch0_V_empty_n, pulse_metadata_ch0_V_1_ack_in, ap_CS_fsm_state2, pulse_terminate_fu_65_p3, ap_block_state2_io)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and not(((ap_const_logic_0 = pulse_queue_ch0_V_empty_n) or (ap_const_logic_0 = pulse_metadata_ch0_V_1_ack_in) or (ap_const_boolean_1 = ap_block_state2_io))) and (ap_const_lv1_1 = pulse_terminate_fu_65_p3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(pulse_queue_ch0_V_empty_n, pulse_metadata_ch0_V_1_ack_in, ap_CS_fsm_state2, pulse_terminate_fu_65_p3, ap_block_state2_io)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and not(((ap_const_logic_0 = pulse_queue_ch0_V_empty_n) or (ap_const_logic_0 = pulse_metadata_ch0_V_1_ack_in) or (ap_const_boolean_1 = ap_block_state2_io))) and (ap_const_lv1_1 = pulse_terminate_fu_65_p3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

        cast_fu_85_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_77_p3),816));

    pulse_metadata_ch0_V_1_ack_in <= pulse_metadata_ch0_V_1_state(1);
    pulse_metadata_ch0_V_1_ack_out <= pulse_metadata_ch0_V_TREADY;

    pulse_metadata_ch0_V_1_data_out_assign_proc : process(pulse_metadata_ch0_V_1_payload_A, pulse_metadata_ch0_V_1_payload_B, pulse_metadata_ch0_V_1_sel)
    begin
        if ((ap_const_logic_1 = pulse_metadata_ch0_V_1_sel)) then 
            pulse_metadata_ch0_V_1_data_out <= pulse_metadata_ch0_V_1_payload_B;
        else 
            pulse_metadata_ch0_V_1_data_out <= pulse_metadata_ch0_V_1_payload_A;
        end if; 
    end process;

    pulse_metadata_ch0_V_1_load_A <= (pulse_metadata_ch0_V_1_state_cmp_full and not(pulse_metadata_ch0_V_1_sel_wr));
    pulse_metadata_ch0_V_1_load_B <= (pulse_metadata_ch0_V_1_sel_wr and pulse_metadata_ch0_V_1_state_cmp_full);
    pulse_metadata_ch0_V_1_sel <= pulse_metadata_ch0_V_1_sel_rd;
    pulse_metadata_ch0_V_1_state_cmp_full <= '0' when (pulse_metadata_ch0_V_1_state = ap_const_lv2_1) else '1';

    pulse_metadata_ch0_V_1_vld_in_assign_proc : process(pulse_queue_ch0_V_empty_n, pulse_metadata_ch0_V_1_ack_in, ap_CS_fsm_state2, pulse_terminate_fu_65_p3, ap_block_state2_io)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv1_0 = pulse_terminate_fu_65_p3) and not(((ap_const_logic_0 = pulse_queue_ch0_V_empty_n) or (ap_const_logic_0 = pulse_metadata_ch0_V_1_ack_in) or (ap_const_boolean_1 = ap_block_state2_io))))) then 
            pulse_metadata_ch0_V_1_vld_in <= ap_const_logic_1;
        else 
            pulse_metadata_ch0_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    pulse_metadata_ch0_V_1_vld_out <= pulse_metadata_ch0_V_1_state(0);
    pulse_metadata_ch0_V_TDATA <= pulse_metadata_ch0_V_1_data_out;

    pulse_metadata_ch0_V_TDATA_blk_n_assign_proc : process(pulse_metadata_ch0_V_1_state, ap_CS_fsm_state2, pulse_terminate_fu_65_p3, ap_CS_fsm_state3)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv1_0 = pulse_terminate_fu_65_p3)) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            pulse_metadata_ch0_V_TDATA_blk_n <= pulse_metadata_ch0_V_1_state(1);
        else 
            pulse_metadata_ch0_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    pulse_metadata_ch0_V_TVALID <= pulse_metadata_ch0_V_1_state(0);

    pulse_queue_ch0_V_blk_n_assign_proc : process(pulse_queue_ch0_V_empty_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            pulse_queue_ch0_V_blk_n <= pulse_queue_ch0_V_empty_n;
        else 
            pulse_queue_ch0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    pulse_queue_ch0_V_read_assign_proc : process(pulse_queue_ch0_V_empty_n, pulse_metadata_ch0_V_1_ack_in, ap_CS_fsm_state2, ap_block_state2_io)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and not(((ap_const_logic_0 = pulse_queue_ch0_V_empty_n) or (ap_const_logic_0 = pulse_metadata_ch0_V_1_ack_in) or (ap_const_boolean_1 = ap_block_state2_io))))) then 
            pulse_queue_ch0_V_read <= ap_const_logic_1;
        else 
            pulse_queue_ch0_V_read <= ap_const_logic_0;
        end if; 
    end process;

    pulse_terminate_fu_65_p3 <= pulse_queue_ch0_V_dout(812 downto 812);
    tmp_1_fu_77_p3 <= (ap_const_lv1_0 & tmp_49_fu_73_p1);
    tmp_49_fu_73_p1 <= pulse_queue_ch0_V_dout(812 - 1 downto 0);
end behav;
