# -*- python -*-
# $Id: SConstruct,v 1.4 2005/08/23 16:22:41 granger Exp $

import os,os.path, sys
sys.path.insert(0, os.path.join(os.getcwd(),'config'))
import eol_scons
import SCons

options = eol_scons.Pkg_Options()
#options.Add(BoolOption('PENTEK', 'Build Pentek applications?', 0))


def SdrSetup(env):
    env.Require(['QTDIR'])
    env.AppendUnique (CCFLAGS=['-Wall','-Wno-char-subscripts'])
    env.AppendUnique (CXXFLAGS=['-Wno-non-virtual-dtor'])
    return env
    
env = Environment(tools = ['default'], GLOBAL_TOOLS = [SdrSetup])


dirs = Split(
"""
   bwtest
   profilerdrx
""")
    
for d in dirs:
    if os.access (d, os.R_OK):
        SConscript(dirs = d)
    else:
        print "Skipping %s." % d

#env.ApidocsIndex (source=["mainpage.dox","config/README"])

options.Update(env)
Help(options.GenerateHelpText(env))

