# -*- python -*-
# $Id: SConstruct,v 1.4 2005/08/23 16:22:41 granger Exp $

import os
import os.path
import sys

sys.path.insert(0, os.path.join(os.getcwd(),'config'))

import eol_scons
import SCons

options = eol_scons.Pkg_Options()

def HcrSetup(env):
    env.Require(['QTDIR'])
    env.AppendUnique (CCFLAGS=['-Wall','-Wno-char-subscripts'])
    env.AppendUnique (CXXFLAGS=['-Wno-non-virtual-dtor',])
    env['DOXYFILE_DICT'] = dict()
    env['DOXYFILE_DICT'].update({ 'HTML_HEADER' : env.File("#header.html") })
    return env
    
env = Environment(tools = ['default'], GLOBAL_TOOLS = [HcrSetup])

dirs = Split(
"""
   bwtest
   hcrdrx
   configddc
""")
    
for d in dirs:
    if os.access (d, os.R_OK):
        SConscript(dirs = d)
    else:
        print "Skipping %s." % d

env.Alias('apidocs', env.Dir("apidocs"))

options.Update(env)
Help(options.GenerateHelpText(env))

