# -*- python -*-

hcrguiTools = Split("""
logx
doxygen
hcrdrxrpcclient
xmitdrpcclient
qt4
""")
hcrguiEnv = Environment(tools = ['default'] + hcrguiTools)
hcrguiEnv.EnableQt4Modules(['QtCore', 'QtGui'])

hcrgui_sources = Split("""
hcrgui.cpp
HcrGuiMainWindow.cpp
HcrGuiXmitStatusDialog.cpp
qrc_HcrGuiMainWindow.cc
""")
hcrgui = hcrguiEnv.Program('hcrgui', hcrgui_sources)
Default(hcrgui)

uifiles = Split("""
HcrGuiMainWindow.ui
HcrGuiXmitStatusDialog.ui
""")
hcrguiEnv.Uic4(uifiles)

# This generates the rules for *.qrc -> qrc_*.cc
qrcfiles = Split("""
HcrGuiMainWindow.qrc
""")
hcrguiEnv.Qrc(qrcfiles)

headers = Split("""
HcrGuiMainWindow.h
HcrGuiXmitStatusDialog.h
""")

html = hcrguiEnv.Apidocs(hcrgui_sources + headers)
Default(html)
