# -*- python -*-

hcrguiTools = Split("""
boost_date_time
hcrpmc730client
cmigitsdaemonrpcclient
doxygen
drxstatus
fireflydRpcClient
hcrdrxrpcclient
hcrexecutiveclient
logx
lrose
motioncontrol
operationmode
qt5
qtcore
qtgui
qtwidgets
SpectracomRpcClient
xmitdrpcclient
""")
hcrguiEnv = Environment(tools = ['default'] + hcrguiTools)

hcrgui_sources = Split("""
hcrgui.cpp
AntennaModeDialog.cpp
CmigitsDetails.cpp
DataMapperStatusThread.cpp
FireflydDetails.cpp
FireflydStatusThread.cpp
HcrdrxDetails.cpp
HcrdrxStatusThread.cpp
HcrGuiLogWindow.cpp
HcrGuiMainWindow.cpp
HcrExecutiveDetails.cpp
InsOverview.cpp
MotionControlDetails.cpp
Pmc730Details.cpp
qrc_HcrGuiMainWindow.cc
SpectracomDetails.cpp
SpectracomStatusThread.cpp
XmitDetails.cpp
XmitdStatusThread.cpp
""")
hcrgui = hcrguiEnv.Program('hcrgui', hcrgui_sources)
Default(hcrgui)

uifiles = Split("""
AntennaModeDialog.ui
CmigitsDetails.ui
FireflydDetails.ui
HcrdrxDetails.ui
HcrGuiLogWindow.ui
HcrGuiMainWindow.ui
HcrExecutiveDetails.ui
InsOverview.ui
MotionControlDetails.ui
Pmc730Details.ui
SpectracomDetails.ui
XmitDetails.ui
""")
hcrguiEnv.Uic(uifiles)

# This generates the rules for *.qrc -> qrc_*.cc
qrcfiles = Split("""
HcrGuiMainWindow.qrc
""")
hcrguiEnv.Qrc(qrcfiles)

headers = Split("""
AntennaModeDialog.h
CmigitsDetails.h
DataMapperStatusThread.h
FireflydDetails.h
FireflydStatusThread.h
HcrdrxDetails.h
HcrdrxStatusThread.h
HcrExecutiveDetails.h
HcrGuiLogWindow.h
HcrGuiMainWindow.h
InsOverview.h
MotionControlDetails.h
Pmc730Details.h
SpectracomDetails.h
SpectracomStatusThread.h
XmitDetails.h
XmitdStatusThread.h
""")

html = hcrguiEnv.Apidocs(hcrgui_sources + headers)
Default(html)
