# -*- python -*-

# Beware tool ordering here! In particular, rapradar must be *after* 
# xmitdrpcclient. Reasons are unclear...
hcrguiTools = Split("""
boost_date_time
hcrpmc730client
cmigitsdaemonrpcclient
doxygen
fireflydRpcClient
hcrdrxrpcclient
logx
motioncontrol
xmitdrpcclient
rapradar
qt4
""")
hcrguiEnv = Environment(tools = ['default'] + hcrguiTools)
hcrguiEnv.EnableQt4Modules(['QtCore', 'QtGui'])

hcrgui_sources = Split("""
hcrgui.cpp
AntennaModeDialog.cpp
CmigitsDetails.cpp
DataMapperStatusThread.cpp
FireflydDetails.cpp
FireflydStatusThread.cpp
HcrdrxDetails.cpp
HcrdrxStatusThread.cpp
HcrGuiLogWindow.cpp
HcrGuiMainWindow.cpp
MotionControlDetails.cpp
MotionControlClientThread.cpp
Pmc730Details.cpp
qrc_HcrGuiMainWindow.cc
XmitDetails.cpp
XmitdStatusThread.cpp
""")
hcrgui = hcrguiEnv.Program('hcrgui', hcrgui_sources)
Default(hcrgui)

uifiles = Split("""
AntennaModeDialog.ui
CmigitsDetails.ui
FireflydDetails.ui
HcrdrxDetails.ui
HcrGuiLogWindow.ui
HcrGuiMainWindow.ui
MotionControlDetails.ui
Pmc730Details.ui
XmitDetails.ui
""")
hcrguiEnv.Uic4(uifiles)

# This generates the rules for *.qrc -> qrc_*.cc
qrcfiles = Split("""
HcrGuiMainWindow.qrc
""")
hcrguiEnv.Qrc(qrcfiles)

headers = Split("""
AntennaModeDialog.h
CmigitsDetails.h
DataMapperStatusThread.h
FireflydDetails.h
FireflydStatusThread.h
HcrdrxDetails.h
HcrdrxStatusThread.h
HcrGuiLogWindow.h
HcrGuiMainWindow.h
MotionControlDetails.h
MotionControlClientThread.h
Pmc730Details.h
XmitDetails.h
XmitdStatusThread.h
""")

html = hcrguiEnv.Apidocs(hcrgui_sources + headers)
Default(html)
