# -*- python -*-
#
# Build cmigitsDaemon
#

tools = Split('''
hcrpmc730client
boost_program_options
cmigits
doxygen
qt4
QFunctionWrapper
QXmlRpcServerAbyss
rapradar
xmlrpc_client++
''')

env = Environment(tools = ['default'] + tools)
env.EnableQt4Modules(['QtCore', 'QtGui'])

sources = Split('''
ApsControl.cpp
SafetyMonitor.cpp
TransmitControl.cpp
''')

headers = Split('''
ApsControl.h
TransmitControl.h
''')

daemon = env.Program('SafetyMonitor', sources)
Default(daemon)

env['DOXYFILE_DICT'].update({ "PROJECT_NAME" : "cmigits library" })
doxref = env.Apidocs(sources + headers)
Default(doxref)