# -*- python -*-
#
# Build SpatialFOGDaemon
#

tools = Split("""
doxygen
QFunctionWrapper
spatialfogcore
qt4
""")

env = Environment(tools = ['default'] + tools)
env.EnableQt4Modules(['QtCore', 'QtGui'])
env.AppendUnique(CXXFLAGS = ['-std=c++11'])

sources = Split('''
FDReader.cpp
QAnppPacketFactory.cpp
SpatialFOGDaemon.cpp
''')

headers = Split('''
FDReader.h
QAnppPacketFactory.h
''')

# env['DOXYFILE_DICT'].update({'PROJECT_NAME':'SpatialFOGDaemon'})
# html = env.Apidocs(sources + headers)
# Default(html)

daemon = env.Program('SpatialFOGDaemon', sources)
Default(daemon)
