# -*- python -*-
#
# Build SpatialFOGDaemon
#

tools = Split("""
doxygen
spatialfogcore
qt4
""")

env = Environment(tools = ['default'] + tools)
env.EnableQt4Modules(['QtCore', 'QtGui'])

sources = Split('''
FDReader.cpp
SpatialFOGDaemon.cpp
''')

headers = Split('''
FDReader.h
''')

env['DOXYFILE_DICT'].update({'PROJECT_NAME':'SpatialFOGDaemon'})
html = env.Apidocs(sources + headers)
Default(html)

daemon = env.Program('SpatialFOGDaemon', sources)
Default(daemon)
